// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	apapproto "github.com/Arm-Debug/apap-cli/clients/go/apapproto"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// ApapClient is an autogenerated mock type for the ApapClient type
type ApapClient struct {
	mock.Mock
}

type ApapClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ApapClient) EXPECT() *ApapClient_Expecter {
	return &ApapClient_Expecter{mock: &_m.Mock}
}

// CloseRender provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) CloseRender(ctx context.Context, in *apapproto.CloseRenderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CloseRender")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.CloseRenderRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.CloseRenderRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.CloseRenderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_CloseRender_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseRender'
type ApapClient_CloseRender_Call struct {
	*mock.Call
}

// CloseRender is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.CloseRenderRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) CloseRender(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_CloseRender_Call {
	return &ApapClient_CloseRender_Call{Call: _e.mock.On("CloseRender",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_CloseRender_Call) Run(run func(ctx context.Context, in *apapproto.CloseRenderRequest, opts ...grpc.CallOption)) *ApapClient_CloseRender_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.CloseRenderRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_CloseRender_Call) Return(_a0 *emptypb.Empty, _a1 error) *ApapClient_CloseRender_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_CloseRender_Call) RunAndReturn(run func(context.Context, *apapproto.CloseRenderRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *ApapClient_CloseRender_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSupportPackage provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) CreateSupportPackage(ctx context.Context, in *apapproto.CreateSupportPackageRequest, opts ...grpc.CallOption) (*apapproto.CreateSupportPackageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateSupportPackage")
	}

	var r0 *apapproto.CreateSupportPackageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.CreateSupportPackageRequest, ...grpc.CallOption) (*apapproto.CreateSupportPackageResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.CreateSupportPackageRequest, ...grpc.CallOption) *apapproto.CreateSupportPackageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.CreateSupportPackageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.CreateSupportPackageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_CreateSupportPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSupportPackage'
type ApapClient_CreateSupportPackage_Call struct {
	*mock.Call
}

// CreateSupportPackage is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.CreateSupportPackageRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) CreateSupportPackage(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_CreateSupportPackage_Call {
	return &ApapClient_CreateSupportPackage_Call{Call: _e.mock.On("CreateSupportPackage",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_CreateSupportPackage_Call) Run(run func(ctx context.Context, in *apapproto.CreateSupportPackageRequest, opts ...grpc.CallOption)) *ApapClient_CreateSupportPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.CreateSupportPackageRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_CreateSupportPackage_Call) Return(_a0 *apapproto.CreateSupportPackageResponse, _a1 error) *ApapClient_CreateSupportPackage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_CreateSupportPackage_Call) RunAndReturn(run func(context.Context, *apapproto.CreateSupportPackageRequest, ...grpc.CallOption) (*apapproto.CreateSupportPackageResponse, error)) *ApapClient_CreateSupportPackage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRun provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) DeleteRun(ctx context.Context, in *apapproto.RunId, opts ...grpc.CallOption) (*apapproto.DeleteRunResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRun")
	}

	var r0 *apapproto.DeleteRunResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RunId, ...grpc.CallOption) (*apapproto.DeleteRunResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RunId, ...grpc.CallOption) *apapproto.DeleteRunResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.DeleteRunResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.RunId, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_DeleteRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRun'
type ApapClient_DeleteRun_Call struct {
	*mock.Call
}

// DeleteRun is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.RunId
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) DeleteRun(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_DeleteRun_Call {
	return &ApapClient_DeleteRun_Call{Call: _e.mock.On("DeleteRun",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_DeleteRun_Call) Run(run func(ctx context.Context, in *apapproto.RunId, opts ...grpc.CallOption)) *ApapClient_DeleteRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.RunId), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_DeleteRun_Call) Return(_a0 *apapproto.DeleteRunResponse, _a1 error) *ApapClient_DeleteRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_DeleteRun_Call) RunAndReturn(run func(context.Context, *apapproto.RunId, ...grpc.CallOption) (*apapproto.DeleteRunResponse, error)) *ApapClient_DeleteRun_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRuns provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) DeleteRuns(ctx context.Context, in *apapproto.DeleteRunsRequest, opts ...grpc.CallOption) (*apapproto.DeleteRunsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRuns")
	}

	var r0 *apapproto.DeleteRunsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.DeleteRunsRequest, ...grpc.CallOption) (*apapproto.DeleteRunsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.DeleteRunsRequest, ...grpc.CallOption) *apapproto.DeleteRunsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.DeleteRunsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.DeleteRunsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_DeleteRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRuns'
type ApapClient_DeleteRuns_Call struct {
	*mock.Call
}

// DeleteRuns is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.DeleteRunsRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) DeleteRuns(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_DeleteRuns_Call {
	return &ApapClient_DeleteRuns_Call{Call: _e.mock.On("DeleteRuns",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_DeleteRuns_Call) Run(run func(ctx context.Context, in *apapproto.DeleteRunsRequest, opts ...grpc.CallOption)) *ApapClient_DeleteRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.DeleteRunsRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_DeleteRuns_Call) Return(_a0 *apapproto.DeleteRunsResponse, _a1 error) *ApapClient_DeleteRuns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_DeleteRuns_Call) RunAndReturn(run func(context.Context, *apapproto.DeleteRunsRequest, ...grpc.CallOption) (*apapproto.DeleteRunsResponse, error)) *ApapClient_DeleteRuns_Call {
	_c.Call.Return(run)
	return _c
}

// ExportRun provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) ExportRun(ctx context.Context, in *apapproto.RunExportRequest, opts ...grpc.CallOption) (*apapproto.RunExportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExportRun")
	}

	var r0 *apapproto.RunExportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RunExportRequest, ...grpc.CallOption) (*apapproto.RunExportResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RunExportRequest, ...grpc.CallOption) *apapproto.RunExportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.RunExportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.RunExportRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_ExportRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportRun'
type ApapClient_ExportRun_Call struct {
	*mock.Call
}

// ExportRun is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.RunExportRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) ExportRun(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_ExportRun_Call {
	return &ApapClient_ExportRun_Call{Call: _e.mock.On("ExportRun",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_ExportRun_Call) Run(run func(ctx context.Context, in *apapproto.RunExportRequest, opts ...grpc.CallOption)) *ApapClient_ExportRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.RunExportRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_ExportRun_Call) Return(_a0 *apapproto.RunExportResponse, _a1 error) *ApapClient_ExportRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_ExportRun_Call) RunAndReturn(run func(context.Context, *apapproto.RunExportRequest, ...grpc.CallOption) (*apapproto.RunExportResponse, error)) *ApapClient_ExportRun_Call {
	_c.Call.Return(run)
	return _c
}

// FindSSHKeysForTarget provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) FindSSHKeysForTarget(ctx context.Context, in *apapproto.Target, opts ...grpc.CallOption) (*apapproto.SSHKeyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindSSHKeysForTarget")
	}

	var r0 *apapproto.SSHKeyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.Target, ...grpc.CallOption) (*apapproto.SSHKeyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.Target, ...grpc.CallOption) *apapproto.SSHKeyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.SSHKeyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.Target, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_FindSSHKeysForTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSSHKeysForTarget'
type ApapClient_FindSSHKeysForTarget_Call struct {
	*mock.Call
}

// FindSSHKeysForTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.Target
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) FindSSHKeysForTarget(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_FindSSHKeysForTarget_Call {
	return &ApapClient_FindSSHKeysForTarget_Call{Call: _e.mock.On("FindSSHKeysForTarget",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_FindSSHKeysForTarget_Call) Run(run func(ctx context.Context, in *apapproto.Target, opts ...grpc.CallOption)) *ApapClient_FindSSHKeysForTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.Target), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_FindSSHKeysForTarget_Call) Return(_a0 *apapproto.SSHKeyResponse, _a1 error) *ApapClient_FindSSHKeysForTarget_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_FindSSHKeysForTarget_Call) RunAndReturn(run func(context.Context, *apapproto.Target, ...grpc.CallOption) (*apapproto.SSHKeyResponse, error)) *ApapClient_FindSSHKeysForTarget_Call {
	_c.Call.Return(run)
	return _c
}

// GetRunDescription provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) GetRunDescription(ctx context.Context, in *apapproto.GetRunDescriptionRequest, opts ...grpc.CallOption) (*apapproto.RunDescription, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetRunDescription")
	}

	var r0 *apapproto.RunDescription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.GetRunDescriptionRequest, ...grpc.CallOption) (*apapproto.RunDescription, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.GetRunDescriptionRequest, ...grpc.CallOption) *apapproto.RunDescription); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.RunDescription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.GetRunDescriptionRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_GetRunDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRunDescription'
type ApapClient_GetRunDescription_Call struct {
	*mock.Call
}

// GetRunDescription is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.GetRunDescriptionRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) GetRunDescription(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_GetRunDescription_Call {
	return &ApapClient_GetRunDescription_Call{Call: _e.mock.On("GetRunDescription",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_GetRunDescription_Call) Run(run func(ctx context.Context, in *apapproto.GetRunDescriptionRequest, opts ...grpc.CallOption)) *ApapClient_GetRunDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.GetRunDescriptionRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_GetRunDescription_Call) Return(_a0 *apapproto.RunDescription, _a1 error) *ApapClient_GetRunDescription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_GetRunDescription_Call) RunAndReturn(run func(context.Context, *apapproto.GetRunDescriptionRequest, ...grpc.CallOption) (*apapproto.RunDescription, error)) *ApapClient_GetRunDescription_Call {
	_c.Call.Return(run)
	return _c
}

// GetRunSummaryBundle provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) GetRunSummaryBundle(ctx context.Context, in *apapproto.RunSummaryBundleRequest, opts ...grpc.CallOption) (*apapproto.RunSummaryBundleResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetRunSummaryBundle")
	}

	var r0 *apapproto.RunSummaryBundleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RunSummaryBundleRequest, ...grpc.CallOption) (*apapproto.RunSummaryBundleResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RunSummaryBundleRequest, ...grpc.CallOption) *apapproto.RunSummaryBundleResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.RunSummaryBundleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.RunSummaryBundleRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_GetRunSummaryBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRunSummaryBundle'
type ApapClient_GetRunSummaryBundle_Call struct {
	*mock.Call
}

// GetRunSummaryBundle is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.RunSummaryBundleRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) GetRunSummaryBundle(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_GetRunSummaryBundle_Call {
	return &ApapClient_GetRunSummaryBundle_Call{Call: _e.mock.On("GetRunSummaryBundle",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_GetRunSummaryBundle_Call) Run(run func(ctx context.Context, in *apapproto.RunSummaryBundleRequest, opts ...grpc.CallOption)) *ApapClient_GetRunSummaryBundle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.RunSummaryBundleRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_GetRunSummaryBundle_Call) Return(_a0 *apapproto.RunSummaryBundleResponse, _a1 error) *ApapClient_GetRunSummaryBundle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_GetRunSummaryBundle_Call) RunAndReturn(run func(context.Context, *apapproto.RunSummaryBundleRequest, ...grpc.CallOption) (*apapproto.RunSummaryBundleResponse, error)) *ApapClient_GetRunSummaryBundle_Call {
	_c.Call.Return(run)
	return _c
}

// GetTelemetrySpecification provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) GetTelemetrySpecification(ctx context.Context, in *apapproto.GetTelemetrySpecificationRequest, opts ...grpc.CallOption) (*apapproto.GetTelemetrySpecificationResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTelemetrySpecification")
	}

	var r0 *apapproto.GetTelemetrySpecificationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.GetTelemetrySpecificationRequest, ...grpc.CallOption) (*apapproto.GetTelemetrySpecificationResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.GetTelemetrySpecificationRequest, ...grpc.CallOption) *apapproto.GetTelemetrySpecificationResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.GetTelemetrySpecificationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.GetTelemetrySpecificationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_GetTelemetrySpecification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTelemetrySpecification'
type ApapClient_GetTelemetrySpecification_Call struct {
	*mock.Call
}

// GetTelemetrySpecification is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.GetTelemetrySpecificationRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) GetTelemetrySpecification(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_GetTelemetrySpecification_Call {
	return &ApapClient_GetTelemetrySpecification_Call{Call: _e.mock.On("GetTelemetrySpecification",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_GetTelemetrySpecification_Call) Run(run func(ctx context.Context, in *apapproto.GetTelemetrySpecificationRequest, opts ...grpc.CallOption)) *ApapClient_GetTelemetrySpecification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.GetTelemetrySpecificationRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_GetTelemetrySpecification_Call) Return(_a0 *apapproto.GetTelemetrySpecificationResponse, _a1 error) *ApapClient_GetTelemetrySpecification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_GetTelemetrySpecification_Call) RunAndReturn(run func(context.Context, *apapproto.GetTelemetrySpecificationRequest, ...grpc.CallOption) (*apapproto.GetTelemetrySpecificationResponse, error)) *ApapClient_GetTelemetrySpecification_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*apapproto.ServiceVersion, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 *apapproto.ServiceVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*apapproto.ServiceVersion, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *apapproto.ServiceVersion); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.ServiceVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type ApapClient_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) GetVersion(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_GetVersion_Call {
	return &ApapClient_GetVersion_Call{Call: _e.mock.On("GetVersion",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_GetVersion_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *ApapClient_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_GetVersion_Call) Return(_a0 *apapproto.ServiceVersion, _a1 error) *ApapClient_GetVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_GetVersion_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*apapproto.ServiceVersion, error)) *ApapClient_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ImportRun provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) ImportRun(ctx context.Context, in *apapproto.RunImportRequest, opts ...grpc.CallOption) (*apapproto.RunImportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ImportRun")
	}

	var r0 *apapproto.RunImportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RunImportRequest, ...grpc.CallOption) (*apapproto.RunImportResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RunImportRequest, ...grpc.CallOption) *apapproto.RunImportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.RunImportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.RunImportRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_ImportRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportRun'
type ApapClient_ImportRun_Call struct {
	*mock.Call
}

// ImportRun is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.RunImportRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) ImportRun(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_ImportRun_Call {
	return &ApapClient_ImportRun_Call{Call: _e.mock.On("ImportRun",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_ImportRun_Call) Run(run func(ctx context.Context, in *apapproto.RunImportRequest, opts ...grpc.CallOption)) *ApapClient_ImportRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.RunImportRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_ImportRun_Call) Return(_a0 *apapproto.RunImportResponse, _a1 error) *ApapClient_ImportRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_ImportRun_Call) RunAndReturn(run func(context.Context, *apapproto.RunImportRequest, ...grpc.CallOption) (*apapproto.RunImportResponse, error)) *ApapClient_ImportRun_Call {
	_c.Call.Return(run)
	return _c
}

// InvokeRender provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) InvokeRender(ctx context.Context, in *apapproto.InvokeRenderRequest, opts ...grpc.CallOption) (*apapproto.InvokeRenderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for InvokeRender")
	}

	var r0 *apapproto.InvokeRenderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.InvokeRenderRequest, ...grpc.CallOption) (*apapproto.InvokeRenderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.InvokeRenderRequest, ...grpc.CallOption) *apapproto.InvokeRenderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.InvokeRenderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.InvokeRenderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_InvokeRender_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvokeRender'
type ApapClient_InvokeRender_Call struct {
	*mock.Call
}

// InvokeRender is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.InvokeRenderRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) InvokeRender(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_InvokeRender_Call {
	return &ApapClient_InvokeRender_Call{Call: _e.mock.On("InvokeRender",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_InvokeRender_Call) Run(run func(ctx context.Context, in *apapproto.InvokeRenderRequest, opts ...grpc.CallOption)) *ApapClient_InvokeRender_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.InvokeRenderRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_InvokeRender_Call) Return(_a0 *apapproto.InvokeRenderResponse, _a1 error) *ApapClient_InvokeRender_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_InvokeRender_Call) RunAndReturn(run func(context.Context, *apapproto.InvokeRenderRequest, ...grpc.CallOption) (*apapproto.InvokeRenderResponse, error)) *ApapClient_InvokeRender_Call {
	_c.Call.Return(run)
	return _c
}

// ListAndroidPackages provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) ListAndroidPackages(ctx context.Context, in *apapproto.ListAndroidPackagesRequest, opts ...grpc.CallOption) (*apapproto.ListAndroidPackagesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListAndroidPackages")
	}

	var r0 *apapproto.ListAndroidPackagesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.ListAndroidPackagesRequest, ...grpc.CallOption) (*apapproto.ListAndroidPackagesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.ListAndroidPackagesRequest, ...grpc.CallOption) *apapproto.ListAndroidPackagesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.ListAndroidPackagesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.ListAndroidPackagesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_ListAndroidPackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAndroidPackages'
type ApapClient_ListAndroidPackages_Call struct {
	*mock.Call
}

// ListAndroidPackages is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.ListAndroidPackagesRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) ListAndroidPackages(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_ListAndroidPackages_Call {
	return &ApapClient_ListAndroidPackages_Call{Call: _e.mock.On("ListAndroidPackages",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_ListAndroidPackages_Call) Run(run func(ctx context.Context, in *apapproto.ListAndroidPackagesRequest, opts ...grpc.CallOption)) *ApapClient_ListAndroidPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.ListAndroidPackagesRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_ListAndroidPackages_Call) Return(_a0 *apapproto.ListAndroidPackagesResponse, _a1 error) *ApapClient_ListAndroidPackages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_ListAndroidPackages_Call) RunAndReturn(run func(context.Context, *apapproto.ListAndroidPackagesRequest, ...grpc.CallOption) (*apapproto.ListAndroidPackagesResponse, error)) *ApapClient_ListAndroidPackages_Call {
	_c.Call.Return(run)
	return _c
}

// ListDirectories provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) ListDirectories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*apapproto.ListDirectoriesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListDirectories")
	}

	var r0 *apapproto.ListDirectoriesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*apapproto.ListDirectoriesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *apapproto.ListDirectoriesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.ListDirectoriesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_ListDirectories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDirectories'
type ApapClient_ListDirectories_Call struct {
	*mock.Call
}

// ListDirectories is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) ListDirectories(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_ListDirectories_Call {
	return &ApapClient_ListDirectories_Call{Call: _e.mock.On("ListDirectories",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_ListDirectories_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *ApapClient_ListDirectories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_ListDirectories_Call) Return(_a0 *apapproto.ListDirectoriesResponse, _a1 error) *ApapClient_ListDirectories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_ListDirectories_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*apapproto.ListDirectoriesResponse, error)) *ApapClient_ListDirectories_Call {
	_c.Call.Return(run)
	return _c
}

// ListPrivateSSHKeys provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) ListPrivateSSHKeys(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*apapproto.PrivateSSHKeyListing, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListPrivateSSHKeys")
	}

	var r0 *apapproto.PrivateSSHKeyListing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*apapproto.PrivateSSHKeyListing, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *apapproto.PrivateSSHKeyListing); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.PrivateSSHKeyListing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_ListPrivateSSHKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPrivateSSHKeys'
type ApapClient_ListPrivateSSHKeys_Call struct {
	*mock.Call
}

// ListPrivateSSHKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) ListPrivateSSHKeys(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_ListPrivateSSHKeys_Call {
	return &ApapClient_ListPrivateSSHKeys_Call{Call: _e.mock.On("ListPrivateSSHKeys",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_ListPrivateSSHKeys_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *ApapClient_ListPrivateSSHKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_ListPrivateSSHKeys_Call) Return(_a0 *apapproto.PrivateSSHKeyListing, _a1 error) *ApapClient_ListPrivateSSHKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_ListPrivateSSHKeys_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*apapproto.PrivateSSHKeyListing, error)) *ApapClient_ListPrivateSSHKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecipes provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) ListRecipes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*apapproto.RecipeNameListing, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListRecipes")
	}

	var r0 *apapproto.RecipeNameListing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*apapproto.RecipeNameListing, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *apapproto.RecipeNameListing); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.RecipeNameListing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_ListRecipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecipes'
type ApapClient_ListRecipes_Call struct {
	*mock.Call
}

// ListRecipes is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) ListRecipes(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_ListRecipes_Call {
	return &ApapClient_ListRecipes_Call{Call: _e.mock.On("ListRecipes",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_ListRecipes_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *ApapClient_ListRecipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_ListRecipes_Call) Return(_a0 *apapproto.RecipeNameListing, _a1 error) *ApapClient_ListRecipes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_ListRecipes_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*apapproto.RecipeNameListing, error)) *ApapClient_ListRecipes_Call {
	_c.Call.Return(run)
	return _c
}

// ListRenders provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) ListRenders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*apapproto.RenderListing, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListRenders")
	}

	var r0 *apapproto.RenderListing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*apapproto.RenderListing, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *apapproto.RenderListing); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.RenderListing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_ListRenders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRenders'
type ApapClient_ListRenders_Call struct {
	*mock.Call
}

// ListRenders is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) ListRenders(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_ListRenders_Call {
	return &ApapClient_ListRenders_Call{Call: _e.mock.On("ListRenders",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_ListRenders_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *ApapClient_ListRenders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_ListRenders_Call) Return(_a0 *apapproto.RenderListing, _a1 error) *ApapClient_ListRenders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_ListRenders_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*apapproto.RenderListing, error)) *ApapClient_ListRenders_Call {
	_c.Call.Return(run)
	return _c
}

// ListRuns provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) ListRuns(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*apapproto.RunListing, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListRuns")
	}

	var r0 *apapproto.RunListing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*apapproto.RunListing, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *apapproto.RunListing); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.RunListing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_ListRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRuns'
type ApapClient_ListRuns_Call struct {
	*mock.Call
}

// ListRuns is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) ListRuns(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_ListRuns_Call {
	return &ApapClient_ListRuns_Call{Call: _e.mock.On("ListRuns",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_ListRuns_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *ApapClient_ListRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_ListRuns_Call) Return(_a0 *apapproto.RunListing, _a1 error) *ApapClient_ListRuns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_ListRuns_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*apapproto.RunListing, error)) *ApapClient_ListRuns_Call {
	_c.Call.Return(run)
	return _c
}

// LookupMessage provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) LookupMessage(ctx context.Context, in *apapproto.LookupMessageRequest, opts ...grpc.CallOption) (*apapproto.LookupMessageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LookupMessage")
	}

	var r0 *apapproto.LookupMessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.LookupMessageRequest, ...grpc.CallOption) (*apapproto.LookupMessageResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.LookupMessageRequest, ...grpc.CallOption) *apapproto.LookupMessageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.LookupMessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.LookupMessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_LookupMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupMessage'
type ApapClient_LookupMessage_Call struct {
	*mock.Call
}

// LookupMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.LookupMessageRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) LookupMessage(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_LookupMessage_Call {
	return &ApapClient_LookupMessage_Call{Call: _e.mock.On("LookupMessage",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_LookupMessage_Call) Run(run func(ctx context.Context, in *apapproto.LookupMessageRequest, opts ...grpc.CallOption)) *ApapClient_LookupMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.LookupMessageRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_LookupMessage_Call) Return(_a0 *apapproto.LookupMessageResponse, _a1 error) *ApapClient_LookupMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_LookupMessage_Call) RunAndReturn(run func(context.Context, *apapproto.LookupMessageRequest, ...grpc.CallOption) (*apapproto.LookupMessageResponse, error)) *ApapClient_LookupMessage_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRecipe provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) ParseRecipe(ctx context.Context, in *apapproto.ParseRecipeMessage, opts ...grpc.CallOption) (*apapproto.ParseRecipeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ParseRecipe")
	}

	var r0 *apapproto.ParseRecipeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.ParseRecipeMessage, ...grpc.CallOption) (*apapproto.ParseRecipeResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.ParseRecipeMessage, ...grpc.CallOption) *apapproto.ParseRecipeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.ParseRecipeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.ParseRecipeMessage, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_ParseRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRecipe'
type ApapClient_ParseRecipe_Call struct {
	*mock.Call
}

// ParseRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.ParseRecipeMessage
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) ParseRecipe(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_ParseRecipe_Call {
	return &ApapClient_ParseRecipe_Call{Call: _e.mock.On("ParseRecipe",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_ParseRecipe_Call) Run(run func(ctx context.Context, in *apapproto.ParseRecipeMessage, opts ...grpc.CallOption)) *ApapClient_ParseRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.ParseRecipeMessage), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_ParseRecipe_Call) Return(_a0 *apapproto.ParseRecipeResponse, _a1 error) *ApapClient_ParseRecipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_ParseRecipe_Call) RunAndReturn(run func(context.Context, *apapproto.ParseRecipeMessage, ...grpc.CallOption) (*apapproto.ParseRecipeResponse, error)) *ApapClient_ParseRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareRender provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) PrepareRender(ctx context.Context, in *apapproto.PrepareRenderRequest, opts ...grpc.CallOption) (*apapproto.PrepareRenderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PrepareRender")
	}

	var r0 *apapproto.PrepareRenderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.PrepareRenderRequest, ...grpc.CallOption) (*apapproto.PrepareRenderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.PrepareRenderRequest, ...grpc.CallOption) *apapproto.PrepareRenderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.PrepareRenderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.PrepareRenderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_PrepareRender_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareRender'
type ApapClient_PrepareRender_Call struct {
	*mock.Call
}

// PrepareRender is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.PrepareRenderRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) PrepareRender(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_PrepareRender_Call {
	return &ApapClient_PrepareRender_Call{Call: _e.mock.On("PrepareRender",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_PrepareRender_Call) Run(run func(ctx context.Context, in *apapproto.PrepareRenderRequest, opts ...grpc.CallOption)) *ApapClient_PrepareRender_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.PrepareRenderRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_PrepareRender_Call) Return(_a0 *apapproto.PrepareRenderResponse, _a1 error) *ApapClient_PrepareRender_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_PrepareRender_Call) RunAndReturn(run func(context.Context, *apapproto.PrepareRenderRequest, ...grpc.CallOption) (*apapproto.PrepareRenderResponse, error)) *ApapClient_PrepareRender_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) Query(ctx context.Context, in *apapproto.QueryRequest, opts ...grpc.CallOption) (apapproto.Apap_QueryClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 apapproto.Apap_QueryClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.QueryRequest, ...grpc.CallOption) (apapproto.Apap_QueryClient, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.QueryRequest, ...grpc.CallOption) apapproto.Apap_QueryClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apapproto.Apap_QueryClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.QueryRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type ApapClient_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.QueryRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) Query(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_Query_Call {
	return &ApapClient_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_Query_Call) Run(run func(ctx context.Context, in *apapproto.QueryRequest, opts ...grpc.CallOption)) *ApapClient_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.QueryRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_Query_Call) Return(_a0 apapproto.Apap_QueryClient, _a1 error) *ApapClient_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_Query_Call) RunAndReturn(run func(context.Context, *apapproto.QueryRequest, ...grpc.CallOption) (apapproto.Apap_QueryClient, error)) *ApapClient_Query_Call {
	_c.Call.Return(run)
	return _c
}

// RecipeIssueCommand provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) RecipeIssueCommand(ctx context.Context, in *apapproto.RecipeCommand, opts ...grpc.CallOption) (apapproto.Apap_RecipeIssueCommandClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RecipeIssueCommand")
	}

	var r0 apapproto.Apap_RecipeIssueCommandClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RecipeCommand, ...grpc.CallOption) (apapproto.Apap_RecipeIssueCommandClient, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RecipeCommand, ...grpc.CallOption) apapproto.Apap_RecipeIssueCommandClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apapproto.Apap_RecipeIssueCommandClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.RecipeCommand, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_RecipeIssueCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecipeIssueCommand'
type ApapClient_RecipeIssueCommand_Call struct {
	*mock.Call
}

// RecipeIssueCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.RecipeCommand
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) RecipeIssueCommand(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_RecipeIssueCommand_Call {
	return &ApapClient_RecipeIssueCommand_Call{Call: _e.mock.On("RecipeIssueCommand",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_RecipeIssueCommand_Call) Run(run func(ctx context.Context, in *apapproto.RecipeCommand, opts ...grpc.CallOption)) *ApapClient_RecipeIssueCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.RecipeCommand), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_RecipeIssueCommand_Call) Return(_a0 apapproto.Apap_RecipeIssueCommandClient, _a1 error) *ApapClient_RecipeIssueCommand_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_RecipeIssueCommand_Call) RunAndReturn(run func(context.Context, *apapproto.RecipeCommand, ...grpc.CallOption) (apapproto.Apap_RecipeIssueCommandClient, error)) *ApapClient_RecipeIssueCommand_Call {
	_c.Call.Return(run)
	return _c
}

// RecipeReady provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) RecipeReady(ctx context.Context, in *apapproto.RecipeReadyRequest, opts ...grpc.CallOption) (*apapproto.RecipeReadyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RecipeReady")
	}

	var r0 *apapproto.RecipeReadyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RecipeReadyRequest, ...grpc.CallOption) (*apapproto.RecipeReadyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RecipeReadyRequest, ...grpc.CallOption) *apapproto.RecipeReadyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.RecipeReadyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.RecipeReadyRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_RecipeReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecipeReady'
type ApapClient_RecipeReady_Call struct {
	*mock.Call
}

// RecipeReady is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.RecipeReadyRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) RecipeReady(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_RecipeReady_Call {
	return &ApapClient_RecipeReady_Call{Call: _e.mock.On("RecipeReady",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_RecipeReady_Call) Run(run func(ctx context.Context, in *apapproto.RecipeReadyRequest, opts ...grpc.CallOption)) *ApapClient_RecipeReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.RecipeReadyRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_RecipeReady_Call) Return(_a0 *apapproto.RecipeReadyResponse, _a1 error) *ApapClient_RecipeReady_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_RecipeReady_Call) RunAndReturn(run func(context.Context, *apapproto.RecipeReadyRequest, ...grpc.CallOption) (*apapproto.RecipeReadyResponse, error)) *ApapClient_RecipeReady_Call {
	_c.Call.Return(run)
	return _c
}

// RecipeValidateParameters provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) RecipeValidateParameters(ctx context.Context, in *apapproto.RecipeValidateParametersRequest, opts ...grpc.CallOption) (*apapproto.RecipeValidateParametersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RecipeValidateParameters")
	}

	var r0 *apapproto.RecipeValidateParametersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RecipeValidateParametersRequest, ...grpc.CallOption) (*apapproto.RecipeValidateParametersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RecipeValidateParametersRequest, ...grpc.CallOption) *apapproto.RecipeValidateParametersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.RecipeValidateParametersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.RecipeValidateParametersRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_RecipeValidateParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecipeValidateParameters'
type ApapClient_RecipeValidateParameters_Call struct {
	*mock.Call
}

// RecipeValidateParameters is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.RecipeValidateParametersRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) RecipeValidateParameters(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_RecipeValidateParameters_Call {
	return &ApapClient_RecipeValidateParameters_Call{Call: _e.mock.On("RecipeValidateParameters",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_RecipeValidateParameters_Call) Run(run func(ctx context.Context, in *apapproto.RecipeValidateParametersRequest, opts ...grpc.CallOption)) *ApapClient_RecipeValidateParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.RecipeValidateParametersRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_RecipeValidateParameters_Call) Return(_a0 *apapproto.RecipeValidateParametersResponse, _a1 error) *ApapClient_RecipeValidateParameters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_RecipeValidateParameters_Call) RunAndReturn(run func(context.Context, *apapproto.RecipeValidateParametersRequest, ...grpc.CallOption) (*apapproto.RecipeValidateParametersResponse, error)) *ApapClient_RecipeValidateParameters_Call {
	_c.Call.Return(run)
	return _c
}

// RenameRun provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) RenameRun(ctx context.Context, in *apapproto.RunRenameRequest, opts ...grpc.CallOption) (*apapproto.RunRenameResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RenameRun")
	}

	var r0 *apapproto.RunRenameResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RunRenameRequest, ...grpc.CallOption) (*apapproto.RunRenameResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.RunRenameRequest, ...grpc.CallOption) *apapproto.RunRenameResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.RunRenameResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.RunRenameRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_RenameRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameRun'
type ApapClient_RenameRun_Call struct {
	*mock.Call
}

// RenameRun is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.RunRenameRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) RenameRun(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_RenameRun_Call {
	return &ApapClient_RenameRun_Call{Call: _e.mock.On("RenameRun",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_RenameRun_Call) Run(run func(ctx context.Context, in *apapproto.RunRenameRequest, opts ...grpc.CallOption)) *ApapClient_RenameRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.RunRenameRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_RenameRun_Call) Return(_a0 *apapproto.RunRenameResponse, _a1 error) *ApapClient_RenameRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_RenameRun_Call) RunAndReturn(run func(context.Context, *apapproto.RunRenameRequest, ...grpc.CallOption) (*apapproto.RunRenameResponse, error)) *ApapClient_RenameRun_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type ApapClient_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) Shutdown(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_Shutdown_Call {
	return &ApapClient_Shutdown_Call{Call: _e.mock.On("Shutdown",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_Shutdown_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *ApapClient_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_Shutdown_Call) Return(_a0 *emptypb.Empty, _a1 error) *ApapClient_Shutdown_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_Shutdown_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)) *ApapClient_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// TargetInfoCollector provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) TargetInfoCollector(ctx context.Context, in *apapproto.TargetInfoRequest, opts ...grpc.CallOption) (*apapproto.TargetInfoResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TargetInfoCollector")
	}

	var r0 *apapproto.TargetInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.TargetInfoRequest, ...grpc.CallOption) (*apapproto.TargetInfoResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.TargetInfoRequest, ...grpc.CallOption) *apapproto.TargetInfoResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.TargetInfoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.TargetInfoRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_TargetInfoCollector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TargetInfoCollector'
type ApapClient_TargetInfoCollector_Call struct {
	*mock.Call
}

// TargetInfoCollector is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.TargetInfoRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) TargetInfoCollector(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_TargetInfoCollector_Call {
	return &ApapClient_TargetInfoCollector_Call{Call: _e.mock.On("TargetInfoCollector",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_TargetInfoCollector_Call) Run(run func(ctx context.Context, in *apapproto.TargetInfoRequest, opts ...grpc.CallOption)) *ApapClient_TargetInfoCollector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.TargetInfoRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_TargetInfoCollector_Call) Return(_a0 *apapproto.TargetInfoResponse, _a1 error) *ApapClient_TargetInfoCollector_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_TargetInfoCollector_Call) RunAndReturn(run func(context.Context, *apapproto.TargetInfoRequest, ...grpc.CallOption) (*apapproto.TargetInfoResponse, error)) *ApapClient_TargetInfoCollector_Call {
	_c.Call.Return(run)
	return _c
}

// TargetPrepare provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) TargetPrepare(ctx context.Context, in *apapproto.TargetPrepareRequest, opts ...grpc.CallOption) (*apapproto.TargetPrepareResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TargetPrepare")
	}

	var r0 *apapproto.TargetPrepareResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.TargetPrepareRequest, ...grpc.CallOption) (*apapproto.TargetPrepareResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.TargetPrepareRequest, ...grpc.CallOption) *apapproto.TargetPrepareResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.TargetPrepareResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.TargetPrepareRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_TargetPrepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TargetPrepare'
type ApapClient_TargetPrepare_Call struct {
	*mock.Call
}

// TargetPrepare is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.TargetPrepareRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) TargetPrepare(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_TargetPrepare_Call {
	return &ApapClient_TargetPrepare_Call{Call: _e.mock.On("TargetPrepare",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_TargetPrepare_Call) Run(run func(ctx context.Context, in *apapproto.TargetPrepareRequest, opts ...grpc.CallOption)) *ApapClient_TargetPrepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.TargetPrepareRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_TargetPrepare_Call) Return(_a0 *apapproto.TargetPrepareResponse, _a1 error) *ApapClient_TargetPrepare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_TargetPrepare_Call) RunAndReturn(run func(context.Context, *apapproto.TargetPrepareRequest, ...grpc.CallOption) (*apapproto.TargetPrepareResponse, error)) *ApapClient_TargetPrepare_Call {
	_c.Call.Return(run)
	return _c
}

// TargetTest provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) TargetTest(ctx context.Context, in *apapproto.TargetTestRequest, opts ...grpc.CallOption) (*apapproto.TargetTestResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TargetTest")
	}

	var r0 *apapproto.TargetTestResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.TargetTestRequest, ...grpc.CallOption) (*apapproto.TargetTestResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.TargetTestRequest, ...grpc.CallOption) *apapproto.TargetTestResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.TargetTestResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.TargetTestRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_TargetTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TargetTest'
type ApapClient_TargetTest_Call struct {
	*mock.Call
}

// TargetTest is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.TargetTestRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) TargetTest(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_TargetTest_Call {
	return &ApapClient_TargetTest_Call{Call: _e.mock.On("TargetTest",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_TargetTest_Call) Run(run func(ctx context.Context, in *apapproto.TargetTestRequest, opts ...grpc.CallOption)) *ApapClient_TargetTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.TargetTestRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_TargetTest_Call) Return(_a0 *apapproto.TargetTestResponse, _a1 error) *ApapClient_TargetTest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_TargetTest_Call) RunAndReturn(run func(context.Context, *apapproto.TargetTestRequest, ...grpc.CallOption) (*apapproto.TargetTestResponse, error)) *ApapClient_TargetTest_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRuns provides a mock function with given fields: ctx, in, opts
func (_m *ApapClient) UpdateRuns(ctx context.Context, in *apapproto.UpdateRunsRequest, opts ...grpc.CallOption) (*apapproto.UpdateRunsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRuns")
	}

	var r0 *apapproto.UpdateRunsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.UpdateRunsRequest, ...grpc.CallOption) (*apapproto.UpdateRunsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apapproto.UpdateRunsRequest, ...grpc.CallOption) *apapproto.UpdateRunsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apapproto.UpdateRunsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apapproto.UpdateRunsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApapClient_UpdateRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRuns'
type ApapClient_UpdateRuns_Call struct {
	*mock.Call
}

// UpdateRuns is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apapproto.UpdateRunsRequest
//   - opts ...grpc.CallOption
func (_e *ApapClient_Expecter) UpdateRuns(ctx interface{}, in interface{}, opts ...interface{}) *ApapClient_UpdateRuns_Call {
	return &ApapClient_UpdateRuns_Call{Call: _e.mock.On("UpdateRuns",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ApapClient_UpdateRuns_Call) Run(run func(ctx context.Context, in *apapproto.UpdateRunsRequest, opts ...grpc.CallOption)) *ApapClient_UpdateRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apapproto.UpdateRunsRequest), variadicArgs...)
	})
	return _c
}

func (_c *ApapClient_UpdateRuns_Call) Return(_a0 *apapproto.UpdateRunsResponse, _a1 error) *ApapClient_UpdateRuns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApapClient_UpdateRuns_Call) RunAndReturn(run func(context.Context, *apapproto.UpdateRunsRequest, ...grpc.CallOption) (*apapproto.UpdateRunsResponse, error)) *ApapClient_UpdateRuns_Call {
	_c.Call.Return(run)
	return _c
}

// NewApapClient creates a new instance of ApapClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApapClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApapClient {
	mock := &ApapClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
