// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	authproto "github.com/Arm-Debug/apap-cli/clients/go/authproto"
	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"
)

// AuthTargetLoginServer is an autogenerated mock type for the Auth_TargetLoginServer type
type AuthTargetLoginServer struct {
	mock.Mock
}

type AuthTargetLoginServer_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthTargetLoginServer) EXPECT() *AuthTargetLoginServer_Expecter {
	return &AuthTargetLoginServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with no fields
func (_m *AuthTargetLoginServer) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// AuthTargetLoginServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type AuthTargetLoginServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *AuthTargetLoginServer_Expecter) Context() *AuthTargetLoginServer_Context_Call {
	return &AuthTargetLoginServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *AuthTargetLoginServer_Context_Call) Run(run func()) *AuthTargetLoginServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthTargetLoginServer_Context_Call) Return(_a0 context.Context) *AuthTargetLoginServer_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthTargetLoginServer_Context_Call) RunAndReturn(run func() context.Context) *AuthTargetLoginServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function with no fields
func (_m *AuthTargetLoginServer) Recv() (*authproto.TargetLoginClientMessage, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *authproto.TargetLoginClientMessage
	var r1 error
	if rf, ok := ret.Get(0).(func() (*authproto.TargetLoginClientMessage, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *authproto.TargetLoginClientMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authproto.TargetLoginClientMessage)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthTargetLoginServer_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type AuthTargetLoginServer_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *AuthTargetLoginServer_Expecter) Recv() *AuthTargetLoginServer_Recv_Call {
	return &AuthTargetLoginServer_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *AuthTargetLoginServer_Recv_Call) Run(run func()) *AuthTargetLoginServer_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthTargetLoginServer_Recv_Call) Return(_a0 *authproto.TargetLoginClientMessage, _a1 error) *AuthTargetLoginServer_Recv_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthTargetLoginServer_Recv_Call) RunAndReturn(run func() (*authproto.TargetLoginClientMessage, error)) *AuthTargetLoginServer_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *AuthTargetLoginServer) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthTargetLoginServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type AuthTargetLoginServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *AuthTargetLoginServer_Expecter) RecvMsg(m interface{}) *AuthTargetLoginServer_RecvMsg_Call {
	return &AuthTargetLoginServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *AuthTargetLoginServer_RecvMsg_Call) Run(run func(m interface{})) *AuthTargetLoginServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *AuthTargetLoginServer_RecvMsg_Call) Return(_a0 error) *AuthTargetLoginServer_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthTargetLoginServer_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *AuthTargetLoginServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *AuthTargetLoginServer) Send(_a0 *authproto.TargetLoginServerMessage) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*authproto.TargetLoginServerMessage) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthTargetLoginServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type AuthTargetLoginServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *authproto.TargetLoginServerMessage
func (_e *AuthTargetLoginServer_Expecter) Send(_a0 interface{}) *AuthTargetLoginServer_Send_Call {
	return &AuthTargetLoginServer_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *AuthTargetLoginServer_Send_Call) Run(run func(_a0 *authproto.TargetLoginServerMessage)) *AuthTargetLoginServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*authproto.TargetLoginServerMessage))
	})
	return _c
}

func (_c *AuthTargetLoginServer_Send_Call) Return(_a0 error) *AuthTargetLoginServer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthTargetLoginServer_Send_Call) RunAndReturn(run func(*authproto.TargetLoginServerMessage) error) *AuthTargetLoginServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *AuthTargetLoginServer) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthTargetLoginServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type AuthTargetLoginServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *AuthTargetLoginServer_Expecter) SendHeader(_a0 interface{}) *AuthTargetLoginServer_SendHeader_Call {
	return &AuthTargetLoginServer_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *AuthTargetLoginServer_SendHeader_Call) Run(run func(_a0 metadata.MD)) *AuthTargetLoginServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *AuthTargetLoginServer_SendHeader_Call) Return(_a0 error) *AuthTargetLoginServer_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthTargetLoginServer_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *AuthTargetLoginServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *AuthTargetLoginServer) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthTargetLoginServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type AuthTargetLoginServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *AuthTargetLoginServer_Expecter) SendMsg(m interface{}) *AuthTargetLoginServer_SendMsg_Call {
	return &AuthTargetLoginServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *AuthTargetLoginServer_SendMsg_Call) Run(run func(m interface{})) *AuthTargetLoginServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *AuthTargetLoginServer_SendMsg_Call) Return(_a0 error) *AuthTargetLoginServer_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthTargetLoginServer_SendMsg_Call) RunAndReturn(run func(interface{}) error) *AuthTargetLoginServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *AuthTargetLoginServer) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthTargetLoginServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type AuthTargetLoginServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *AuthTargetLoginServer_Expecter) SetHeader(_a0 interface{}) *AuthTargetLoginServer_SetHeader_Call {
	return &AuthTargetLoginServer_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *AuthTargetLoginServer_SetHeader_Call) Run(run func(_a0 metadata.MD)) *AuthTargetLoginServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *AuthTargetLoginServer_SetHeader_Call) Return(_a0 error) *AuthTargetLoginServer_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthTargetLoginServer_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *AuthTargetLoginServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *AuthTargetLoginServer) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// AuthTargetLoginServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type AuthTargetLoginServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *AuthTargetLoginServer_Expecter) SetTrailer(_a0 interface{}) *AuthTargetLoginServer_SetTrailer_Call {
	return &AuthTargetLoginServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *AuthTargetLoginServer_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *AuthTargetLoginServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *AuthTargetLoginServer_SetTrailer_Call) Return() *AuthTargetLoginServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthTargetLoginServer_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *AuthTargetLoginServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}

// NewAuthTargetLoginServer creates a new instance of AuthTargetLoginServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthTargetLoginServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthTargetLoginServer {
	mock := &AuthTargetLoginServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
