// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	authproto "github.com/Arm-Debug/apap-cli/clients/go/authproto"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// AuthClient is an autogenerated mock type for the AuthClient type
type AuthClient struct {
	mock.Mock
}

type AuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthClient) EXPECT() *AuthClient_Expecter {
	return &AuthClient_Expecter{mock: &_m.Mock}
}

// TargetLogin provides a mock function with given fields: ctx, opts
func (_m *AuthClient) TargetLogin(ctx context.Context, opts ...grpc.CallOption) (authproto.Auth_TargetLoginClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TargetLogin")
	}

	var r0 authproto.Auth_TargetLoginClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (authproto.Auth_TargetLoginClient, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) authproto.Auth_TargetLoginClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authproto.Auth_TargetLoginClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthClient_TargetLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TargetLogin'
type AuthClient_TargetLogin_Call struct {
	*mock.Call
}

// TargetLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *AuthClient_Expecter) TargetLogin(ctx interface{}, opts ...interface{}) *AuthClient_TargetLogin_Call {
	return &AuthClient_TargetLogin_Call{Call: _e.mock.On("TargetLogin",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *AuthClient_TargetLogin_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *AuthClient_TargetLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *AuthClient_TargetLogin_Call) Return(_a0 authproto.Auth_TargetLoginClient, _a1 error) *AuthClient_TargetLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthClient_TargetLogin_Call) RunAndReturn(run func(context.Context, ...grpc.CallOption) (authproto.Auth_TargetLoginClient, error)) *AuthClient_TargetLogin_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthClient creates a new instance of AuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthClient {
	mock := &AuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
