// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	authproto "github.com/Arm-Debug/apap-cli/clients/go/authproto"
	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"
)

// AuthTargetLoginClient is an autogenerated mock type for the Auth_TargetLoginClient type
type AuthTargetLoginClient struct {
	mock.Mock
}

type AuthTargetLoginClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthTargetLoginClient) EXPECT() *AuthTargetLoginClient_Expecter {
	return &AuthTargetLoginClient_Expecter{mock: &_m.Mock}
}

// CloseSend provides a mock function with no fields
func (_m *AuthTargetLoginClient) CloseSend() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthTargetLoginClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type AuthTargetLoginClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *AuthTargetLoginClient_Expecter) CloseSend() *AuthTargetLoginClient_CloseSend_Call {
	return &AuthTargetLoginClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *AuthTargetLoginClient_CloseSend_Call) Run(run func()) *AuthTargetLoginClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthTargetLoginClient_CloseSend_Call) Return(_a0 error) *AuthTargetLoginClient_CloseSend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthTargetLoginClient_CloseSend_Call) RunAndReturn(run func() error) *AuthTargetLoginClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with no fields
func (_m *AuthTargetLoginClient) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// AuthTargetLoginClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type AuthTargetLoginClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *AuthTargetLoginClient_Expecter) Context() *AuthTargetLoginClient_Context_Call {
	return &AuthTargetLoginClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *AuthTargetLoginClient_Context_Call) Run(run func()) *AuthTargetLoginClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthTargetLoginClient_Context_Call) Return(_a0 context.Context) *AuthTargetLoginClient_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthTargetLoginClient_Context_Call) RunAndReturn(run func() context.Context) *AuthTargetLoginClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function with no fields
func (_m *AuthTargetLoginClient) Header() (metadata.MD, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if rf, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthTargetLoginClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type AuthTargetLoginClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *AuthTargetLoginClient_Expecter) Header() *AuthTargetLoginClient_Header_Call {
	return &AuthTargetLoginClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *AuthTargetLoginClient_Header_Call) Run(run func()) *AuthTargetLoginClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthTargetLoginClient_Header_Call) Return(_a0 metadata.MD, _a1 error) *AuthTargetLoginClient_Header_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthTargetLoginClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *AuthTargetLoginClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function with no fields
func (_m *AuthTargetLoginClient) Recv() (*authproto.TargetLoginServerMessage, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *authproto.TargetLoginServerMessage
	var r1 error
	if rf, ok := ret.Get(0).(func() (*authproto.TargetLoginServerMessage, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *authproto.TargetLoginServerMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authproto.TargetLoginServerMessage)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthTargetLoginClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type AuthTargetLoginClient_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *AuthTargetLoginClient_Expecter) Recv() *AuthTargetLoginClient_Recv_Call {
	return &AuthTargetLoginClient_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *AuthTargetLoginClient_Recv_Call) Run(run func()) *AuthTargetLoginClient_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthTargetLoginClient_Recv_Call) Return(_a0 *authproto.TargetLoginServerMessage, _a1 error) *AuthTargetLoginClient_Recv_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthTargetLoginClient_Recv_Call) RunAndReturn(run func() (*authproto.TargetLoginServerMessage, error)) *AuthTargetLoginClient_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *AuthTargetLoginClient) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthTargetLoginClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type AuthTargetLoginClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *AuthTargetLoginClient_Expecter) RecvMsg(m interface{}) *AuthTargetLoginClient_RecvMsg_Call {
	return &AuthTargetLoginClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *AuthTargetLoginClient_RecvMsg_Call) Run(run func(m interface{})) *AuthTargetLoginClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *AuthTargetLoginClient_RecvMsg_Call) Return(_a0 error) *AuthTargetLoginClient_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthTargetLoginClient_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *AuthTargetLoginClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *AuthTargetLoginClient) Send(_a0 *authproto.TargetLoginClientMessage) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*authproto.TargetLoginClientMessage) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthTargetLoginClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type AuthTargetLoginClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *authproto.TargetLoginClientMessage
func (_e *AuthTargetLoginClient_Expecter) Send(_a0 interface{}) *AuthTargetLoginClient_Send_Call {
	return &AuthTargetLoginClient_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *AuthTargetLoginClient_Send_Call) Run(run func(_a0 *authproto.TargetLoginClientMessage)) *AuthTargetLoginClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*authproto.TargetLoginClientMessage))
	})
	return _c
}

func (_c *AuthTargetLoginClient_Send_Call) Return(_a0 error) *AuthTargetLoginClient_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthTargetLoginClient_Send_Call) RunAndReturn(run func(*authproto.TargetLoginClientMessage) error) *AuthTargetLoginClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *AuthTargetLoginClient) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthTargetLoginClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type AuthTargetLoginClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *AuthTargetLoginClient_Expecter) SendMsg(m interface{}) *AuthTargetLoginClient_SendMsg_Call {
	return &AuthTargetLoginClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *AuthTargetLoginClient_SendMsg_Call) Run(run func(m interface{})) *AuthTargetLoginClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *AuthTargetLoginClient_SendMsg_Call) Return(_a0 error) *AuthTargetLoginClient_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthTargetLoginClient_SendMsg_Call) RunAndReturn(run func(interface{}) error) *AuthTargetLoginClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function with no fields
func (_m *AuthTargetLoginClient) Trailer() metadata.MD {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	return r0
}

// AuthTargetLoginClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type AuthTargetLoginClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *AuthTargetLoginClient_Expecter) Trailer() *AuthTargetLoginClient_Trailer_Call {
	return &AuthTargetLoginClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *AuthTargetLoginClient_Trailer_Call) Run(run func()) *AuthTargetLoginClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthTargetLoginClient_Trailer_Call) Return(_a0 metadata.MD) *AuthTargetLoginClient_Trailer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthTargetLoginClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *AuthTargetLoginClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthTargetLoginClient creates a new instance of AuthTargetLoginClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthTargetLoginClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthTargetLoginClient {
	mock := &AuthTargetLoginClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
