// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	targetagentproto "github.com/Arm-Debug/apap-cli/clients/go/targetagentproto"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// TargetAgentClient is an autogenerated mock type for the TargetAgentClient type
type TargetAgentClient struct {
	mock.Mock
}

type TargetAgentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TargetAgentClient) EXPECT() *TargetAgentClient_Expecter {
	return &TargetAgentClient_Expecter{mock: &_m.Mock}
}

// Chown provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) Chown(ctx context.Context, in *targetagentproto.ChownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Chown")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ChownRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ChownRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.ChownRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_Chown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chown'
type TargetAgentClient_Chown_Call struct {
	*mock.Call
}

// Chown is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.ChownRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) Chown(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_Chown_Call {
	return &TargetAgentClient_Chown_Call{Call: _e.mock.On("Chown",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_Chown_Call) Run(run func(ctx context.Context, in *targetagentproto.ChownRequest, opts ...grpc.CallOption)) *TargetAgentClient_Chown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.ChownRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_Chown_Call) Return(_a0 *emptypb.Empty, _a1 error) *TargetAgentClient_Chown_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_Chown_Call) RunAndReturn(run func(context.Context, *targetagentproto.ChownRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *TargetAgentClient_Chown_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTempDir provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) CreateTempDir(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*targetagentproto.TempDir, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateTempDir")
	}

	var r0 *targetagentproto.TempDir
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*targetagentproto.TempDir, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *targetagentproto.TempDir); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*targetagentproto.TempDir)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_CreateTempDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTempDir'
type TargetAgentClient_CreateTempDir_Call struct {
	*mock.Call
}

// CreateTempDir is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) CreateTempDir(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_CreateTempDir_Call {
	return &TargetAgentClient_CreateTempDir_Call{Call: _e.mock.On("CreateTempDir",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_CreateTempDir_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *TargetAgentClient_CreateTempDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_CreateTempDir_Call) Return(_a0 *targetagentproto.TempDir, _a1 error) *TargetAgentClient_CreateTempDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_CreateTempDir_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*targetagentproto.TempDir, error)) *TargetAgentClient_CreateTempDir_Call {
	_c.Call.Return(run)
	return _c
}

// ElevatePrivileges provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) ElevatePrivileges(ctx context.Context, in *targetagentproto.ElevatePrivilegesRequest, opts ...grpc.CallOption) (*targetagentproto.ElevatePrivilegesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ElevatePrivileges")
	}

	var r0 *targetagentproto.ElevatePrivilegesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ElevatePrivilegesRequest, ...grpc.CallOption) (*targetagentproto.ElevatePrivilegesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ElevatePrivilegesRequest, ...grpc.CallOption) *targetagentproto.ElevatePrivilegesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*targetagentproto.ElevatePrivilegesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.ElevatePrivilegesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_ElevatePrivileges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ElevatePrivileges'
type TargetAgentClient_ElevatePrivileges_Call struct {
	*mock.Call
}

// ElevatePrivileges is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.ElevatePrivilegesRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) ElevatePrivileges(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_ElevatePrivileges_Call {
	return &TargetAgentClient_ElevatePrivileges_Call{Call: _e.mock.On("ElevatePrivileges",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_ElevatePrivileges_Call) Run(run func(ctx context.Context, in *targetagentproto.ElevatePrivilegesRequest, opts ...grpc.CallOption)) *TargetAgentClient_ElevatePrivileges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.ElevatePrivilegesRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_ElevatePrivileges_Call) Return(_a0 *targetagentproto.ElevatePrivilegesResponse, _a1 error) *TargetAgentClient_ElevatePrivileges_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_ElevatePrivileges_Call) RunAndReturn(run func(context.Context, *targetagentproto.ElevatePrivilegesRequest, ...grpc.CallOption) (*targetagentproto.ElevatePrivilegesResponse, error)) *TargetAgentClient_ElevatePrivileges_Call {
	_c.Call.Return(run)
	return _c
}

// ExecCommand provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) ExecCommand(ctx context.Context, in *targetagentproto.ExecCommandRequest, opts ...grpc.CallOption) (*targetagentproto.CommandResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecCommand")
	}

	var r0 *targetagentproto.CommandResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ExecCommandRequest, ...grpc.CallOption) (*targetagentproto.CommandResult, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ExecCommandRequest, ...grpc.CallOption) *targetagentproto.CommandResult); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*targetagentproto.CommandResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.ExecCommandRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_ExecCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecCommand'
type TargetAgentClient_ExecCommand_Call struct {
	*mock.Call
}

// ExecCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.ExecCommandRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) ExecCommand(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_ExecCommand_Call {
	return &TargetAgentClient_ExecCommand_Call{Call: _e.mock.On("ExecCommand",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_ExecCommand_Call) Run(run func(ctx context.Context, in *targetagentproto.ExecCommandRequest, opts ...grpc.CallOption)) *TargetAgentClient_ExecCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.ExecCommandRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_ExecCommand_Call) Return(_a0 *targetagentproto.CommandResult, _a1 error) *TargetAgentClient_ExecCommand_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_ExecCommand_Call) RunAndReturn(run func(context.Context, *targetagentproto.ExecCommandRequest, ...grpc.CallOption) (*targetagentproto.CommandResult, error)) *TargetAgentClient_ExecCommand_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivilegeInfo provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) GetPrivilegeInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*targetagentproto.GetPrivilegeInfoResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivilegeInfo")
	}

	var r0 *targetagentproto.GetPrivilegeInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*targetagentproto.GetPrivilegeInfoResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *targetagentproto.GetPrivilegeInfoResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*targetagentproto.GetPrivilegeInfoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_GetPrivilegeInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivilegeInfo'
type TargetAgentClient_GetPrivilegeInfo_Call struct {
	*mock.Call
}

// GetPrivilegeInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) GetPrivilegeInfo(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_GetPrivilegeInfo_Call {
	return &TargetAgentClient_GetPrivilegeInfo_Call{Call: _e.mock.On("GetPrivilegeInfo",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_GetPrivilegeInfo_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *TargetAgentClient_GetPrivilegeInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_GetPrivilegeInfo_Call) Return(_a0 *targetagentproto.GetPrivilegeInfoResponse, _a1 error) *TargetAgentClient_GetPrivilegeInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_GetPrivilegeInfo_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*targetagentproto.GetPrivilegeInfoResponse, error)) *TargetAgentClient_GetPrivilegeInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTargetInfo provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) GetTargetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*targetagentproto.TargetInfo, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTargetInfo")
	}

	var r0 *targetagentproto.TargetInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*targetagentproto.TargetInfo, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *targetagentproto.TargetInfo); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*targetagentproto.TargetInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_GetTargetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTargetInfo'
type TargetAgentClient_GetTargetInfo_Call struct {
	*mock.Call
}

// GetTargetInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) GetTargetInfo(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_GetTargetInfo_Call {
	return &TargetAgentClient_GetTargetInfo_Call{Call: _e.mock.On("GetTargetInfo",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_GetTargetInfo_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *TargetAgentClient_GetTargetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_GetTargetInfo_Call) Return(_a0 *targetagentproto.TargetInfo, _a1 error) *TargetAgentClient_GetTargetInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_GetTargetInfo_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*targetagentproto.TargetInfo, error)) *TargetAgentClient_GetTargetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*targetagentproto.GetVersionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 *targetagentproto.GetVersionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*targetagentproto.GetVersionResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *targetagentproto.GetVersionResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*targetagentproto.GetVersionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type TargetAgentClient_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) GetVersion(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_GetVersion_Call {
	return &TargetAgentClient_GetVersion_Call{Call: _e.mock.On("GetVersion",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_GetVersion_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *TargetAgentClient_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_GetVersion_Call) Return(_a0 *targetagentproto.GetVersionResponse, _a1 error) *TargetAgentClient_GetVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_GetVersion_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*targetagentproto.GetVersionResponse, error)) *TargetAgentClient_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// HoldLock provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) HoldLock(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (targetagentproto.TargetAgent_HoldLockClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HoldLock")
	}

	var r0 targetagentproto.TargetAgent_HoldLockClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (targetagentproto.TargetAgent_HoldLockClient, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) targetagentproto.TargetAgent_HoldLockClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(targetagentproto.TargetAgent_HoldLockClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_HoldLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HoldLock'
type TargetAgentClient_HoldLock_Call struct {
	*mock.Call
}

// HoldLock is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) HoldLock(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_HoldLock_Call {
	return &TargetAgentClient_HoldLock_Call{Call: _e.mock.On("HoldLock",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_HoldLock_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *TargetAgentClient_HoldLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_HoldLock_Call) Return(_a0 targetagentproto.TargetAgent_HoldLockClient, _a1 error) *TargetAgentClient_HoldLock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_HoldLock_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (targetagentproto.TargetAgent_HoldLockClient, error)) *TargetAgentClient_HoldLock_Call {
	_c.Call.Return(run)
	return _c
}

// InterruptProcess provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) InterruptProcess(ctx context.Context, in *targetagentproto.InterruptProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for InterruptProcess")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.InterruptProcessRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.InterruptProcessRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.InterruptProcessRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_InterruptProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InterruptProcess'
type TargetAgentClient_InterruptProcess_Call struct {
	*mock.Call
}

// InterruptProcess is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.InterruptProcessRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) InterruptProcess(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_InterruptProcess_Call {
	return &TargetAgentClient_InterruptProcess_Call{Call: _e.mock.On("InterruptProcess",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_InterruptProcess_Call) Run(run func(ctx context.Context, in *targetagentproto.InterruptProcessRequest, opts ...grpc.CallOption)) *TargetAgentClient_InterruptProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.InterruptProcessRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_InterruptProcess_Call) Return(_a0 *emptypb.Empty, _a1 error) *TargetAgentClient_InterruptProcess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_InterruptProcess_Call) RunAndReturn(run func(context.Context, *targetagentproto.InterruptProcessRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *TargetAgentClient_InterruptProcess_Call {
	_c.Call.Return(run)
	return _c
}

// KillProcess provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) KillProcess(ctx context.Context, in *targetagentproto.KillProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for KillProcess")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.KillProcessRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.KillProcessRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.KillProcessRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_KillProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillProcess'
type TargetAgentClient_KillProcess_Call struct {
	*mock.Call
}

// KillProcess is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.KillProcessRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) KillProcess(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_KillProcess_Call {
	return &TargetAgentClient_KillProcess_Call{Call: _e.mock.On("KillProcess",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_KillProcess_Call) Run(run func(ctx context.Context, in *targetagentproto.KillProcessRequest, opts ...grpc.CallOption)) *TargetAgentClient_KillProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.KillProcessRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_KillProcess_Call) Return(_a0 *emptypb.Empty, _a1 error) *TargetAgentClient_KillProcess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_KillProcess_Call) RunAndReturn(run func(context.Context, *targetagentproto.KillProcessRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *TargetAgentClient_KillProcess_Call {
	_c.Call.Return(run)
	return _c
}

// ListAndroidPackages provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) ListAndroidPackages(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*targetagentproto.AndroidPackageList, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListAndroidPackages")
	}

	var r0 *targetagentproto.AndroidPackageList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*targetagentproto.AndroidPackageList, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *targetagentproto.AndroidPackageList); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*targetagentproto.AndroidPackageList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_ListAndroidPackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAndroidPackages'
type TargetAgentClient_ListAndroidPackages_Call struct {
	*mock.Call
}

// ListAndroidPackages is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) ListAndroidPackages(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_ListAndroidPackages_Call {
	return &TargetAgentClient_ListAndroidPackages_Call{Call: _e.mock.On("ListAndroidPackages",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_ListAndroidPackages_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *TargetAgentClient_ListAndroidPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_ListAndroidPackages_Call) Return(_a0 *targetagentproto.AndroidPackageList, _a1 error) *TargetAgentClient_ListAndroidPackages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_ListAndroidPackages_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*targetagentproto.AndroidPackageList, error)) *TargetAgentClient_ListAndroidPackages_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiles provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) ListFiles(ctx context.Context, in *targetagentproto.ListFilesRequest, opts ...grpc.CallOption) (*targetagentproto.ListFilesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 *targetagentproto.ListFilesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ListFilesRequest, ...grpc.CallOption) (*targetagentproto.ListFilesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ListFilesRequest, ...grpc.CallOption) *targetagentproto.ListFilesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*targetagentproto.ListFilesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.ListFilesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type TargetAgentClient_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.ListFilesRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) ListFiles(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_ListFiles_Call {
	return &TargetAgentClient_ListFiles_Call{Call: _e.mock.On("ListFiles",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_ListFiles_Call) Run(run func(ctx context.Context, in *targetagentproto.ListFilesRequest, opts ...grpc.CallOption)) *TargetAgentClient_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.ListFilesRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_ListFiles_Call) Return(_a0 *targetagentproto.ListFilesResponse, _a1 error) *TargetAgentClient_ListFiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_ListFiles_Call) RunAndReturn(run func(context.Context, *targetagentproto.ListFilesRequest, ...grpc.CallOption) (*targetagentproto.ListFilesResponse, error)) *TargetAgentClient_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}

// ListProcesses provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) ListProcesses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*targetagentproto.ProcessList, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListProcesses")
	}

	var r0 *targetagentproto.ProcessList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*targetagentproto.ProcessList, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *targetagentproto.ProcessList); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*targetagentproto.ProcessList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_ListProcesses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProcesses'
type TargetAgentClient_ListProcesses_Call struct {
	*mock.Call
}

// ListProcesses is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) ListProcesses(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_ListProcesses_Call {
	return &TargetAgentClient_ListProcesses_Call{Call: _e.mock.On("ListProcesses",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_ListProcesses_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *TargetAgentClient_ListProcesses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_ListProcesses_Call) Return(_a0 *targetagentproto.ProcessList, _a1 error) *TargetAgentClient_ListProcesses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_ListProcesses_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*targetagentproto.ProcessList, error)) *TargetAgentClient_ListProcesses_Call {
	_c.Call.Return(run)
	return _c
}

// MakeWritable provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) MakeWritable(ctx context.Context, in *targetagentproto.MakeWritableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for MakeWritable")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.MakeWritableRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.MakeWritableRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.MakeWritableRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_MakeWritable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeWritable'
type TargetAgentClient_MakeWritable_Call struct {
	*mock.Call
}

// MakeWritable is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.MakeWritableRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) MakeWritable(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_MakeWritable_Call {
	return &TargetAgentClient_MakeWritable_Call{Call: _e.mock.On("MakeWritable",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_MakeWritable_Call) Run(run func(ctx context.Context, in *targetagentproto.MakeWritableRequest, opts ...grpc.CallOption)) *TargetAgentClient_MakeWritable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.MakeWritableRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_MakeWritable_Call) Return(_a0 *emptypb.Empty, _a1 error) *TargetAgentClient_MakeWritable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_MakeWritable_Call) RunAndReturn(run func(context.Context, *targetagentproto.MakeWritableRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *TargetAgentClient_MakeWritable_Call {
	_c.Call.Return(run)
	return _c
}

// Mkdir provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) Mkdir(ctx context.Context, in *targetagentproto.MkdirRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Mkdir")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.MkdirRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.MkdirRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.MkdirRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_Mkdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mkdir'
type TargetAgentClient_Mkdir_Call struct {
	*mock.Call
}

// Mkdir is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.MkdirRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) Mkdir(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_Mkdir_Call {
	return &TargetAgentClient_Mkdir_Call{Call: _e.mock.On("Mkdir",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_Mkdir_Call) Run(run func(ctx context.Context, in *targetagentproto.MkdirRequest, opts ...grpc.CallOption)) *TargetAgentClient_Mkdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.MkdirRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_Mkdir_Call) Return(_a0 *emptypb.Empty, _a1 error) *TargetAgentClient_Mkdir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_Mkdir_Call) RunAndReturn(run func(context.Context, *targetagentproto.MkdirRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *TargetAgentClient_Mkdir_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseProcessHandles provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) ReleaseProcessHandles(ctx context.Context, in *targetagentproto.ReleaseProcessHandlesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseProcessHandles")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ReleaseProcessHandlesRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ReleaseProcessHandlesRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.ReleaseProcessHandlesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_ReleaseProcessHandles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseProcessHandles'
type TargetAgentClient_ReleaseProcessHandles_Call struct {
	*mock.Call
}

// ReleaseProcessHandles is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.ReleaseProcessHandlesRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) ReleaseProcessHandles(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_ReleaseProcessHandles_Call {
	return &TargetAgentClient_ReleaseProcessHandles_Call{Call: _e.mock.On("ReleaseProcessHandles",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_ReleaseProcessHandles_Call) Run(run func(ctx context.Context, in *targetagentproto.ReleaseProcessHandlesRequest, opts ...grpc.CallOption)) *TargetAgentClient_ReleaseProcessHandles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.ReleaseProcessHandlesRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_ReleaseProcessHandles_Call) Return(_a0 *emptypb.Empty, _a1 error) *TargetAgentClient_ReleaseProcessHandles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_ReleaseProcessHandles_Call) RunAndReturn(run func(context.Context, *targetagentproto.ReleaseProcessHandlesRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *TargetAgentClient_ReleaseProcessHandles_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveFile provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) RetrieveFile(ctx context.Context, in *targetagentproto.FileRequest, opts ...grpc.CallOption) (targetagentproto.TargetAgent_RetrieveFileClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveFile")
	}

	var r0 targetagentproto.TargetAgent_RetrieveFileClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.FileRequest, ...grpc.CallOption) (targetagentproto.TargetAgent_RetrieveFileClient, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.FileRequest, ...grpc.CallOption) targetagentproto.TargetAgent_RetrieveFileClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(targetagentproto.TargetAgent_RetrieveFileClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.FileRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_RetrieveFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveFile'
type TargetAgentClient_RetrieveFile_Call struct {
	*mock.Call
}

// RetrieveFile is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.FileRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) RetrieveFile(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_RetrieveFile_Call {
	return &TargetAgentClient_RetrieveFile_Call{Call: _e.mock.On("RetrieveFile",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_RetrieveFile_Call) Run(run func(ctx context.Context, in *targetagentproto.FileRequest, opts ...grpc.CallOption)) *TargetAgentClient_RetrieveFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.FileRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_RetrieveFile_Call) Return(_a0 targetagentproto.TargetAgent_RetrieveFileClient, _a1 error) *TargetAgentClient_RetrieveFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_RetrieveFile_Call) RunAndReturn(run func(context.Context, *targetagentproto.FileRequest, ...grpc.CallOption) (targetagentproto.TargetAgent_RetrieveFileClient, error)) *TargetAgentClient_RetrieveFile_Call {
	_c.Call.Return(run)
	return _c
}

// Rm provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) Rm(ctx context.Context, in *targetagentproto.RmRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Rm")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.RmRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.RmRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.RmRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_Rm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rm'
type TargetAgentClient_Rm_Call struct {
	*mock.Call
}

// Rm is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.RmRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) Rm(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_Rm_Call {
	return &TargetAgentClient_Rm_Call{Call: _e.mock.On("Rm",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_Rm_Call) Run(run func(ctx context.Context, in *targetagentproto.RmRequest, opts ...grpc.CallOption)) *TargetAgentClient_Rm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.RmRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_Rm_Call) Return(_a0 *emptypb.Empty, _a1 error) *TargetAgentClient_Rm_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_Rm_Call) RunAndReturn(run func(context.Context, *targetagentproto.RmRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *TargetAgentClient_Rm_Call {
	_c.Call.Return(run)
	return _c
}

// SetAffinity provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) SetAffinity(ctx context.Context, in *targetagentproto.AffinityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SetAffinity")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.AffinityRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.AffinityRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.AffinityRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_SetAffinity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAffinity'
type TargetAgentClient_SetAffinity_Call struct {
	*mock.Call
}

// SetAffinity is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.AffinityRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) SetAffinity(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_SetAffinity_Call {
	return &TargetAgentClient_SetAffinity_Call{Call: _e.mock.On("SetAffinity",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_SetAffinity_Call) Run(run func(ctx context.Context, in *targetagentproto.AffinityRequest, opts ...grpc.CallOption)) *TargetAgentClient_SetAffinity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.AffinityRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_SetAffinity_Call) Return(_a0 *emptypb.Empty, _a1 error) *TargetAgentClient_SetAffinity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_SetAffinity_Call) RunAndReturn(run func(context.Context, *targetagentproto.AffinityRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *TargetAgentClient_SetAffinity_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) Shutdown(ctx context.Context, in *targetagentproto.ShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ShutdownRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ShutdownRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.ShutdownRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type TargetAgentClient_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.ShutdownRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) Shutdown(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_Shutdown_Call {
	return &TargetAgentClient_Shutdown_Call{Call: _e.mock.On("Shutdown",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_Shutdown_Call) Run(run func(ctx context.Context, in *targetagentproto.ShutdownRequest, opts ...grpc.CallOption)) *TargetAgentClient_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.ShutdownRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_Shutdown_Call) Return(_a0 *emptypb.Empty, _a1 error) *TargetAgentClient_Shutdown_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_Shutdown_Call) RunAndReturn(run func(context.Context, *targetagentproto.ShutdownRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *TargetAgentClient_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// StartProcess provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) StartProcess(ctx context.Context, in *targetagentproto.StartProcessRequest, opts ...grpc.CallOption) (*targetagentproto.StartProcessResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StartProcess")
	}

	var r0 *targetagentproto.StartProcessResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.StartProcessRequest, ...grpc.CallOption) (*targetagentproto.StartProcessResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.StartProcessRequest, ...grpc.CallOption) *targetagentproto.StartProcessResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*targetagentproto.StartProcessResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.StartProcessRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_StartProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartProcess'
type TargetAgentClient_StartProcess_Call struct {
	*mock.Call
}

// StartProcess is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.StartProcessRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) StartProcess(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_StartProcess_Call {
	return &TargetAgentClient_StartProcess_Call{Call: _e.mock.On("StartProcess",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_StartProcess_Call) Run(run func(ctx context.Context, in *targetagentproto.StartProcessRequest, opts ...grpc.CallOption)) *TargetAgentClient_StartProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.StartProcessRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_StartProcess_Call) Return(_a0 *targetagentproto.StartProcessResponse, _a1 error) *TargetAgentClient_StartProcess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_StartProcess_Call) RunAndReturn(run func(context.Context, *targetagentproto.StartProcessRequest, ...grpc.CallOption) (*targetagentproto.StartProcessResponse, error)) *TargetAgentClient_StartProcess_Call {
	_c.Call.Return(run)
	return _c
}

// StoreFile provides a mock function with given fields: ctx, opts
func (_m *TargetAgentClient) StoreFile(ctx context.Context, opts ...grpc.CallOption) (targetagentproto.TargetAgent_StoreFileClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StoreFile")
	}

	var r0 targetagentproto.TargetAgent_StoreFileClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (targetagentproto.TargetAgent_StoreFileClient, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) targetagentproto.TargetAgent_StoreFileClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(targetagentproto.TargetAgent_StoreFileClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_StoreFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreFile'
type TargetAgentClient_StoreFile_Call struct {
	*mock.Call
}

// StoreFile is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) StoreFile(ctx interface{}, opts ...interface{}) *TargetAgentClient_StoreFile_Call {
	return &TargetAgentClient_StoreFile_Call{Call: _e.mock.On("StoreFile",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *TargetAgentClient_StoreFile_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *TargetAgentClient_StoreFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_StoreFile_Call) Return(_a0 targetagentproto.TargetAgent_StoreFileClient, _a1 error) *TargetAgentClient_StoreFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_StoreFile_Call) RunAndReturn(run func(context.Context, ...grpc.CallOption) (targetagentproto.TargetAgent_StoreFileClient, error)) *TargetAgentClient_StoreFile_Call {
	_c.Call.Return(run)
	return _c
}

// StreamLogs provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) StreamLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (targetagentproto.TargetAgent_StreamLogsClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StreamLogs")
	}

	var r0 targetagentproto.TargetAgent_StreamLogsClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (targetagentproto.TargetAgent_StreamLogsClient, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) targetagentproto.TargetAgent_StreamLogsClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(targetagentproto.TargetAgent_StreamLogsClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_StreamLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamLogs'
type TargetAgentClient_StreamLogs_Call struct {
	*mock.Call
}

// StreamLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) StreamLogs(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_StreamLogs_Call {
	return &TargetAgentClient_StreamLogs_Call{Call: _e.mock.On("StreamLogs",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_StreamLogs_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *TargetAgentClient_StreamLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_StreamLogs_Call) Return(_a0 targetagentproto.TargetAgent_StreamLogsClient, _a1 error) *TargetAgentClient_StreamLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_StreamLogs_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (targetagentproto.TargetAgent_StreamLogsClient, error)) *TargetAgentClient_StreamLogs_Call {
	_c.Call.Return(run)
	return _c
}

// StreamStderr provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) StreamStderr(ctx context.Context, in *targetagentproto.ProcessStreamRequest, opts ...grpc.CallOption) (targetagentproto.TargetAgent_StreamStderrClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StreamStderr")
	}

	var r0 targetagentproto.TargetAgent_StreamStderrClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ProcessStreamRequest, ...grpc.CallOption) (targetagentproto.TargetAgent_StreamStderrClient, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ProcessStreamRequest, ...grpc.CallOption) targetagentproto.TargetAgent_StreamStderrClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(targetagentproto.TargetAgent_StreamStderrClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.ProcessStreamRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_StreamStderr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamStderr'
type TargetAgentClient_StreamStderr_Call struct {
	*mock.Call
}

// StreamStderr is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.ProcessStreamRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) StreamStderr(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_StreamStderr_Call {
	return &TargetAgentClient_StreamStderr_Call{Call: _e.mock.On("StreamStderr",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_StreamStderr_Call) Run(run func(ctx context.Context, in *targetagentproto.ProcessStreamRequest, opts ...grpc.CallOption)) *TargetAgentClient_StreamStderr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.ProcessStreamRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_StreamStderr_Call) Return(_a0 targetagentproto.TargetAgent_StreamStderrClient, _a1 error) *TargetAgentClient_StreamStderr_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_StreamStderr_Call) RunAndReturn(run func(context.Context, *targetagentproto.ProcessStreamRequest, ...grpc.CallOption) (targetagentproto.TargetAgent_StreamStderrClient, error)) *TargetAgentClient_StreamStderr_Call {
	_c.Call.Return(run)
	return _c
}

// StreamStdout provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) StreamStdout(ctx context.Context, in *targetagentproto.ProcessStreamRequest, opts ...grpc.CallOption) (targetagentproto.TargetAgent_StreamStdoutClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StreamStdout")
	}

	var r0 targetagentproto.TargetAgent_StreamStdoutClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ProcessStreamRequest, ...grpc.CallOption) (targetagentproto.TargetAgent_StreamStdoutClient, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.ProcessStreamRequest, ...grpc.CallOption) targetagentproto.TargetAgent_StreamStdoutClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(targetagentproto.TargetAgent_StreamStdoutClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.ProcessStreamRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_StreamStdout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamStdout'
type TargetAgentClient_StreamStdout_Call struct {
	*mock.Call
}

// StreamStdout is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.ProcessStreamRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) StreamStdout(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_StreamStdout_Call {
	return &TargetAgentClient_StreamStdout_Call{Call: _e.mock.On("StreamStdout",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_StreamStdout_Call) Run(run func(ctx context.Context, in *targetagentproto.ProcessStreamRequest, opts ...grpc.CallOption)) *TargetAgentClient_StreamStdout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.ProcessStreamRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_StreamStdout_Call) Return(_a0 targetagentproto.TargetAgent_StreamStdoutClient, _a1 error) *TargetAgentClient_StreamStdout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_StreamStdout_Call) RunAndReturn(run func(context.Context, *targetagentproto.ProcessStreamRequest, ...grpc.CallOption) (targetagentproto.TargetAgent_StreamStdoutClient, error)) *TargetAgentClient_StreamStdout_Call {
	_c.Call.Return(run)
	return _c
}

// WaitProcess provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) WaitProcess(ctx context.Context, in *targetagentproto.WaitProcessRequest, opts ...grpc.CallOption) (*targetagentproto.WaitProcessResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WaitProcess")
	}

	var r0 *targetagentproto.WaitProcessResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.WaitProcessRequest, ...grpc.CallOption) (*targetagentproto.WaitProcessResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.WaitProcessRequest, ...grpc.CallOption) *targetagentproto.WaitProcessResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*targetagentproto.WaitProcessResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.WaitProcessRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_WaitProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitProcess'
type TargetAgentClient_WaitProcess_Call struct {
	*mock.Call
}

// WaitProcess is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.WaitProcessRequest
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) WaitProcess(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_WaitProcess_Call {
	return &TargetAgentClient_WaitProcess_Call{Call: _e.mock.On("WaitProcess",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_WaitProcess_Call) Run(run func(ctx context.Context, in *targetagentproto.WaitProcessRequest, opts ...grpc.CallOption)) *TargetAgentClient_WaitProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.WaitProcessRequest), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_WaitProcess_Call) Return(_a0 *targetagentproto.WaitProcessResponse, _a1 error) *TargetAgentClient_WaitProcess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_WaitProcess_Call) RunAndReturn(run func(context.Context, *targetagentproto.WaitProcessRequest, ...grpc.CallOption) (*targetagentproto.WaitProcessResponse, error)) *TargetAgentClient_WaitProcess_Call {
	_c.Call.Return(run)
	return _c
}

// WriteToStdin provides a mock function with given fields: ctx, in, opts
func (_m *TargetAgentClient) WriteToStdin(ctx context.Context, in *targetagentproto.StdinChunk, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WriteToStdin")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.StdinChunk, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *targetagentproto.StdinChunk, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *targetagentproto.StdinChunk, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TargetAgentClient_WriteToStdin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteToStdin'
type TargetAgentClient_WriteToStdin_Call struct {
	*mock.Call
}

// WriteToStdin is a helper method to define mock.On call
//   - ctx context.Context
//   - in *targetagentproto.StdinChunk
//   - opts ...grpc.CallOption
func (_e *TargetAgentClient_Expecter) WriteToStdin(ctx interface{}, in interface{}, opts ...interface{}) *TargetAgentClient_WriteToStdin_Call {
	return &TargetAgentClient_WriteToStdin_Call{Call: _e.mock.On("WriteToStdin",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *TargetAgentClient_WriteToStdin_Call) Run(run func(ctx context.Context, in *targetagentproto.StdinChunk, opts ...grpc.CallOption)) *TargetAgentClient_WriteToStdin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*targetagentproto.StdinChunk), variadicArgs...)
	})
	return _c
}

func (_c *TargetAgentClient_WriteToStdin_Call) Return(_a0 *emptypb.Empty, _a1 error) *TargetAgentClient_WriteToStdin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TargetAgentClient_WriteToStdin_Call) RunAndReturn(run func(context.Context, *targetagentproto.StdinChunk, ...grpc.CallOption) (*emptypb.Empty, error)) *TargetAgentClient_WriteToStdin_Call {
	_c.Call.Return(run)
	return _c
}

// NewTargetAgentClient creates a new instance of TargetAgentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTargetAgentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TargetAgentClient {
	mock := &TargetAgentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
