// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	tetherproto "github.com/Arm-Debug/apap-cli/clients/go/tetherproto"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// TetherClient is an autogenerated mock type for the TetherClient type
type TetherClient struct {
	mock.Mock
}

type TetherClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TetherClient) EXPECT() *TetherClient_Expecter {
	return &TetherClient_Expecter{mock: &_m.Mock}
}

// Hold provides a mock function with given fields: ctx, opts
func (_m *TetherClient) Hold(ctx context.Context, opts ...grpc.CallOption) (tetherproto.Tether_HoldClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Hold")
	}

	var r0 tetherproto.Tether_HoldClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (tetherproto.Tether_HoldClient, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) tetherproto.Tether_HoldClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tetherproto.Tether_HoldClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TetherClient_Hold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hold'
type TetherClient_Hold_Call struct {
	*mock.Call
}

// Hold is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *TetherClient_Expecter) Hold(ctx interface{}, opts ...interface{}) *TetherClient_Hold_Call {
	return &TetherClient_Hold_Call{Call: _e.mock.On("Hold",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *TetherClient_Hold_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *TetherClient_Hold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *TetherClient_Hold_Call) Return(_a0 tetherproto.Tether_HoldClient, _a1 error) *TetherClient_Hold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TetherClient_Hold_Call) RunAndReturn(run func(context.Context, ...grpc.CallOption) (tetherproto.Tether_HoldClient, error)) *TetherClient_Hold_Call {
	_c.Call.Return(run)
	return _c
}

// NewTetherClient creates a new instance of TetherClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTetherClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TetherClient {
	mock := &TetherClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
