// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	tetherproto "github.com/Arm-Debug/apap-cli/clients/go/tetherproto"
	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"
)

// TetherHoldServer is an autogenerated mock type for the Tether_HoldServer type
type TetherHoldServer struct {
	mock.Mock
}

type TetherHoldServer_Expecter struct {
	mock *mock.Mock
}

func (_m *TetherHoldServer) EXPECT() *TetherHoldServer_Expecter {
	return &TetherHoldServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with no fields
func (_m *TetherHoldServer) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// TetherHoldServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type TetherHoldServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *TetherHoldServer_Expecter) Context() *TetherHoldServer_Context_Call {
	return &TetherHoldServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *TetherHoldServer_Context_Call) Run(run func()) *TetherHoldServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldServer_Context_Call) Return(_a0 context.Context) *TetherHoldServer_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TetherHoldServer_Context_Call) RunAndReturn(run func() context.Context) *TetherHoldServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function with no fields
func (_m *TetherHoldServer) Recv() (*tetherproto.PulseRequest, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *tetherproto.PulseRequest
	var r1 error
	if rf, ok := ret.Get(0).(func() (*tetherproto.PulseRequest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *tetherproto.PulseRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tetherproto.PulseRequest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TetherHoldServer_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type TetherHoldServer_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *TetherHoldServer_Expecter) Recv() *TetherHoldServer_Recv_Call {
	return &TetherHoldServer_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *TetherHoldServer_Recv_Call) Run(run func()) *TetherHoldServer_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldServer_Recv_Call) Return(_a0 *tetherproto.PulseRequest, _a1 error) *TetherHoldServer_Recv_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TetherHoldServer_Recv_Call) RunAndReturn(run func() (*tetherproto.PulseRequest, error)) *TetherHoldServer_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *TetherHoldServer) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TetherHoldServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type TetherHoldServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *TetherHoldServer_Expecter) RecvMsg(m interface{}) *TetherHoldServer_RecvMsg_Call {
	return &TetherHoldServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *TetherHoldServer_RecvMsg_Call) Run(run func(m interface{})) *TetherHoldServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *TetherHoldServer_RecvMsg_Call) Return(_a0 error) *TetherHoldServer_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TetherHoldServer_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *TetherHoldServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *TetherHoldServer) Send(_a0 *tetherproto.PulseAck) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*tetherproto.PulseAck) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TetherHoldServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type TetherHoldServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *tetherproto.PulseAck
func (_e *TetherHoldServer_Expecter) Send(_a0 interface{}) *TetherHoldServer_Send_Call {
	return &TetherHoldServer_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *TetherHoldServer_Send_Call) Run(run func(_a0 *tetherproto.PulseAck)) *TetherHoldServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*tetherproto.PulseAck))
	})
	return _c
}

func (_c *TetherHoldServer_Send_Call) Return(_a0 error) *TetherHoldServer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TetherHoldServer_Send_Call) RunAndReturn(run func(*tetherproto.PulseAck) error) *TetherHoldServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *TetherHoldServer) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TetherHoldServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type TetherHoldServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *TetherHoldServer_Expecter) SendHeader(_a0 interface{}) *TetherHoldServer_SendHeader_Call {
	return &TetherHoldServer_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *TetherHoldServer_SendHeader_Call) Run(run func(_a0 metadata.MD)) *TetherHoldServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *TetherHoldServer_SendHeader_Call) Return(_a0 error) *TetherHoldServer_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TetherHoldServer_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *TetherHoldServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *TetherHoldServer) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TetherHoldServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type TetherHoldServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *TetherHoldServer_Expecter) SendMsg(m interface{}) *TetherHoldServer_SendMsg_Call {
	return &TetherHoldServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *TetherHoldServer_SendMsg_Call) Run(run func(m interface{})) *TetherHoldServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *TetherHoldServer_SendMsg_Call) Return(_a0 error) *TetherHoldServer_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TetherHoldServer_SendMsg_Call) RunAndReturn(run func(interface{}) error) *TetherHoldServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *TetherHoldServer) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TetherHoldServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type TetherHoldServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *TetherHoldServer_Expecter) SetHeader(_a0 interface{}) *TetherHoldServer_SetHeader_Call {
	return &TetherHoldServer_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *TetherHoldServer_SetHeader_Call) Run(run func(_a0 metadata.MD)) *TetherHoldServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *TetherHoldServer_SetHeader_Call) Return(_a0 error) *TetherHoldServer_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TetherHoldServer_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *TetherHoldServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *TetherHoldServer) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// TetherHoldServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type TetherHoldServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *TetherHoldServer_Expecter) SetTrailer(_a0 interface{}) *TetherHoldServer_SetTrailer_Call {
	return &TetherHoldServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *TetherHoldServer_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *TetherHoldServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *TetherHoldServer_SetTrailer_Call) Return() *TetherHoldServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *TetherHoldServer_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *TetherHoldServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}

// NewTetherHoldServer creates a new instance of TetherHoldServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTetherHoldServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TetherHoldServer {
	mock := &TetherHoldServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
