// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	tetherproto "github.com/Arm-Debug/apap-cli/clients/go/tetherproto"
	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"
)

// TetherHoldClient is an autogenerated mock type for the Tether_HoldClient type
type TetherHoldClient struct {
	mock.Mock
}

type TetherHoldClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TetherHoldClient) EXPECT() *TetherHoldClient_Expecter {
	return &TetherHoldClient_Expecter{mock: &_m.Mock}
}

// CloseSend provides a mock function with no fields
func (_m *TetherHoldClient) CloseSend() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TetherHoldClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type TetherHoldClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *TetherHoldClient_Expecter) CloseSend() *TetherHoldClient_CloseSend_Call {
	return &TetherHoldClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *TetherHoldClient_CloseSend_Call) Run(run func()) *TetherHoldClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldClient_CloseSend_Call) Return(_a0 error) *TetherHoldClient_CloseSend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TetherHoldClient_CloseSend_Call) RunAndReturn(run func() error) *TetherHoldClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with no fields
func (_m *TetherHoldClient) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// TetherHoldClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type TetherHoldClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *TetherHoldClient_Expecter) Context() *TetherHoldClient_Context_Call {
	return &TetherHoldClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *TetherHoldClient_Context_Call) Run(run func()) *TetherHoldClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldClient_Context_Call) Return(_a0 context.Context) *TetherHoldClient_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TetherHoldClient_Context_Call) RunAndReturn(run func() context.Context) *TetherHoldClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function with no fields
func (_m *TetherHoldClient) Header() (metadata.MD, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if rf, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TetherHoldClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type TetherHoldClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *TetherHoldClient_Expecter) Header() *TetherHoldClient_Header_Call {
	return &TetherHoldClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *TetherHoldClient_Header_Call) Run(run func()) *TetherHoldClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldClient_Header_Call) Return(_a0 metadata.MD, _a1 error) *TetherHoldClient_Header_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TetherHoldClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *TetherHoldClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function with no fields
func (_m *TetherHoldClient) Recv() (*tetherproto.PulseAck, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *tetherproto.PulseAck
	var r1 error
	if rf, ok := ret.Get(0).(func() (*tetherproto.PulseAck, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *tetherproto.PulseAck); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tetherproto.PulseAck)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TetherHoldClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type TetherHoldClient_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *TetherHoldClient_Expecter) Recv() *TetherHoldClient_Recv_Call {
	return &TetherHoldClient_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *TetherHoldClient_Recv_Call) Run(run func()) *TetherHoldClient_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldClient_Recv_Call) Return(_a0 *tetherproto.PulseAck, _a1 error) *TetherHoldClient_Recv_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TetherHoldClient_Recv_Call) RunAndReturn(run func() (*tetherproto.PulseAck, error)) *TetherHoldClient_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *TetherHoldClient) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TetherHoldClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type TetherHoldClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *TetherHoldClient_Expecter) RecvMsg(m interface{}) *TetherHoldClient_RecvMsg_Call {
	return &TetherHoldClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *TetherHoldClient_RecvMsg_Call) Run(run func(m interface{})) *TetherHoldClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *TetherHoldClient_RecvMsg_Call) Return(_a0 error) *TetherHoldClient_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TetherHoldClient_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *TetherHoldClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *TetherHoldClient) Send(_a0 *tetherproto.PulseRequest) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*tetherproto.PulseRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TetherHoldClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type TetherHoldClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *tetherproto.PulseRequest
func (_e *TetherHoldClient_Expecter) Send(_a0 interface{}) *TetherHoldClient_Send_Call {
	return &TetherHoldClient_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *TetherHoldClient_Send_Call) Run(run func(_a0 *tetherproto.PulseRequest)) *TetherHoldClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*tetherproto.PulseRequest))
	})
	return _c
}

func (_c *TetherHoldClient_Send_Call) Return(_a0 error) *TetherHoldClient_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TetherHoldClient_Send_Call) RunAndReturn(run func(*tetherproto.PulseRequest) error) *TetherHoldClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *TetherHoldClient) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TetherHoldClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type TetherHoldClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *TetherHoldClient_Expecter) SendMsg(m interface{}) *TetherHoldClient_SendMsg_Call {
	return &TetherHoldClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *TetherHoldClient_SendMsg_Call) Run(run func(m interface{})) *TetherHoldClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *TetherHoldClient_SendMsg_Call) Return(_a0 error) *TetherHoldClient_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TetherHoldClient_SendMsg_Call) RunAndReturn(run func(interface{}) error) *TetherHoldClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function with no fields
func (_m *TetherHoldClient) Trailer() metadata.MD {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	return r0
}

// TetherHoldClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type TetherHoldClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *TetherHoldClient_Expecter) Trailer() *TetherHoldClient_Trailer_Call {
	return &TetherHoldClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *TetherHoldClient_Trailer_Call) Run(run func()) *TetherHoldClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldClient_Trailer_Call) Return(_a0 metadata.MD) *TetherHoldClient_Trailer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TetherHoldClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *TetherHoldClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewTetherHoldClient creates a new instance of TetherHoldClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTetherHoldClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TetherHoldClient {
	mock := &TetherHoldClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
