// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.23.4
// source: authproto/auth.proto

package authproto

import (
	apapproto "github.com/Arm-Debug/apap-cli/clients/go/apapproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TargetLoginPromptType specifies the type of credential requested.
type TargetLoginPromptType int32

const (
	TargetLoginPromptType_TARGET_LOGIN_PROMPT_TYPE_UNSPECIFIED   TargetLoginPromptType = 0
	TargetLoginPromptType_TARGET_LOGIN_PROMPT_TYPE_PASSWORD      TargetLoginPromptType = 1
	TargetLoginPromptType_TARGET_LOGIN_PROMPT_TYPE_KEYPASSPHRASE TargetLoginPromptType = 2
)

// Enum value maps for TargetLoginPromptType.
var (
	TargetLoginPromptType_name = map[int32]string{
		0: "TARGET_LOGIN_PROMPT_TYPE_UNSPECIFIED",
		1: "TARGET_LOGIN_PROMPT_TYPE_PASSWORD",
		2: "TARGET_LOGIN_PROMPT_TYPE_KEYPASSPHRASE",
	}
	TargetLoginPromptType_value = map[string]int32{
		"TARGET_LOGIN_PROMPT_TYPE_UNSPECIFIED":   0,
		"TARGET_LOGIN_PROMPT_TYPE_PASSWORD":      1,
		"TARGET_LOGIN_PROMPT_TYPE_KEYPASSPHRASE": 2,
	}
)

func (x TargetLoginPromptType) Enum() *TargetLoginPromptType {
	p := new(TargetLoginPromptType)
	*p = x
	return p
}

func (x TargetLoginPromptType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetLoginPromptType) Descriptor() protoreflect.EnumDescriptor {
	return file_authproto_auth_proto_enumTypes[0].Descriptor()
}

func (TargetLoginPromptType) Type() protoreflect.EnumType {
	return &file_authproto_auth_proto_enumTypes[0]
}

func (x TargetLoginPromptType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetLoginPromptType.Descriptor instead.
func (TargetLoginPromptType) EnumDescriptor() ([]byte, []int) {
	return file_authproto_auth_proto_rawDescGZIP(), []int{0}
}

// TargetLoginRequest describes the target that the client wants to log into.
type TargetLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *apapproto.Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// Create a transient SSH connection for this login attempt instead of
	// reusing a cached SSH connection.
	// This re-evaluates host-key verification and authentication, prompts again
	// if needed, and closes the resulting connection without caching it.
	// For non-SSH targets, this option is ignored.
	CreateTransientSshConnection bool `protobuf:"varint,2,opt,name=create_transient_ssh_connection,json=createTransientSshConnection,proto3" json:"create_transient_ssh_connection,omitempty"`
}

func (x *TargetLoginRequest) Reset() {
	*x = TargetLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authproto_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetLoginRequest) ProtoMessage() {}

func (x *TargetLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authproto_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetLoginRequest.ProtoReflect.Descriptor instead.
func (*TargetLoginRequest) Descriptor() ([]byte, []int) {
	return file_authproto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *TargetLoginRequest) GetTarget() *apapproto.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *TargetLoginRequest) GetCreateTransientSshConnection() bool {
	if x != nil {
		return x.CreateTransientSshConnection
	}
	return false
}

// TargetLoginResponse returns placeholder information for the target login request.
type TargetLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReturnCode apapproto.StatusCode  `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3,enum=apap.StatusCode" json:"return_code,omitempty"`
	Error      *apapproto.ErrorChain `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *TargetLoginResponse) Reset() {
	*x = TargetLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authproto_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetLoginResponse) ProtoMessage() {}

func (x *TargetLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authproto_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetLoginResponse.ProtoReflect.Descriptor instead.
func (*TargetLoginResponse) Descriptor() ([]byte, []int) {
	return file_authproto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *TargetLoginResponse) GetReturnCode() apapproto.StatusCode {
	if x != nil {
		return x.ReturnCode
	}
	return apapproto.StatusCode(0)
}

func (x *TargetLoginResponse) GetError() *apapproto.ErrorChain {
	if x != nil {
		return x.Error
	}
	return nil
}

// TargetLoginClientMessage encapsulates all client-to-server communication for the TargetLogin RPC.
type TargetLoginClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*TargetLoginClientMessage_Request
	//	*TargetLoginClientMessage_Credentials
	//	*TargetLoginClientMessage_FingerprintAcceptance
	Message isTargetLoginClientMessage_Message `protobuf_oneof:"message"`
}

func (x *TargetLoginClientMessage) Reset() {
	*x = TargetLoginClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authproto_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetLoginClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetLoginClientMessage) ProtoMessage() {}

func (x *TargetLoginClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_authproto_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetLoginClientMessage.ProtoReflect.Descriptor instead.
func (*TargetLoginClientMessage) Descriptor() ([]byte, []int) {
	return file_authproto_auth_proto_rawDescGZIP(), []int{2}
}

func (m *TargetLoginClientMessage) GetMessage() isTargetLoginClientMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *TargetLoginClientMessage) GetRequest() *TargetLoginRequest {
	if x, ok := x.GetMessage().(*TargetLoginClientMessage_Request); ok {
		return x.Request
	}
	return nil
}

func (x *TargetLoginClientMessage) GetCredentials() *TargetLoginCredentials {
	if x, ok := x.GetMessage().(*TargetLoginClientMessage_Credentials); ok {
		return x.Credentials
	}
	return nil
}

func (x *TargetLoginClientMessage) GetFingerprintAcceptance() *TargetLoginFingerprintAcceptance {
	if x, ok := x.GetMessage().(*TargetLoginClientMessage_FingerprintAcceptance); ok {
		return x.FingerprintAcceptance
	}
	return nil
}

type isTargetLoginClientMessage_Message interface {
	isTargetLoginClientMessage_Message()
}

type TargetLoginClientMessage_Request struct {
	Request *TargetLoginRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type TargetLoginClientMessage_Credentials struct {
	Credentials *TargetLoginCredentials `protobuf:"bytes,2,opt,name=credentials,proto3,oneof"`
}

type TargetLoginClientMessage_FingerprintAcceptance struct {
	FingerprintAcceptance *TargetLoginFingerprintAcceptance `protobuf:"bytes,3,opt,name=fingerprint_acceptance,json=fingerprintAcceptance,proto3,oneof"`
}

func (*TargetLoginClientMessage_Request) isTargetLoginClientMessage_Message() {}

func (*TargetLoginClientMessage_Credentials) isTargetLoginClientMessage_Message() {}

func (*TargetLoginClientMessage_FingerprintAcceptance) isTargetLoginClientMessage_Message() {}

// TargetLoginServerMessage encapsulates all server-to-client communication for the TargetLogin RPC.
type TargetLoginServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*TargetLoginServerMessage_Prompt
	//	*TargetLoginServerMessage_Response
	//	*TargetLoginServerMessage_FingerprintPrompt
	Message isTargetLoginServerMessage_Message `protobuf_oneof:"message"`
}

func (x *TargetLoginServerMessage) Reset() {
	*x = TargetLoginServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authproto_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetLoginServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetLoginServerMessage) ProtoMessage() {}

func (x *TargetLoginServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_authproto_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetLoginServerMessage.ProtoReflect.Descriptor instead.
func (*TargetLoginServerMessage) Descriptor() ([]byte, []int) {
	return file_authproto_auth_proto_rawDescGZIP(), []int{3}
}

func (m *TargetLoginServerMessage) GetMessage() isTargetLoginServerMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *TargetLoginServerMessage) GetPrompt() *TargetLoginPrompt {
	if x, ok := x.GetMessage().(*TargetLoginServerMessage_Prompt); ok {
		return x.Prompt
	}
	return nil
}

func (x *TargetLoginServerMessage) GetResponse() *TargetLoginResponse {
	if x, ok := x.GetMessage().(*TargetLoginServerMessage_Response); ok {
		return x.Response
	}
	return nil
}

func (x *TargetLoginServerMessage) GetFingerprintPrompt() *TargetLoginFingerprintPrompt {
	if x, ok := x.GetMessage().(*TargetLoginServerMessage_FingerprintPrompt); ok {
		return x.FingerprintPrompt
	}
	return nil
}

type isTargetLoginServerMessage_Message interface {
	isTargetLoginServerMessage_Message()
}

type TargetLoginServerMessage_Prompt struct {
	Prompt *TargetLoginPrompt `protobuf:"bytes,1,opt,name=prompt,proto3,oneof"`
}

type TargetLoginServerMessage_Response struct {
	Response *TargetLoginResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type TargetLoginServerMessage_FingerprintPrompt struct {
	FingerprintPrompt *TargetLoginFingerprintPrompt `protobuf:"bytes,3,opt,name=fingerprint_prompt,json=fingerprintPrompt,proto3,oneof"`
}

func (*TargetLoginServerMessage_Prompt) isTargetLoginServerMessage_Message() {}

func (*TargetLoginServerMessage_Response) isTargetLoginServerMessage_Message() {}

func (*TargetLoginServerMessage_FingerprintPrompt) isTargetLoginServerMessage_Message() {}

// TargetLoginPrompt requests additional information from the client, such as passwords or passphrases.
type TargetLoginPrompt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type           TargetLoginPromptType `protobuf:"varint,2,opt,name=type,proto3,enum=auth.TargetLoginPromptType" json:"type,omitempty"`
	Host           string                `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	JumpIndex      uint32                `protobuf:"varint,4,opt,name=jump_index,json=jumpIndex,proto3" json:"jump_index,omitempty"`
	KeyPath        string                `protobuf:"bytes,5,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	CurrentAttempt uint32                `protobuf:"varint,6,opt,name=current_attempt,json=currentAttempt,proto3" json:"current_attempt,omitempty"`
	MaxAttempts    uint32                `protobuf:"varint,7,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	Username       string                `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	TotalJumps     uint32                `protobuf:"varint,9,opt,name=total_jumps,json=totalJumps,proto3" json:"total_jumps,omitempty"`
}

func (x *TargetLoginPrompt) Reset() {
	*x = TargetLoginPrompt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authproto_auth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetLoginPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetLoginPrompt) ProtoMessage() {}

func (x *TargetLoginPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_authproto_auth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetLoginPrompt.ProtoReflect.Descriptor instead.
func (*TargetLoginPrompt) Descriptor() ([]byte, []int) {
	return file_authproto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *TargetLoginPrompt) GetType() TargetLoginPromptType {
	if x != nil {
		return x.Type
	}
	return TargetLoginPromptType_TARGET_LOGIN_PROMPT_TYPE_UNSPECIFIED
}

func (x *TargetLoginPrompt) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TargetLoginPrompt) GetJumpIndex() uint32 {
	if x != nil {
		return x.JumpIndex
	}
	return 0
}

func (x *TargetLoginPrompt) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

func (x *TargetLoginPrompt) GetCurrentAttempt() uint32 {
	if x != nil {
		return x.CurrentAttempt
	}
	return 0
}

func (x *TargetLoginPrompt) GetMaxAttempts() uint32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *TargetLoginPrompt) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TargetLoginPrompt) GetTotalJumps() uint32 {
	if x != nil {
		return x.TotalJumps
	}
	return 0
}

// TargetLoginCredentials responds to a secret prompt issued by the server.
type TargetLoginCredentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret []byte `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *TargetLoginCredentials) Reset() {
	*x = TargetLoginCredentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authproto_auth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetLoginCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetLoginCredentials) ProtoMessage() {}

func (x *TargetLoginCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_authproto_auth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetLoginCredentials.ProtoReflect.Descriptor instead.
func (*TargetLoginCredentials) Descriptor() ([]byte, []int) {
	return file_authproto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *TargetLoginCredentials) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

// TargetLoginFingerprintAcceptance responds to a host-key prompt issued by the server.
type TargetLoginFingerprintAcceptance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *TargetLoginFingerprintAcceptance) Reset() {
	*x = TargetLoginFingerprintAcceptance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authproto_auth_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetLoginFingerprintAcceptance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetLoginFingerprintAcceptance) ProtoMessage() {}

func (x *TargetLoginFingerprintAcceptance) ProtoReflect() protoreflect.Message {
	mi := &file_authproto_auth_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetLoginFingerprintAcceptance.ProtoReflect.Descriptor instead.
func (*TargetLoginFingerprintAcceptance) Descriptor() ([]byte, []int) {
	return file_authproto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *TargetLoginFingerprintAcceptance) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// TargetLoginFingerprintPrompt requests acceptance for a host key fingerprint.
type TargetLoginFingerprintPrompt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host               string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	HostKeyType        string   `protobuf:"bytes,2,opt,name=host_key_type,json=hostKeyType,proto3" json:"host_key_type,omitempty"`
	HostKeyFingerprint string   `protobuf:"bytes,3,opt,name=host_key_fingerprint,json=hostKeyFingerprint,proto3" json:"host_key_fingerprint,omitempty"`
	KnownAs            []string `protobuf:"bytes,4,rep,name=known_as,json=knownAs,proto3" json:"known_as,omitempty"`
}

func (x *TargetLoginFingerprintPrompt) Reset() {
	*x = TargetLoginFingerprintPrompt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authproto_auth_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetLoginFingerprintPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetLoginFingerprintPrompt) ProtoMessage() {}

func (x *TargetLoginFingerprintPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_authproto_auth_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetLoginFingerprintPrompt.ProtoReflect.Descriptor instead.
func (*TargetLoginFingerprintPrompt) Descriptor() ([]byte, []int) {
	return file_authproto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *TargetLoginFingerprintPrompt) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TargetLoginFingerprintPrompt) GetHostKeyType() string {
	if x != nil {
		return x.HostKeyType
	}
	return ""
}

func (x *TargetLoginFingerprintPrompt) GetHostKeyFingerprint() string {
	if x != nil {
		return x.HostKeyFingerprint
	}
	return ""
}

func (x *TargetLoginFingerprintPrompt) GetKnownAs() []string {
	if x != nil {
		return x.KnownAs
	}
	return nil
}

var File_authproto_auth_proto protoreflect.FileDescriptor

var file_authproto_auth_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x75, 0x74, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x14, 0x61, 0x70,
	0x61, 0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x12, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x61, 0x70,
	0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12,
	0x45, 0x0a, 0x1f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x73, 0x73, 0x68, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x1c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x70, 0x0a, 0x13, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x61, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x26, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x61, 0x70, 0x61, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xfe, 0x01, 0x0a, 0x18, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x48, 0x00,
	0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x5f, 0x0a,
	0x16, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x5f, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x48, 0x00, 0x52, 0x15, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x09,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xe6, 0x01, 0x0a, 0x18, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x48,
	0x00, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x37, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x53, 0x0a, 0x12, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x48, 0x00, 0x52, 0x11, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x9b, 0x02, 0x0a, 0x11, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x6a, 0x75, 0x6d, 0x70, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x6a, 0x75, 0x6d, 0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x19, 0x0a, 0x08,
	0x6b, 0x65, 0x79, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x5f, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x41, 0x74, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6a, 0x75, 0x6d, 0x70, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4a, 0x75, 0x6d, 0x70, 0x73,
	0x22, 0x30, 0x0a, 0x16, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x22, 0x3e, 0x0a, 0x20, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x65, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x1c, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x68, 0x6f, 0x73, 0x74, 0x5f,
	0x6b, 0x65, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x68, 0x6f, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72,
	0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x68, 0x6f, 0x73, 0x74, 0x4b,
	0x65, 0x79, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x61, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x41, 0x73, 0x2a, 0x94, 0x01, 0x0a, 0x15, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x28, 0x0a, 0x24, 0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x5f, 0x4c, 0x4f, 0x47,
	0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x25, 0x0a, 0x21,
	0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f,
	0x4d, 0x50, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52,
	0x44, 0x10, 0x01, 0x12, 0x2a, 0x0a, 0x26, 0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x5f, 0x4c, 0x4f,
	0x47, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x4d, 0x50, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x4b, 0x45, 0x59, 0x50, 0x41, 0x53, 0x53, 0x50, 0x48, 0x52, 0x41, 0x53, 0x45, 0x10, 0x02, 0x32,
	0x59, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x51, 0x0a, 0x0b, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x72, 0x6d, 0x2d, 0x44, 0x65, 0x62,
	0x75, 0x67, 0x2f, 0x61, 0x70, 0x61, 0x70, 0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authproto_auth_proto_rawDescOnce sync.Once
	file_authproto_auth_proto_rawDescData = file_authproto_auth_proto_rawDesc
)

func file_authproto_auth_proto_rawDescGZIP() []byte {
	file_authproto_auth_proto_rawDescOnce.Do(func() {
		file_authproto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_authproto_auth_proto_rawDescData)
	})
	return file_authproto_auth_proto_rawDescData
}

var file_authproto_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authproto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_authproto_auth_proto_goTypes = []any{
	(TargetLoginPromptType)(0),               // 0: auth.TargetLoginPromptType
	(*TargetLoginRequest)(nil),               // 1: auth.TargetLoginRequest
	(*TargetLoginResponse)(nil),              // 2: auth.TargetLoginResponse
	(*TargetLoginClientMessage)(nil),         // 3: auth.TargetLoginClientMessage
	(*TargetLoginServerMessage)(nil),         // 4: auth.TargetLoginServerMessage
	(*TargetLoginPrompt)(nil),                // 5: auth.TargetLoginPrompt
	(*TargetLoginCredentials)(nil),           // 6: auth.TargetLoginCredentials
	(*TargetLoginFingerprintAcceptance)(nil), // 7: auth.TargetLoginFingerprintAcceptance
	(*TargetLoginFingerprintPrompt)(nil),     // 8: auth.TargetLoginFingerprintPrompt
	(*apapproto.Target)(nil),                 // 9: apap.Target
	(apapproto.StatusCode)(0),                // 10: apap.StatusCode
	(*apapproto.ErrorChain)(nil),             // 11: apap.ErrorChain
}
var file_authproto_auth_proto_depIdxs = []int32{
	9,  // 0: auth.TargetLoginRequest.target:type_name -> apap.Target
	10, // 1: auth.TargetLoginResponse.return_code:type_name -> apap.StatusCode
	11, // 2: auth.TargetLoginResponse.error:type_name -> apap.ErrorChain
	1,  // 3: auth.TargetLoginClientMessage.request:type_name -> auth.TargetLoginRequest
	6,  // 4: auth.TargetLoginClientMessage.credentials:type_name -> auth.TargetLoginCredentials
	7,  // 5: auth.TargetLoginClientMessage.fingerprint_acceptance:type_name -> auth.TargetLoginFingerprintAcceptance
	5,  // 6: auth.TargetLoginServerMessage.prompt:type_name -> auth.TargetLoginPrompt
	2,  // 7: auth.TargetLoginServerMessage.response:type_name -> auth.TargetLoginResponse
	8,  // 8: auth.TargetLoginServerMessage.fingerprint_prompt:type_name -> auth.TargetLoginFingerprintPrompt
	0,  // 9: auth.TargetLoginPrompt.type:type_name -> auth.TargetLoginPromptType
	3,  // 10: auth.Auth.TargetLogin:input_type -> auth.TargetLoginClientMessage
	4,  // 11: auth.Auth.TargetLogin:output_type -> auth.TargetLoginServerMessage
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_authproto_auth_proto_init() }
func file_authproto_auth_proto_init() {
	if File_authproto_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authproto_auth_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TargetLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authproto_auth_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TargetLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authproto_auth_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TargetLoginClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authproto_auth_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TargetLoginServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authproto_auth_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TargetLoginPrompt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authproto_auth_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TargetLoginCredentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authproto_auth_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*TargetLoginFingerprintAcceptance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authproto_auth_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*TargetLoginFingerprintPrompt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_authproto_auth_proto_msgTypes[2].OneofWrappers = []any{
		(*TargetLoginClientMessage_Request)(nil),
		(*TargetLoginClientMessage_Credentials)(nil),
		(*TargetLoginClientMessage_FingerprintAcceptance)(nil),
	}
	file_authproto_auth_proto_msgTypes[3].OneofWrappers = []any{
		(*TargetLoginServerMessage_Prompt)(nil),
		(*TargetLoginServerMessage_Response)(nil),
		(*TargetLoginServerMessage_FingerprintPrompt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authproto_auth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authproto_auth_proto_goTypes,
		DependencyIndexes: file_authproto_auth_proto_depIdxs,
		EnumInfos:         file_authproto_auth_proto_enumTypes,
		MessageInfos:      file_authproto_auth_proto_msgTypes,
	}.Build()
	File_authproto_auth_proto = out.File
	file_authproto_auth_proto_rawDesc = nil
	file_authproto_auth_proto_goTypes = nil
	file_authproto_auth_proto_depIdxs = nil
}
