// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.23.4
// source: authproto/auth.proto

package authproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Auth_TargetLogin_FullMethodName = "/auth.Auth/TargetLogin"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Auth service provides TLS-protected authentication entrypoints between clients and the engine.
type AuthClient interface {
	// TargetLogin establishes an authenticated session for a specific target.
	// The stream allows the service to prompt for additional credentials (for example, passwords) in the future.
	TargetLogin(ctx context.Context, opts ...grpc.CallOption) (Auth_TargetLoginClient, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) TargetLogin(ctx context.Context, opts ...grpc.CallOption) (Auth_TargetLoginClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Auth_ServiceDesc.Streams[0], Auth_TargetLogin_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &authTargetLoginClient{ClientStream: stream}
	return x, nil
}

type Auth_TargetLoginClient interface {
	Send(*TargetLoginClientMessage) error
	Recv() (*TargetLoginServerMessage, error)
	grpc.ClientStream
}

type authTargetLoginClient struct {
	grpc.ClientStream
}

func (x *authTargetLoginClient) Send(m *TargetLoginClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *authTargetLoginClient) Recv() (*TargetLoginServerMessage, error) {
	m := new(TargetLoginServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility
//
// Auth service provides TLS-protected authentication entrypoints between clients and the engine.
type AuthServer interface {
	// TargetLogin establishes an authenticated session for a specific target.
	// The stream allows the service to prompt for additional credentials (for example, passwords) in the future.
	TargetLogin(Auth_TargetLoginServer) error
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (UnimplementedAuthServer) TargetLogin(Auth_TargetLoginServer) error {
	return status.Errorf(codes.Unimplemented, "method TargetLogin not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_TargetLogin_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuthServer).TargetLogin(&authTargetLoginServer{ServerStream: stream})
}

type Auth_TargetLoginServer interface {
	Send(*TargetLoginServerMessage) error
	Recv() (*TargetLoginClientMessage, error)
	grpc.ServerStream
}

type authTargetLoginServer struct {
	grpc.ServerStream
}

func (x *authTargetLoginServer) Send(m *TargetLoginServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *authTargetLoginServer) Recv() (*TargetLoginClientMessage, error) {
	m := new(TargetLoginClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TargetLogin",
			Handler:       _Auth_TargetLogin_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "authproto/auth.proto",
}
