// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.23.4
// source: targetagentproto/targetagent.proto

package targetagentproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TargetAgent_GetVersion_FullMethodName            = "/TargetAgent/GetVersion"
	TargetAgent_Shutdown_FullMethodName              = "/TargetAgent/Shutdown"
	TargetAgent_ElevatePrivileges_FullMethodName     = "/TargetAgent/ElevatePrivileges"
	TargetAgent_GetPrivilegeInfo_FullMethodName      = "/TargetAgent/GetPrivilegeInfo"
	TargetAgent_StartProcess_FullMethodName          = "/TargetAgent/StartProcess"
	TargetAgent_ReleaseProcessHandles_FullMethodName = "/TargetAgent/ReleaseProcessHandles"
	TargetAgent_ExecCommand_FullMethodName           = "/TargetAgent/ExecCommand"
	TargetAgent_KillProcess_FullMethodName           = "/TargetAgent/KillProcess"
	TargetAgent_InterruptProcess_FullMethodName      = "/TargetAgent/InterruptProcess"
	TargetAgent_WaitProcess_FullMethodName           = "/TargetAgent/WaitProcess"
	TargetAgent_RetrieveFile_FullMethodName          = "/TargetAgent/RetrieveFile"
	TargetAgent_StoreFile_FullMethodName             = "/TargetAgent/StoreFile"
	TargetAgent_CreateTempDir_FullMethodName         = "/TargetAgent/CreateTempDir"
	TargetAgent_Mkdir_FullMethodName                 = "/TargetAgent/Mkdir"
	TargetAgent_Rm_FullMethodName                    = "/TargetAgent/Rm"
	TargetAgent_MakeWritable_FullMethodName          = "/TargetAgent/MakeWritable"
	TargetAgent_Chown_FullMethodName                 = "/TargetAgent/Chown"
	TargetAgent_ListFiles_FullMethodName             = "/TargetAgent/ListFiles"
	TargetAgent_GetTargetInfo_FullMethodName         = "/TargetAgent/GetTargetInfo"
	TargetAgent_ListProcesses_FullMethodName         = "/TargetAgent/ListProcesses"
	TargetAgent_ListAndroidPackages_FullMethodName   = "/TargetAgent/ListAndroidPackages"
	TargetAgent_SetAffinity_FullMethodName           = "/TargetAgent/SetAffinity"
	TargetAgent_StreamStdout_FullMethodName          = "/TargetAgent/StreamStdout"
	TargetAgent_StreamStderr_FullMethodName          = "/TargetAgent/StreamStderr"
	TargetAgent_WriteToStdin_FullMethodName          = "/TargetAgent/WriteToStdin"
	TargetAgent_StreamLogs_FullMethodName            = "/TargetAgent/StreamLogs"
	TargetAgent_HoldLock_FullMethodName              = "/TargetAgent/HoldLock"
)

// TargetAgentClient is the client API for TargetAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TargetAgentClient interface {
	// --------------------
	// Agent Management
	// --------------------
	GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetVersionResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ElevatePrivileges(ctx context.Context, in *ElevatePrivilegesRequest, opts ...grpc.CallOption) (*ElevatePrivilegesResponse, error)
	GetPrivilegeInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPrivilegeInfoResponse, error)
	// StartProcess starts a process on the target with the specified command and options.
	// The returned PID can be used to manage the process (e.g. stream output, wait for completion, kill, etc.).
	// Clients must call ReleaseProcessHandles with the PID when they are finished with the process to allow the agent to clean up any associated resources.
	StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*StartProcessResponse, error)
	ReleaseProcessHandles(ctx context.Context, in *ReleaseProcessHandlesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ExecCommand(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (*CommandResult, error)
	KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	InterruptProcess(ctx context.Context, in *InterruptProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	WaitProcess(ctx context.Context, in *WaitProcessRequest, opts ...grpc.CallOption) (*WaitProcessResponse, error)
	// --------------------
	// Filesystem
	// --------------------
	RetrieveFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (TargetAgent_RetrieveFileClient, error)
	StoreFile(ctx context.Context, opts ...grpc.CallOption) (TargetAgent_StoreFileClient, error)
	CreateTempDir(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TempDir, error)
	Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Rm(ctx context.Context, in *RmRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MakeWritable(ctx context.Context, in *MakeWritableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Chown(ctx context.Context, in *ChownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	// --------------------
	// System Info
	// --------------------
	GetTargetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TargetInfo, error)
	ListProcesses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProcessList, error)
	ListAndroidPackages(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AndroidPackageList, error)
	SetAffinity(ctx context.Context, in *AffinityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --------------------
	// Streaming I/O
	// --------------------
	StreamStdout(ctx context.Context, in *ProcessStreamRequest, opts ...grpc.CallOption) (TargetAgent_StreamStdoutClient, error)
	StreamStderr(ctx context.Context, in *ProcessStreamRequest, opts ...grpc.CallOption) (TargetAgent_StreamStderrClient, error)
	WriteToStdin(ctx context.Context, in *StdinChunk, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --------------------
	// Logging
	// --------------------
	StreamLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (TargetAgent_StreamLogsClient, error)
	// --------------------
	// Locking - provide controls for exclusive access to the target. The lock does
	// not restrict other clients from utilising any of the API surface. Clients are
	// expected to cooperate to respect the lock.
	// --------------------
	HoldLock(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (TargetAgent_HoldLockClient, error)
}

type targetAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewTargetAgentClient(cc grpc.ClientConnInterface) TargetAgentClient {
	return &targetAgentClient{cc}
}

func (c *targetAgentClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, TargetAgent_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetAgent_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) ElevatePrivileges(ctx context.Context, in *ElevatePrivilegesRequest, opts ...grpc.CallOption) (*ElevatePrivilegesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ElevatePrivilegesResponse)
	err := c.cc.Invoke(ctx, TargetAgent_ElevatePrivileges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) GetPrivilegeInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPrivilegeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivilegeInfoResponse)
	err := c.cc.Invoke(ctx, TargetAgent_GetPrivilegeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*StartProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartProcessResponse)
	err := c.cc.Invoke(ctx, TargetAgent_StartProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) ReleaseProcessHandles(ctx context.Context, in *ReleaseProcessHandlesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetAgent_ReleaseProcessHandles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) ExecCommand(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, TargetAgent_ExecCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetAgent_KillProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) InterruptProcess(ctx context.Context, in *InterruptProcessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetAgent_InterruptProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) WaitProcess(ctx context.Context, in *WaitProcessRequest, opts ...grpc.CallOption) (*WaitProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitProcessResponse)
	err := c.cc.Invoke(ctx, TargetAgent_WaitProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) RetrieveFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (TargetAgent_RetrieveFileClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetAgent_ServiceDesc.Streams[0], TargetAgent_RetrieveFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &targetAgentRetrieveFileClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TargetAgent_RetrieveFileClient interface {
	Recv() (*FileContent, error)
	grpc.ClientStream
}

type targetAgentRetrieveFileClient struct {
	grpc.ClientStream
}

func (x *targetAgentRetrieveFileClient) Recv() (*FileContent, error) {
	m := new(FileContent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *targetAgentClient) StoreFile(ctx context.Context, opts ...grpc.CallOption) (TargetAgent_StoreFileClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetAgent_ServiceDesc.Streams[1], TargetAgent_StoreFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &targetAgentStoreFileClient{ClientStream: stream}
	return x, nil
}

type TargetAgent_StoreFileClient interface {
	Send(*StoreRequest) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type targetAgentStoreFileClient struct {
	grpc.ClientStream
}

func (x *targetAgentStoreFileClient) Send(m *StoreRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *targetAgentStoreFileClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *targetAgentClient) CreateTempDir(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TempDir, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TempDir)
	err := c.cc.Invoke(ctx, TargetAgent_CreateTempDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetAgent_Mkdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) Rm(ctx context.Context, in *RmRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetAgent_Rm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) MakeWritable(ctx context.Context, in *MakeWritableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetAgent_MakeWritable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) Chown(ctx context.Context, in *ChownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetAgent_Chown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, TargetAgent_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) GetTargetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TargetInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetInfo)
	err := c.cc.Invoke(ctx, TargetAgent_GetTargetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) ListProcesses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProcessList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessList)
	err := c.cc.Invoke(ctx, TargetAgent_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) ListAndroidPackages(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AndroidPackageList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AndroidPackageList)
	err := c.cc.Invoke(ctx, TargetAgent_ListAndroidPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) SetAffinity(ctx context.Context, in *AffinityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetAgent_SetAffinity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) StreamStdout(ctx context.Context, in *ProcessStreamRequest, opts ...grpc.CallOption) (TargetAgent_StreamStdoutClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetAgent_ServiceDesc.Streams[2], TargetAgent_StreamStdout_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &targetAgentStreamStdoutClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TargetAgent_StreamStdoutClient interface {
	Recv() (*StreamChunk, error)
	grpc.ClientStream
}

type targetAgentStreamStdoutClient struct {
	grpc.ClientStream
}

func (x *targetAgentStreamStdoutClient) Recv() (*StreamChunk, error) {
	m := new(StreamChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *targetAgentClient) StreamStderr(ctx context.Context, in *ProcessStreamRequest, opts ...grpc.CallOption) (TargetAgent_StreamStderrClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetAgent_ServiceDesc.Streams[3], TargetAgent_StreamStderr_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &targetAgentStreamStderrClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TargetAgent_StreamStderrClient interface {
	Recv() (*StreamChunk, error)
	grpc.ClientStream
}

type targetAgentStreamStderrClient struct {
	grpc.ClientStream
}

func (x *targetAgentStreamStderrClient) Recv() (*StreamChunk, error) {
	m := new(StreamChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *targetAgentClient) WriteToStdin(ctx context.Context, in *StdinChunk, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetAgent_WriteToStdin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetAgentClient) StreamLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (TargetAgent_StreamLogsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetAgent_ServiceDesc.Streams[4], TargetAgent_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &targetAgentStreamLogsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TargetAgent_StreamLogsClient interface {
	Recv() (*LogEntry, error)
	grpc.ClientStream
}

type targetAgentStreamLogsClient struct {
	grpc.ClientStream
}

func (x *targetAgentStreamLogsClient) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *targetAgentClient) HoldLock(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (TargetAgent_HoldLockClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetAgent_ServiceDesc.Streams[5], TargetAgent_HoldLock_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &targetAgentHoldLockClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TargetAgent_HoldLockClient interface {
	Recv() (*LockGranted, error)
	grpc.ClientStream
}

type targetAgentHoldLockClient struct {
	grpc.ClientStream
}

func (x *targetAgentHoldLockClient) Recv() (*LockGranted, error) {
	m := new(LockGranted)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TargetAgentServer is the server API for TargetAgent service.
// All implementations must embed UnimplementedTargetAgentServer
// for forward compatibility
type TargetAgentServer interface {
	// --------------------
	// Agent Management
	// --------------------
	GetVersion(context.Context, *emptypb.Empty) (*GetVersionResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*emptypb.Empty, error)
	ElevatePrivileges(context.Context, *ElevatePrivilegesRequest) (*ElevatePrivilegesResponse, error)
	GetPrivilegeInfo(context.Context, *emptypb.Empty) (*GetPrivilegeInfoResponse, error)
	// StartProcess starts a process on the target with the specified command and options.
	// The returned PID can be used to manage the process (e.g. stream output, wait for completion, kill, etc.).
	// Clients must call ReleaseProcessHandles with the PID when they are finished with the process to allow the agent to clean up any associated resources.
	StartProcess(context.Context, *StartProcessRequest) (*StartProcessResponse, error)
	ReleaseProcessHandles(context.Context, *ReleaseProcessHandlesRequest) (*emptypb.Empty, error)
	ExecCommand(context.Context, *ExecCommandRequest) (*CommandResult, error)
	KillProcess(context.Context, *KillProcessRequest) (*emptypb.Empty, error)
	InterruptProcess(context.Context, *InterruptProcessRequest) (*emptypb.Empty, error)
	WaitProcess(context.Context, *WaitProcessRequest) (*WaitProcessResponse, error)
	// --------------------
	// Filesystem
	// --------------------
	RetrieveFile(*FileRequest, TargetAgent_RetrieveFileServer) error
	StoreFile(TargetAgent_StoreFileServer) error
	CreateTempDir(context.Context, *emptypb.Empty) (*TempDir, error)
	Mkdir(context.Context, *MkdirRequest) (*emptypb.Empty, error)
	Rm(context.Context, *RmRequest) (*emptypb.Empty, error)
	MakeWritable(context.Context, *MakeWritableRequest) (*emptypb.Empty, error)
	Chown(context.Context, *ChownRequest) (*emptypb.Empty, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	// --------------------
	// System Info
	// --------------------
	GetTargetInfo(context.Context, *emptypb.Empty) (*TargetInfo, error)
	ListProcesses(context.Context, *emptypb.Empty) (*ProcessList, error)
	ListAndroidPackages(context.Context, *emptypb.Empty) (*AndroidPackageList, error)
	SetAffinity(context.Context, *AffinityRequest) (*emptypb.Empty, error)
	// --------------------
	// Streaming I/O
	// --------------------
	StreamStdout(*ProcessStreamRequest, TargetAgent_StreamStdoutServer) error
	StreamStderr(*ProcessStreamRequest, TargetAgent_StreamStderrServer) error
	WriteToStdin(context.Context, *StdinChunk) (*emptypb.Empty, error)
	// --------------------
	// Logging
	// --------------------
	StreamLogs(*emptypb.Empty, TargetAgent_StreamLogsServer) error
	// --------------------
	// Locking - provide controls for exclusive access to the target. The lock does
	// not restrict other clients from utilising any of the API surface. Clients are
	// expected to cooperate to respect the lock.
	// --------------------
	HoldLock(*emptypb.Empty, TargetAgent_HoldLockServer) error
	mustEmbedUnimplementedTargetAgentServer()
}

// UnimplementedTargetAgentServer must be embedded to have forward compatible implementations.
type UnimplementedTargetAgentServer struct {
}

func (UnimplementedTargetAgentServer) GetVersion(context.Context, *emptypb.Empty) (*GetVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedTargetAgentServer) Shutdown(context.Context, *ShutdownRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedTargetAgentServer) ElevatePrivileges(context.Context, *ElevatePrivilegesRequest) (*ElevatePrivilegesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ElevatePrivileges not implemented")
}
func (UnimplementedTargetAgentServer) GetPrivilegeInfo(context.Context, *emptypb.Empty) (*GetPrivilegeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivilegeInfo not implemented")
}
func (UnimplementedTargetAgentServer) StartProcess(context.Context, *StartProcessRequest) (*StartProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProcess not implemented")
}
func (UnimplementedTargetAgentServer) ReleaseProcessHandles(context.Context, *ReleaseProcessHandlesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseProcessHandles not implemented")
}
func (UnimplementedTargetAgentServer) ExecCommand(context.Context, *ExecCommandRequest) (*CommandResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecCommand not implemented")
}
func (UnimplementedTargetAgentServer) KillProcess(context.Context, *KillProcessRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillProcess not implemented")
}
func (UnimplementedTargetAgentServer) InterruptProcess(context.Context, *InterruptProcessRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InterruptProcess not implemented")
}
func (UnimplementedTargetAgentServer) WaitProcess(context.Context, *WaitProcessRequest) (*WaitProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitProcess not implemented")
}
func (UnimplementedTargetAgentServer) RetrieveFile(*FileRequest, TargetAgent_RetrieveFileServer) error {
	return status.Errorf(codes.Unimplemented, "method RetrieveFile not implemented")
}
func (UnimplementedTargetAgentServer) StoreFile(TargetAgent_StoreFileServer) error {
	return status.Errorf(codes.Unimplemented, "method StoreFile not implemented")
}
func (UnimplementedTargetAgentServer) CreateTempDir(context.Context, *emptypb.Empty) (*TempDir, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTempDir not implemented")
}
func (UnimplementedTargetAgentServer) Mkdir(context.Context, *MkdirRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mkdir not implemented")
}
func (UnimplementedTargetAgentServer) Rm(context.Context, *RmRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rm not implemented")
}
func (UnimplementedTargetAgentServer) MakeWritable(context.Context, *MakeWritableRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeWritable not implemented")
}
func (UnimplementedTargetAgentServer) Chown(context.Context, *ChownRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chown not implemented")
}
func (UnimplementedTargetAgentServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedTargetAgentServer) GetTargetInfo(context.Context, *emptypb.Empty) (*TargetInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTargetInfo not implemented")
}
func (UnimplementedTargetAgentServer) ListProcesses(context.Context, *emptypb.Empty) (*ProcessList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedTargetAgentServer) ListAndroidPackages(context.Context, *emptypb.Empty) (*AndroidPackageList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAndroidPackages not implemented")
}
func (UnimplementedTargetAgentServer) SetAffinity(context.Context, *AffinityRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAffinity not implemented")
}
func (UnimplementedTargetAgentServer) StreamStdout(*ProcessStreamRequest, TargetAgent_StreamStdoutServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamStdout not implemented")
}
func (UnimplementedTargetAgentServer) StreamStderr(*ProcessStreamRequest, TargetAgent_StreamStderrServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamStderr not implemented")
}
func (UnimplementedTargetAgentServer) WriteToStdin(context.Context, *StdinChunk) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteToStdin not implemented")
}
func (UnimplementedTargetAgentServer) StreamLogs(*emptypb.Empty, TargetAgent_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedTargetAgentServer) HoldLock(*emptypb.Empty, TargetAgent_HoldLockServer) error {
	return status.Errorf(codes.Unimplemented, "method HoldLock not implemented")
}
func (UnimplementedTargetAgentServer) mustEmbedUnimplementedTargetAgentServer() {}

// UnsafeTargetAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TargetAgentServer will
// result in compilation errors.
type UnsafeTargetAgentServer interface {
	mustEmbedUnimplementedTargetAgentServer()
}

func RegisterTargetAgentServer(s grpc.ServiceRegistrar, srv TargetAgentServer) {
	s.RegisterService(&TargetAgent_ServiceDesc, srv)
}

func _TargetAgent_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).GetVersion(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_ElevatePrivileges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElevatePrivilegesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).ElevatePrivileges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_ElevatePrivileges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).ElevatePrivileges(ctx, req.(*ElevatePrivilegesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_GetPrivilegeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).GetPrivilegeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_GetPrivilegeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).GetPrivilegeInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_StartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).StartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_StartProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).StartProcess(ctx, req.(*StartProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_ReleaseProcessHandles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseProcessHandlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).ReleaseProcessHandles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_ReleaseProcessHandles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).ReleaseProcessHandles(ctx, req.(*ReleaseProcessHandlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_ExecCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).ExecCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_ExecCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).ExecCommand(ctx, req.(*ExecCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_KillProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).KillProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_KillProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).KillProcess(ctx, req.(*KillProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_InterruptProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterruptProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).InterruptProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_InterruptProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).InterruptProcess(ctx, req.(*InterruptProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_WaitProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).WaitProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_WaitProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).WaitProcess(ctx, req.(*WaitProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_RetrieveFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetAgentServer).RetrieveFile(m, &targetAgentRetrieveFileServer{ServerStream: stream})
}

type TargetAgent_RetrieveFileServer interface {
	Send(*FileContent) error
	grpc.ServerStream
}

type targetAgentRetrieveFileServer struct {
	grpc.ServerStream
}

func (x *targetAgentRetrieveFileServer) Send(m *FileContent) error {
	return x.ServerStream.SendMsg(m)
}

func _TargetAgent_StoreFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TargetAgentServer).StoreFile(&targetAgentStoreFileServer{ServerStream: stream})
}

type TargetAgent_StoreFileServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*StoreRequest, error)
	grpc.ServerStream
}

type targetAgentStoreFileServer struct {
	grpc.ServerStream
}

func (x *targetAgentStoreFileServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *targetAgentStoreFileServer) Recv() (*StoreRequest, error) {
	m := new(StoreRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TargetAgent_CreateTempDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).CreateTempDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_CreateTempDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).CreateTempDir(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_Mkdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).Mkdir(ctx, req.(*MkdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_Rm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).Rm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_Rm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).Rm(ctx, req.(*RmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_MakeWritable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeWritableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).MakeWritable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_MakeWritable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).MakeWritable(ctx, req.(*MakeWritableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_Chown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).Chown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_Chown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).Chown(ctx, req.(*ChownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_GetTargetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).GetTargetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_GetTargetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).GetTargetInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).ListProcesses(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_ListAndroidPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).ListAndroidPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_ListAndroidPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).ListAndroidPackages(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_SetAffinity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AffinityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).SetAffinity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_SetAffinity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).SetAffinity(ctx, req.(*AffinityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_StreamStdout_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetAgentServer).StreamStdout(m, &targetAgentStreamStdoutServer{ServerStream: stream})
}

type TargetAgent_StreamStdoutServer interface {
	Send(*StreamChunk) error
	grpc.ServerStream
}

type targetAgentStreamStdoutServer struct {
	grpc.ServerStream
}

func (x *targetAgentStreamStdoutServer) Send(m *StreamChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _TargetAgent_StreamStderr_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetAgentServer).StreamStderr(m, &targetAgentStreamStderrServer{ServerStream: stream})
}

type TargetAgent_StreamStderrServer interface {
	Send(*StreamChunk) error
	grpc.ServerStream
}

type targetAgentStreamStderrServer struct {
	grpc.ServerStream
}

func (x *targetAgentStreamStderrServer) Send(m *StreamChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _TargetAgent_WriteToStdin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StdinChunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetAgentServer).WriteToStdin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetAgent_WriteToStdin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetAgentServer).WriteToStdin(ctx, req.(*StdinChunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetAgent_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetAgentServer).StreamLogs(m, &targetAgentStreamLogsServer{ServerStream: stream})
}

type TargetAgent_StreamLogsServer interface {
	Send(*LogEntry) error
	grpc.ServerStream
}

type targetAgentStreamLogsServer struct {
	grpc.ServerStream
}

func (x *targetAgentStreamLogsServer) Send(m *LogEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _TargetAgent_HoldLock_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetAgentServer).HoldLock(m, &targetAgentHoldLockServer{ServerStream: stream})
}

type TargetAgent_HoldLockServer interface {
	Send(*LockGranted) error
	grpc.ServerStream
}

type targetAgentHoldLockServer struct {
	grpc.ServerStream
}

func (x *targetAgentHoldLockServer) Send(m *LockGranted) error {
	return x.ServerStream.SendMsg(m)
}

// TargetAgent_ServiceDesc is the grpc.ServiceDesc for TargetAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TargetAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TargetAgent",
	HandlerType: (*TargetAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _TargetAgent_GetVersion_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _TargetAgent_Shutdown_Handler,
		},
		{
			MethodName: "ElevatePrivileges",
			Handler:    _TargetAgent_ElevatePrivileges_Handler,
		},
		{
			MethodName: "GetPrivilegeInfo",
			Handler:    _TargetAgent_GetPrivilegeInfo_Handler,
		},
		{
			MethodName: "StartProcess",
			Handler:    _TargetAgent_StartProcess_Handler,
		},
		{
			MethodName: "ReleaseProcessHandles",
			Handler:    _TargetAgent_ReleaseProcessHandles_Handler,
		},
		{
			MethodName: "ExecCommand",
			Handler:    _TargetAgent_ExecCommand_Handler,
		},
		{
			MethodName: "KillProcess",
			Handler:    _TargetAgent_KillProcess_Handler,
		},
		{
			MethodName: "InterruptProcess",
			Handler:    _TargetAgent_InterruptProcess_Handler,
		},
		{
			MethodName: "WaitProcess",
			Handler:    _TargetAgent_WaitProcess_Handler,
		},
		{
			MethodName: "CreateTempDir",
			Handler:    _TargetAgent_CreateTempDir_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _TargetAgent_Mkdir_Handler,
		},
		{
			MethodName: "Rm",
			Handler:    _TargetAgent_Rm_Handler,
		},
		{
			MethodName: "MakeWritable",
			Handler:    _TargetAgent_MakeWritable_Handler,
		},
		{
			MethodName: "Chown",
			Handler:    _TargetAgent_Chown_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _TargetAgent_ListFiles_Handler,
		},
		{
			MethodName: "GetTargetInfo",
			Handler:    _TargetAgent_GetTargetInfo_Handler,
		},
		{
			MethodName: "ListProcesses",
			Handler:    _TargetAgent_ListProcesses_Handler,
		},
		{
			MethodName: "ListAndroidPackages",
			Handler:    _TargetAgent_ListAndroidPackages_Handler,
		},
		{
			MethodName: "SetAffinity",
			Handler:    _TargetAgent_SetAffinity_Handler,
		},
		{
			MethodName: "WriteToStdin",
			Handler:    _TargetAgent_WriteToStdin_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RetrieveFile",
			Handler:       _TargetAgent_RetrieveFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StoreFile",
			Handler:       _TargetAgent_StoreFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamStdout",
			Handler:       _TargetAgent_StreamStdout_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamStderr",
			Handler:       _TargetAgent_StreamStderr_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _TargetAgent_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HoldLock",
			Handler:       _TargetAgent_HoldLock_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "targetagentproto/targetagent.proto",
}
