// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

package render

import (
	"fmt"

	"github.com/Arm-Debug/apap-cli/apap-engine/cdf"
	"github.com/Arm-Debug/apap-cli/apap-engine/run"
)

type ManifestEntryInfo struct {
	componentType     cdf.ComponentType
	rendererIdentity  RendererIdentity
	associatedContent []run.RunID
	pending           bool
}

func NewManifestEntryInfo(
	componentType cdf.ComponentType,
	rendererIdentity RendererIdentity,
	associatedContent []run.RunID,
) ManifestEntryInfo {
	return ManifestEntryInfo{componentType, rendererIdentity, associatedContent, false}
}

func (i *ManifestEntryInfo) ComponentType() cdf.ComponentType {
	return i.componentType
}

func (i *ManifestEntryInfo) RendererIdentity() RendererIdentity {
	return i.rendererIdentity
}

func (i *ManifestEntryInfo) RendererIndex() int { return i.rendererIdentity.Index }

func (i *ManifestEntryInfo) AssociatedContent() []run.RunID { return i.associatedContent }

func (i *ManifestEntryInfo) Pending() bool { return i.pending }

type TableType int

const (
	RegularTable TableType = iota
	// if hidden, it should not be reported to the GUI; generally used to generate unique names for temporary tables
	HiddenTable
	// if temp, it should not be reported to the GUI and is expected to be short-lived; used for transient tables that are not intended for public consumption
	TempTable
)

type ManifestEntry struct {
	info      ManifestEntryInfo
	tableName string
	tableType TableType
}

func (e *ManifestEntry) Info() *ManifestEntryInfo {
	return &e.info
}

func (e *ManifestEntry) TableName() string {
	return e.tableName
}

func (e *ManifestEntry) IsHidden() bool { return e.tableType == HiddenTable }

func (e *ManifestEntry) IsTemp() bool { return e.tableType == TempTable }

// Manifest describes all the tables which can be queried while the render session is active.
type Manifest struct {
	entries []ManifestEntry
}

func NewManifest() Manifest {
	return Manifest{entries: []ManifestEntry{}}
}

func (m *Manifest) GetEntry(tableName string) (ManifestEntry, error) {
	for _, e := range m.entries {
		if e.tableName == tableName {
			return e, nil
		}
	}
	return ManifestEntry{}, fmt.Errorf("manifest entry not found")
}

func (m *Manifest) Entries() []ManifestEntry {
	return m.entries
}

// TempTableNames returns the current temp table names tracked by the manifest.
//
// Temp entries are treated as disposable staging tables by the current render session lifecycle.
func (m *Manifest) TempTableNames() []string {
	tempTableNames := make([]string, 0)
	for _, entry := range m.entries {
		if !entry.IsTemp() {
			continue
		}
		tempTableNames = append(tempTableNames, entry.TableName())
	}
	return tempTableNames
}

// RemoveEntry deletes a manifest entry by table name.
func (m *Manifest) RemoveEntry(tableName string) error {
	for i, e := range m.entries {
		if e.tableName == tableName {
			m.entries = append(m.entries[:i], m.entries[i+1:]...)
			return nil
		}
	}
	return fmt.Errorf("manifest entry not found")
}

func (m *Manifest) countEntriesByComponentType(componentType string) int {
	count := 0
	for _, entry := range m.entries {
		if entry.Info().ComponentType().Name == componentType {
			count++
		}
	}
	return count
}

func SanitizeTableName(s string) string {
	bytes := make([]byte, len(s))
	for i := range s {
		c := s[i]
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9', c == '_':
			bytes[i] = c
		default:
			bytes[i] = '_'
		}
	}
	return string(bytes)
}

// AddEntry adds an entry to the Manifest. The table name of the entry is generated by this function and is guaranteed
// to be unique within the Database, as long as the session prefix is set appropriately on the Manifest.
func (m *Manifest) AddEntry(info ManifestEntryInfo) string {
	return m.addEntryInternal(info, RegularTable)
}

// AddEntryHidden adds a hidden entry to the Manifest. The table name of the entry is generated by this function and is
// guaranteed to be unique within the Database, as long as the session prefix is set appropriately on the Manifest.
// Use this variant when you want to add a new table with a well-known component type but don't want to publicize it yet.
func (m *Manifest) AddEntryHidden(info ManifestEntryInfo) string {
	return m.addEntryInternal(info, HiddenTable)
}

func (m *Manifest) addEntryInternal(info ManifestEntryInfo, tableType TableType) string {
	indexStr := ""
	index := m.countEntriesByComponentType(info.componentType.Name)
	if index > 0 {
		indexStr = fmt.Sprintf("_%d", index)
	}
	componentName := SanitizeTableName(info.componentType.Name)
	tableName := componentName + indexStr
	entry := ManifestEntry{info: info, tableName: tableName, tableType: tableType}
	m.entries = append(m.entries, entry)
	return tableName
}

// AddTempTable generates a new unique temporary table name by adding a temp entry to the manifest. These
// entries will not be reported to the GUI.
//
// Temp Tables are automatically dropped after each renderer initialization.
func (m *Manifest) AddTempTable() string {
	return m.addEntryInternal(
		ManifestEntryInfo{
			componentType: cdf.ComponentType{
				Name:          "anonymous",
				SchemaVersion: "0.0",
			},
			rendererIdentity:  RendererIdentity{},
			associatedContent: []run.RunID{},
		},
		TempTable,
	)
}

// GetComponentTypeFromTable retrieves the component type of a table from the manifest.
func (m *Manifest) GetComponentTypeFromTable(tableName string) (cdf.ComponentType, error) {
	for _, entry := range m.entries {
		if entry.tableName == tableName {
			return entry.info.ComponentType(), nil
		}
	}
	return cdf.ComponentType{}, fmt.Errorf("table '%s' not found in manifest", tableName)
}
