// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

package renderimpls

import (
	"fmt"
	"path/filepath"

	"github.com/Arm-Debug/apap-cli/apap-engine/cdf"
	"github.com/Arm-Debug/apap-cli/apap-engine/render"
	"github.com/Arm-Debug/apap-cli/apap-engine/run"
	"github.com/Arm-Debug/apap-cli/apap-engine/target"
	"github.com/Arm-Debug/apap-cli/apap-engine/util"
)

// SourceCodeAttribution is a renderer that creates a source code attribution table from the periodic_samples table
// and the source_files table.
// The source code attribution table maps performance samples to source code files and lines.
// It uses the source_files table to map addresses to source files and lines.
// The periodic_samples table is expected to be generated by the sources-capture-periodic_sampling component.

type SourceCodeAttributionConfig struct {
	PeriodicSamples string `json:"periodic-samples"`
	Entity          string `json:"entity"`
}

type SourceCodeAttributionRenderer struct {
	config         *render.Config
	specificConfig *SourceCodeAttributionConfig
}

func (r *SourceCodeAttributionRenderer) Name() string {
	return "SourceCodeAttribution"
}

func (r *SourceCodeAttributionRenderer) Version() string {
	return "1.0.0"
}

func (r *SourceCodeAttributionRenderer) NewManifestEntryInfo(
	componentTypeName string, associatedContent []run.RunID,
) render.ManifestEntryInfo {
	return render.NewManifestEntryInfo(
		cdf.ComponentType{Name: componentTypeName, SchemaVersion: r.Version()},
		r.config.Identity,
		associatedContent,
	)
}

func (r *SourceCodeAttributionRenderer) Configure(config *render.Config) error {
	r.config = config

	var err error
	r.specificConfig, err = util.DecodeJSON[SourceCodeAttributionConfig]([]byte(config.JSON))
	if err != nil {
		return fmt.Errorf("failed to parse config '%s': %w", config.JSON, err)
	}

	return nil
}

func (r *SourceCodeAttributionRenderer) getEntity() string {
	entity := r.specificConfig.Entity
	if entity == "" {
		return "tool/neoprof/0/"
	}
	return entity
}

func (r *SourceCodeAttributionRenderer) getComponentPeriodicSamples() string {
	reriodicSamples := r.specificConfig.PeriodicSamples

	if len(reriodicSamples) != 0 {
		return reriodicSamples
	}
	// If unset, return default
	return "sources-capture-periodic_sampling"
}

func (r *SourceCodeAttributionRenderer) GetInputSpec() render.InputSpec {
	inputSpec := render.InputSpec{}
	inputSpec.Ports = []render.PortSpec{
		{Name: "source_files", Cardinality: render.CardinalityPerRun, ComponentType: cdf.ComponentType{Name: "source_files", SchemaVersion: r.Version()}},
	}
	return inputSpec
}

func (r *SourceCodeAttributionRenderer) GetOutputSpec() render.OutputSpec {
	outputSpec := render.OutputSpec{}
	outputSpec.Ports = []render.PortSpec{
		{Name: "periodic_samples", Cardinality: render.CardinalityPerRun, ComponentType: cdf.ComponentType{Name: "periodic_samples", SchemaVersion: r.Version()}},
	}
	return outputSpec
}

func (r *SourceCodeAttributionRenderer) Initialize(session render.Session, resolvedDataSources map[string][]render.TableRef) error {
	sourceFilesTable, ok := resolvedDataSources["source_files"]
	if !ok || len(sourceFilesTable) == 0 {
		return fmt.Errorf("missing required input 'symbols' for SourceCodeAttributionRenderer renderer")
	}

	runTargets := map[string]target.Target{}
	runTables := map[string]string{}
	for i, entry := range session.Content().Entries {
		engineTarget, err := target.EngineTargetFromJSON(entry.Model.Metadata().TargetConfig)
		if err != nil {
			return fmt.Errorf("failed to parse target for run %s: %w", entry.ID.Value, err)
		}
		runTargets[entry.ID.Value] = engineTarget
		if i < len(sourceFilesTable) {
			runTables[entry.ID.Value] = sourceFilesTable[i].Name
		}
	}

	unionViewName := "source_files_union"
	if err := createSourceFilesUnionView(session.Database().Conn, unionViewName, runTables); err != nil {
		return fmt.Errorf("failed to create source_files_union view: %v", err)
	}
	// Do NOT create an unqualified view; macro/UDF use the qualified table to avoid schema ambiguity.
	if err := registerLoadSourceContentFunction(session.Database().Conn, unionViewName, session.TargetSessions(), runTargets, session.ID()); err != nil {
		return fmt.Errorf("failed to register load_source_content udf: %v", err)
	}

	for i, entry := range session.Content().Entries {
		err := LoadSourceCodeAttributionTables(
			session.Database().Conn,
			entry.Model,
			filepath.Join(r.getEntity(), "output/", r.getComponentPeriodicSamples()),
			sourceFilesTable[i].Name,
			func(componentTypeName string) string {
				return session.Manifest().AddEntry(
					r.NewManifestEntryInfo(componentTypeName, []run.RunID{entry.ID}),
				)
			},
		)
		if err != nil {
			return err
		}

	}
	return nil
}
