// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

package renderimpls

import (
	"fmt"
	"path/filepath"

	"github.com/Arm-Debug/apap-cli/apap-engine/cdf"
	"github.com/Arm-Debug/apap-cli/apap-engine/render"
	"github.com/Arm-Debug/apap-cli/apap-engine/run"
	"github.com/Arm-Debug/apap-cli/apap-engine/util"
)

// StreamlineAnalyzeSymbols is a renderer that creates a symbols table, an images table, and a source_files table from
// the symbols.json file generated by Streamline.

const defaultEntity string = "tool/neoprof/0/"
const defaultSymbols string = "symbols.json"

type StreamlineAnalyzeSymbolsConfig struct {
	Symbols       string `json:"symbols"`
	LegacySymbols string `json:"legacy_symbols"`
	Entity        string `json:"entity"`
}

type StreamlineAnalyzeSymbolsRenderer struct {
	config         *render.Config
	specificConfig *StreamlineAnalyzeSymbolsConfig
}

func (r *StreamlineAnalyzeSymbolsRenderer) Name() string {
	return "StreamlineAnalyzeSymbols"
}

func (r *StreamlineAnalyzeSymbolsRenderer) Version() string {
	return "1.0.0"
}

func (r *StreamlineAnalyzeSymbolsRenderer) NewManifestEntryInfo(
	componentTypeName string, associatedContent []run.RunID,
) render.ManifestEntryInfo {
	return render.NewManifestEntryInfo(
		cdf.ComponentType{Name: componentTypeName, SchemaVersion: r.Version()},
		r.config.Identity,
		associatedContent,
	)
}

func (r *StreamlineAnalyzeSymbolsRenderer) Configure(config *render.Config) error {
	r.config = config

	var err error
	r.specificConfig, err = util.DecodeJSON[StreamlineAnalyzeSymbolsConfig]([]byte(config.JSON))
	if err != nil {
		return fmt.Errorf("failed to parse config '%s': %w", config.JSON, err)
	}

	return nil
}

func (r *StreamlineAnalyzeSymbolsRenderer) getEntity() string {
	entity := r.specificConfig.Entity
	if entity == "" {
		return defaultEntity
	}
	return entity
}

func (r *StreamlineAnalyzeSymbolsRenderer) getComponentSymbols() string {
	symbols := r.specificConfig.Symbols

	if symbols == "" {
		// If unset, return default
		return defaultSymbols
	}
	return symbols
}

func (r *StreamlineAnalyzeSymbolsRenderer) getLegacyComponentSymbols() *string {
	legacy := r.specificConfig.LegacySymbols

	if legacy == "" {
		// If unset, return default
		return nil
	}
	return &legacy
}

func (r *StreamlineAnalyzeSymbolsRenderer) GetInputSpec() render.InputSpec {
	return render.InputSpec{}
}

func (r *StreamlineAnalyzeSymbolsRenderer) GetOutputSpec() render.OutputSpec {
	outputSpec := render.OutputSpec{}
	outputSpec.Ports = []render.PortSpec{
		{Name: "images", Cardinality: render.CardinalityPerRun, ComponentType: cdf.ComponentType{Name: "images", SchemaVersion: r.Version()}},
		{Name: "symbols", Cardinality: render.CardinalityPerRun, ComponentType: cdf.ComponentType{Name: "symbols", SchemaVersion: r.Version()}},
		{Name: "source_files", Cardinality: render.CardinalityPerRun, ComponentType: cdf.ComponentType{Name: "source_files", SchemaVersion: r.Version()}},
	}
	return outputSpec
}

func (r *StreamlineAnalyzeSymbolsRenderer) Initialize(session render.Session, resolvedDataSources map[string][]render.TableRef) error {

	for _, entry := range session.Content().Entries {
		symbols := r.getComponentSymbols()
		legacySymbols := r.getLegacyComponentSymbols()
		var symbolsJSONs = []string{filepath.Join(r.getEntity(), "output/", symbols)}
		if symbols != defaultSymbols && legacySymbols != nil {
			symbolsJSONs = append(symbolsJSONs, filepath.Join(r.getEntity(), "output/", *legacySymbols))
		}
		err := LoadSymbolTables(
			session.Database().Conn,
			entry.Model,
			symbolsJSONs,
			func(componentTypeName string) string {
				return session.Manifest().AddEntry(
					r.NewManifestEntryInfo(componentTypeName, []run.RunID{entry.ID}),
				)
			},
		)

		if err != nil {
			return err
		}
	}
	return nil
}
