// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

package renderimpls

import (
	"context"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/Arm-Debug/apap-cli/apap-engine/cdf"
	"github.com/Arm-Debug/apap-cli/apap-engine/render"
	"github.com/Arm-Debug/apap-cli/apap-engine/run"
)

type supportedCoreTypeRow struct {
	coreNumber int
	clusterID  int
	midr       string
	name       string
}

type supportedCoreTypeColumn struct {
	name     string
	dataType string
}

func createTargetInfoCPUTable(
	t *testing.T,
	db *render.Database,
	manifest *render.Manifest,
	runID run.RunID,
	values string,
) string {
	t.Helper()

	tableName := manifest.AddEntry(render.NewManifestEntryInfo(
		cdf.ComponentType{Name: "target-info-cpus", SchemaVersion: cpusOutputSchemaVersion},
		render.RendererIdentity{Name: "TargetInfoRenderer"},
		[]run.RunID{runID},
	))
	// #nosec G201 -- table names are manifest-generated and values are test fixtures.
	query := fmt.Sprintf(`
		CREATE TABLE %s (
			core_number BIGINT,
			cluster_id BIGINT,
			midr VARCHAR,
			name VARCHAR
		);
		INSERT INTO %s VALUES %s;
	`, QuoteColumnName(tableName), QuoteColumnName(tableName), values)
	_, err := db.Conn.ExecContext(context.Background(), query)
	require.NoError(t, err)
	return tableName
}

func readSupportedCoreTypes(t *testing.T, db *render.Database, tableName string) []supportedCoreTypeRow {
	t.Helper()

	// #nosec G201 -- tableName is generated by the render manifest.
	query := fmt.Sprintf(
		"SELECT core_number, cluster_id, midr, name FROM %s ORDER BY core_number",
		QuoteColumnName(tableName),
	)
	rows, err := db.Conn.QueryContext(context.Background(), query)
	require.NoError(t, err)
	defer rows.Close()

	result := make([]supportedCoreTypeRow, 0)
	for rows.Next() {
		var row supportedCoreTypeRow
		require.NoError(t, rows.Scan(&row.coreNumber, &row.clusterID, &row.midr, &row.name))
		result = append(result, row)
	}
	require.NoError(t, rows.Err())
	return result
}

func readSupportedCoreTypeColumns(
	t *testing.T,
	db *render.Database,
	tableName string,
) []supportedCoreTypeColumn {
	t.Helper()

	rows, err := db.Conn.QueryContext(context.Background(), `
		SELECT column_name, data_type
		FROM information_schema.columns
		WHERE table_name = ?
		ORDER BY ordinal_position
	`, tableName)
	require.NoError(t, err)
	defer rows.Close()

	result := make([]supportedCoreTypeColumn, 0)
	for rows.Next() {
		var column supportedCoreTypeColumn
		require.NoError(t, rows.Scan(&column.name, &column.dataType))
		result = append(result, column)
	}
	require.NoError(t, rows.Err())
	return result
}

func TestSupportedCoreTypesSpecs(t *testing.T) {
	renderer := &SupportedCoreTypes{}

	input := renderer.GetInputSpec().Get("target_info_cpus")
	require.NotNil(t, input)
	assert.Equal(t, render.CardinalityPerRun, input.Cardinality)
	assert.Equal(t, cdf.ComponentType{Name: "target-info-cpus", SchemaVersion: "0.1"}, input.ComponentType)

	output := renderer.GetOutputSpec().Get("supported_core_types")
	require.NotNil(t, output)
	assert.Equal(t, render.CardinalityPerRun, output.Cardinality)
	assert.Equal(t, cdf.ComponentType{Name: "target-info-supported-core-types", SchemaVersion: "0.1"}, output.ComponentType)
}

func TestSupportedCoreTypesInitialize(t *testing.T) {
	db := newDuckDB(t)
	manifest := render.NewManifest()
	runA := run.RunID{Value: "run-a"}
	runB := run.RunID{Value: "run-b"}
	inputA := createTargetInfoCPUTable(t, db, &manifest, runA, `
		(0, 0, '0x410fd0c0', 'Neoverse-N1'),
		(1, 0, '0x410fd0c0', 'Neoverse-N1'),
		(2, 1, '0x410fd490', 'Neoverse-N2'),
		(3, 1, '0x00000000', 'Unsupported CPU')
	`)
	inputB := createTargetInfoCPUTable(t, db, &manifest, runB, `
		(0, 0, '0x00000000', 'Unsupported CPU')
	`)

	content := render.ContentMap{Entries: []render.ContentMapEntry{{ID: runA}, {ID: runB}}}
	session := &render.MockSession{}
	session.On("Content").Return(&content)
	session.On("Manifest").Return(&manifest)
	session.On("Database").Return(db)

	renderer := &SupportedCoreTypes{}
	require.NoError(t, renderer.Configure(&render.Config{
		Identity: render.RendererIdentity{Name: "SupportedCoreTypes"},
	}))
	require.NoError(t, renderer.Initialize(session, render.TableRefMap{
		"target_info_cpus": {{Name: inputA}, {Name: inputB}},
	}))

	entries := manifest.Entries()
	require.Len(t, entries, 4)
	outputA := entries[2]
	outputB := entries[3]
	assert.Equal(t, []run.RunID{runA}, outputA.Info().AssociatedContent())
	assert.Equal(t, []run.RunID{runB}, outputB.Info().AssociatedContent())
	assert.Equal(t, supportedCoreTypesComponentType, outputA.Info().ComponentType())
	assert.Equal(t, supportedCoreTypesComponentType, outputB.Info().ComponentType())
	assert.Equal(t, []supportedCoreTypeColumn{
		{name: "core_number", dataType: "BIGINT"},
		{name: "cluster_id", dataType: "BIGINT"},
		{name: "midr", dataType: "VARCHAR"},
		{name: "name", dataType: "VARCHAR"},
	}, readSupportedCoreTypeColumns(t, db, outputB.TableName()))

	assert.Equal(t, []supportedCoreTypeRow{
		{coreNumber: 0, clusterID: 0, midr: "0x410fd0c0", name: "Neoverse-N1"},
		{coreNumber: 1, clusterID: 0, midr: "0x410fd0c0", name: "Neoverse-N1"},
		{coreNumber: 2, clusterID: 1, midr: "0x410fd490", name: "Neoverse-N2"},
	}, readSupportedCoreTypes(t, db, outputA.TableName()))
	assert.Empty(t, readSupportedCoreTypes(t, db, outputB.TableName()))
}

func TestSupportedCoreTypesRequiresOneInputPerRun(t *testing.T) {
	content := render.ContentMap{Entries: []render.ContentMapEntry{
		{ID: run.RunID{Value: "run-a"}},
		{ID: run.RunID{Value: "run-b"}},
	}}
	session := &render.MockSession{}
	session.On("Content").Return(&content)

	renderer := &SupportedCoreTypes{}
	err := renderer.Initialize(session, render.TableRefMap{
		"target_info_cpus": {{Name: "target_info_cpus"}},
	})
	require.EqualError(t, err, "expected one 'target_info_cpus' input per run: got 1 inputs for 2 runs")
}
