# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0

version: "2"
run:
  build-tags:
    - integration
    - duckdb_arrow
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    gosec:
      config:
        G306: "0644"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/Arm-Debug)
    goimports:
      local-prefixes:
        - github.com/Arm-Debug
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
