// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.23.4
// source: apapproto/apap.proto

package apapproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Apap_Shutdown_FullMethodName                  = "/apap.Apap/Shutdown"
	Apap_GetVersion_FullMethodName                = "/apap.Apap/GetVersion"
	Apap_GetTelemetrySpecification_FullMethodName = "/apap.Apap/GetTelemetrySpecification"
	Apap_ListRuns_FullMethodName                  = "/apap.Apap/ListRuns"
	Apap_GetRunDescription_FullMethodName         = "/apap.Apap/GetRunDescription"
	Apap_RenameRun_FullMethodName                 = "/apap.Apap/RenameRun"
	Apap_InvokeRender_FullMethodName              = "/apap.Apap/InvokeRender"
	Apap_PrepareRender_FullMethodName             = "/apap.Apap/PrepareRender"
	Apap_ListRenders_FullMethodName               = "/apap.Apap/ListRenders"
	Apap_CloseRender_FullMethodName               = "/apap.Apap/CloseRender"
	Apap_Query_FullMethodName                     = "/apap.Apap/Query"
	Apap_RecipeIssueCommand_FullMethodName        = "/apap.Apap/RecipeIssueCommand"
	Apap_RecipeReady_FullMethodName               = "/apap.Apap/RecipeReady"
	Apap_TargetTest_FullMethodName                = "/apap.Apap/TargetTest"
	Apap_TargetPrepare_FullMethodName             = "/apap.Apap/TargetPrepare"
	Apap_DeleteRun_FullMethodName                 = "/apap.Apap/DeleteRun"
	Apap_DeleteRuns_FullMethodName                = "/apap.Apap/DeleteRuns"
	Apap_ExportRun_FullMethodName                 = "/apap.Apap/ExportRun"
	Apap_TargetInfoCollector_FullMethodName       = "/apap.Apap/TargetInfoCollector"
	Apap_ListAndroidPackages_FullMethodName       = "/apap.Apap/ListAndroidPackages"
	Apap_ImportRun_FullMethodName                 = "/apap.Apap/ImportRun"
	Apap_ListPrivateSSHKeys_FullMethodName        = "/apap.Apap/ListPrivateSSHKeys"
	Apap_ParseRecipe_FullMethodName               = "/apap.Apap/ParseRecipe"
	Apap_ListRecipes_FullMethodName               = "/apap.Apap/ListRecipes"
	Apap_RecipeValidateParameters_FullMethodName  = "/apap.Apap/RecipeValidateParameters"
	Apap_FindSSHKeysForTarget_FullMethodName      = "/apap.Apap/FindSSHKeysForTarget"
	Apap_UpdateRuns_FullMethodName                = "/apap.Apap/UpdateRuns"
	Apap_LookupMessage_FullMethodName             = "/apap.Apap/LookupMessage"
	Apap_ListDirectories_FullMethodName           = "/apap.Apap/ListDirectories"
	Apap_CreateSupportPackage_FullMethodName      = "/apap.Apap/CreateSupportPackage"
	Apap_GetRunSummaryBundle_FullMethodName       = "/apap.Apap/GetRunSummaryBundle"
)

// ApapClient is the client API for Apap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Arm Performance Analysis Platform Service Definition
type ApapClient interface {
	// Requests that the server should shut down
	Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get the version of the connected server
	GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceVersion, error)
	// Get the telemetry specification for a supported CPU model
	GetTelemetrySpecification(ctx context.Context, in *GetTelemetrySpecificationRequest, opts ...grpc.CallOption) (*GetTelemetrySpecificationResponse, error)
	// Return descriptions of all runs
	ListRuns(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RunListing, error)
	// Return description a single run
	GetRunDescription(ctx context.Context, in *GetRunDescriptionRequest, opts ...grpc.CallOption) (*RunDescription, error)
	// Rename run
	RenameRun(ctx context.Context, in *RunRenameRequest, opts ...grpc.CallOption) (*RunRenameResponse, error)
	// Invoke renderer(s) - primitive for calling renderers directly
	InvokeRender(ctx context.Context, in *InvokeRenderRequest, opts ...grpc.CallOption) (*InvokeRenderResponse, error)
	// Prepare for calling InvokeRender - primitive for calling the recipe to obtain the rendering and visualization configuration
	PrepareRender(ctx context.Context, in *PrepareRenderRequest, opts ...grpc.CallOption) (*PrepareRenderResponse, error)
	// List all active render sessions and their respective memory usages
	ListRenders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RenderListing, error)
	// Close an active renderer session
	CloseRender(ctx context.Context, in *CloseRenderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Query rendered data
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (Apap_QueryClient, error)
	// Requests that the server should run the specified recipe command on the target
	RecipeIssueCommand(ctx context.Context, in *RecipeCommand, opts ...grpc.CallOption) (Apap_RecipeIssueCommandClient, error)
	// Check whether a recipe is ready to run on a target
	RecipeReady(ctx context.Context, in *RecipeReadyRequest, opts ...grpc.CallOption) (*RecipeReadyResponse, error)
	// Test the connection to the target server
	TargetTest(ctx context.Context, in *TargetTestRequest, opts ...grpc.CallOption) (*TargetTestResponse, error)
	// Test the connection to the target server
	TargetPrepare(ctx context.Context, in *TargetPrepareRequest, opts ...grpc.CallOption) (*TargetPrepareResponse, error)
	// Delete a run
	DeleteRun(ctx context.Context, in *RunId, opts ...grpc.CallOption) (*DeleteRunResponse, error)
	// Delete multiple runs
	DeleteRuns(ctx context.Context, in *DeleteRunsRequest, opts ...grpc.CallOption) (*DeleteRunsResponse, error)
	// Export a run
	ExportRun(ctx context.Context, in *RunExportRequest, opts ...grpc.CallOption) (*RunExportResponse, error)
	// Collect target information
	TargetInfoCollector(ctx context.Context, in *TargetInfoRequest, opts ...grpc.CallOption) (*TargetInfoResponse, error)
	// List Android packages and their activities for the target.
	ListAndroidPackages(ctx context.Context, in *ListAndroidPackagesRequest, opts ...grpc.CallOption) (*ListAndroidPackagesResponse, error)
	// Import a run
	ImportRun(ctx context.Context, in *RunImportRequest, opts ...grpc.CallOption) (*RunImportResponse, error)
	// List private SSH keys found in common search directories on the host machine.
	ListPrivateSSHKeys(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PrivateSSHKeyListing, error)
	// Parse the named recipe and return its definition. If a target is provided parameter value functions will be executed
	// and the target info will be exposed.
	ParseRecipe(ctx context.Context, in *ParseRecipeMessage, opts ...grpc.CallOption) (*ParseRecipeResponse, error)
	// List available recipes
	ListRecipes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RecipeNameListing, error)
	// Validate the recipe parameters meet the constraints provided by the recipe. Parameter enabled state is computed and returned in the response.
	RecipeValidateParameters(ctx context.Context, in *RecipeValidateParametersRequest, opts ...grpc.CallOption) (*RecipeValidateParametersResponse, error)
	// Automatically find SSH keys for the target
	FindSSHKeysForTarget(ctx context.Context, in *Target, opts ...grpc.CallOption) (*SSHKeyResponse, error)
	// Update one or more runs
	UpdateRuns(ctx context.Context, in *UpdateRunsRequest, opts ...grpc.CallOption) (*UpdateRunsResponse, error)
	// Lookup a message in the catalog
	LookupMessage(ctx context.Context, in *LookupMessageRequest, opts ...grpc.CallOption) (*LookupMessageResponse, error)
	// List the directories used by atperf (e.g. the engine logs directory)
	ListDirectories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListDirectoriesResponse, error)
	// Create a support package containing diagnostic logs and optional run exports
	CreateSupportPackage(ctx context.Context, in *CreateSupportPackageRequest, opts ...grpc.CallOption) (*CreateSupportPackageResponse, error)
	// Fetch data required by the MCP server to generate insights
	GetRunSummaryBundle(ctx context.Context, in *RunSummaryBundleRequest, opts ...grpc.CallOption) (*RunSummaryBundleResponse, error)
}

type apapClient struct {
	cc grpc.ClientConnInterface
}

func NewApapClient(cc grpc.ClientConnInterface) ApapClient {
	return &apapClient{cc}
}

func (c *apapClient) Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Apap_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceVersion)
	err := c.cc.Invoke(ctx, Apap_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) GetTelemetrySpecification(ctx context.Context, in *GetTelemetrySpecificationRequest, opts ...grpc.CallOption) (*GetTelemetrySpecificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTelemetrySpecificationResponse)
	err := c.cc.Invoke(ctx, Apap_GetTelemetrySpecification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) ListRuns(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RunListing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunListing)
	err := c.cc.Invoke(ctx, Apap_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) GetRunDescription(ctx context.Context, in *GetRunDescriptionRequest, opts ...grpc.CallOption) (*RunDescription, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunDescription)
	err := c.cc.Invoke(ctx, Apap_GetRunDescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) RenameRun(ctx context.Context, in *RunRenameRequest, opts ...grpc.CallOption) (*RunRenameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunRenameResponse)
	err := c.cc.Invoke(ctx, Apap_RenameRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) InvokeRender(ctx context.Context, in *InvokeRenderRequest, opts ...grpc.CallOption) (*InvokeRenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeRenderResponse)
	err := c.cc.Invoke(ctx, Apap_InvokeRender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) PrepareRender(ctx context.Context, in *PrepareRenderRequest, opts ...grpc.CallOption) (*PrepareRenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareRenderResponse)
	err := c.cc.Invoke(ctx, Apap_PrepareRender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) ListRenders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RenderListing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderListing)
	err := c.cc.Invoke(ctx, Apap_ListRenders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) CloseRender(ctx context.Context, in *CloseRenderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Apap_CloseRender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (Apap_QueryClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Apap_ServiceDesc.Streams[0], Apap_Query_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &apapQueryClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Apap_QueryClient interface {
	Recv() (*QueryResponse, error)
	grpc.ClientStream
}

type apapQueryClient struct {
	grpc.ClientStream
}

func (x *apapQueryClient) Recv() (*QueryResponse, error) {
	m := new(QueryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apapClient) RecipeIssueCommand(ctx context.Context, in *RecipeCommand, opts ...grpc.CallOption) (Apap_RecipeIssueCommandClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Apap_ServiceDesc.Streams[1], Apap_RecipeIssueCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &apapRecipeIssueCommandClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Apap_RecipeIssueCommandClient interface {
	Recv() (*RecipeResponse, error)
	grpc.ClientStream
}

type apapRecipeIssueCommandClient struct {
	grpc.ClientStream
}

func (x *apapRecipeIssueCommandClient) Recv() (*RecipeResponse, error) {
	m := new(RecipeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apapClient) RecipeReady(ctx context.Context, in *RecipeReadyRequest, opts ...grpc.CallOption) (*RecipeReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecipeReadyResponse)
	err := c.cc.Invoke(ctx, Apap_RecipeReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) TargetTest(ctx context.Context, in *TargetTestRequest, opts ...grpc.CallOption) (*TargetTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetTestResponse)
	err := c.cc.Invoke(ctx, Apap_TargetTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) TargetPrepare(ctx context.Context, in *TargetPrepareRequest, opts ...grpc.CallOption) (*TargetPrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetPrepareResponse)
	err := c.cc.Invoke(ctx, Apap_TargetPrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) DeleteRun(ctx context.Context, in *RunId, opts ...grpc.CallOption) (*DeleteRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRunResponse)
	err := c.cc.Invoke(ctx, Apap_DeleteRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) DeleteRuns(ctx context.Context, in *DeleteRunsRequest, opts ...grpc.CallOption) (*DeleteRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRunsResponse)
	err := c.cc.Invoke(ctx, Apap_DeleteRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) ExportRun(ctx context.Context, in *RunExportRequest, opts ...grpc.CallOption) (*RunExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunExportResponse)
	err := c.cc.Invoke(ctx, Apap_ExportRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) TargetInfoCollector(ctx context.Context, in *TargetInfoRequest, opts ...grpc.CallOption) (*TargetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetInfoResponse)
	err := c.cc.Invoke(ctx, Apap_TargetInfoCollector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) ListAndroidPackages(ctx context.Context, in *ListAndroidPackagesRequest, opts ...grpc.CallOption) (*ListAndroidPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAndroidPackagesResponse)
	err := c.cc.Invoke(ctx, Apap_ListAndroidPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) ImportRun(ctx context.Context, in *RunImportRequest, opts ...grpc.CallOption) (*RunImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunImportResponse)
	err := c.cc.Invoke(ctx, Apap_ImportRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) ListPrivateSSHKeys(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PrivateSSHKeyListing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrivateSSHKeyListing)
	err := c.cc.Invoke(ctx, Apap_ListPrivateSSHKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) ParseRecipe(ctx context.Context, in *ParseRecipeMessage, opts ...grpc.CallOption) (*ParseRecipeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseRecipeResponse)
	err := c.cc.Invoke(ctx, Apap_ParseRecipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) ListRecipes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RecipeNameListing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecipeNameListing)
	err := c.cc.Invoke(ctx, Apap_ListRecipes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) RecipeValidateParameters(ctx context.Context, in *RecipeValidateParametersRequest, opts ...grpc.CallOption) (*RecipeValidateParametersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecipeValidateParametersResponse)
	err := c.cc.Invoke(ctx, Apap_RecipeValidateParameters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) FindSSHKeysForTarget(ctx context.Context, in *Target, opts ...grpc.CallOption) (*SSHKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSHKeyResponse)
	err := c.cc.Invoke(ctx, Apap_FindSSHKeysForTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) UpdateRuns(ctx context.Context, in *UpdateRunsRequest, opts ...grpc.CallOption) (*UpdateRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRunsResponse)
	err := c.cc.Invoke(ctx, Apap_UpdateRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) LookupMessage(ctx context.Context, in *LookupMessageRequest, opts ...grpc.CallOption) (*LookupMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupMessageResponse)
	err := c.cc.Invoke(ctx, Apap_LookupMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) ListDirectories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListDirectoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirectoriesResponse)
	err := c.cc.Invoke(ctx, Apap_ListDirectories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) CreateSupportPackage(ctx context.Context, in *CreateSupportPackageRequest, opts ...grpc.CallOption) (*CreateSupportPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSupportPackageResponse)
	err := c.cc.Invoke(ctx, Apap_CreateSupportPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apapClient) GetRunSummaryBundle(ctx context.Context, in *RunSummaryBundleRequest, opts ...grpc.CallOption) (*RunSummaryBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunSummaryBundleResponse)
	err := c.cc.Invoke(ctx, Apap_GetRunSummaryBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApapServer is the server API for Apap service.
// All implementations must embed UnimplementedApapServer
// for forward compatibility
//
// Arm Performance Analysis Platform Service Definition
type ApapServer interface {
	// Requests that the server should shut down
	Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Get the version of the connected server
	GetVersion(context.Context, *emptypb.Empty) (*ServiceVersion, error)
	// Get the telemetry specification for a supported CPU model
	GetTelemetrySpecification(context.Context, *GetTelemetrySpecificationRequest) (*GetTelemetrySpecificationResponse, error)
	// Return descriptions of all runs
	ListRuns(context.Context, *emptypb.Empty) (*RunListing, error)
	// Return description a single run
	GetRunDescription(context.Context, *GetRunDescriptionRequest) (*RunDescription, error)
	// Rename run
	RenameRun(context.Context, *RunRenameRequest) (*RunRenameResponse, error)
	// Invoke renderer(s) - primitive for calling renderers directly
	InvokeRender(context.Context, *InvokeRenderRequest) (*InvokeRenderResponse, error)
	// Prepare for calling InvokeRender - primitive for calling the recipe to obtain the rendering and visualization configuration
	PrepareRender(context.Context, *PrepareRenderRequest) (*PrepareRenderResponse, error)
	// List all active render sessions and their respective memory usages
	ListRenders(context.Context, *emptypb.Empty) (*RenderListing, error)
	// Close an active renderer session
	CloseRender(context.Context, *CloseRenderRequest) (*emptypb.Empty, error)
	// Query rendered data
	Query(*QueryRequest, Apap_QueryServer) error
	// Requests that the server should run the specified recipe command on the target
	RecipeIssueCommand(*RecipeCommand, Apap_RecipeIssueCommandServer) error
	// Check whether a recipe is ready to run on a target
	RecipeReady(context.Context, *RecipeReadyRequest) (*RecipeReadyResponse, error)
	// Test the connection to the target server
	TargetTest(context.Context, *TargetTestRequest) (*TargetTestResponse, error)
	// Test the connection to the target server
	TargetPrepare(context.Context, *TargetPrepareRequest) (*TargetPrepareResponse, error)
	// Delete a run
	DeleteRun(context.Context, *RunId) (*DeleteRunResponse, error)
	// Delete multiple runs
	DeleteRuns(context.Context, *DeleteRunsRequest) (*DeleteRunsResponse, error)
	// Export a run
	ExportRun(context.Context, *RunExportRequest) (*RunExportResponse, error)
	// Collect target information
	TargetInfoCollector(context.Context, *TargetInfoRequest) (*TargetInfoResponse, error)
	// List Android packages and their activities for the target.
	ListAndroidPackages(context.Context, *ListAndroidPackagesRequest) (*ListAndroidPackagesResponse, error)
	// Import a run
	ImportRun(context.Context, *RunImportRequest) (*RunImportResponse, error)
	// List private SSH keys found in common search directories on the host machine.
	ListPrivateSSHKeys(context.Context, *emptypb.Empty) (*PrivateSSHKeyListing, error)
	// Parse the named recipe and return its definition. If a target is provided parameter value functions will be executed
	// and the target info will be exposed.
	ParseRecipe(context.Context, *ParseRecipeMessage) (*ParseRecipeResponse, error)
	// List available recipes
	ListRecipes(context.Context, *emptypb.Empty) (*RecipeNameListing, error)
	// Validate the recipe parameters meet the constraints provided by the recipe. Parameter enabled state is computed and returned in the response.
	RecipeValidateParameters(context.Context, *RecipeValidateParametersRequest) (*RecipeValidateParametersResponse, error)
	// Automatically find SSH keys for the target
	FindSSHKeysForTarget(context.Context, *Target) (*SSHKeyResponse, error)
	// Update one or more runs
	UpdateRuns(context.Context, *UpdateRunsRequest) (*UpdateRunsResponse, error)
	// Lookup a message in the catalog
	LookupMessage(context.Context, *LookupMessageRequest) (*LookupMessageResponse, error)
	// List the directories used by atperf (e.g. the engine logs directory)
	ListDirectories(context.Context, *emptypb.Empty) (*ListDirectoriesResponse, error)
	// Create a support package containing diagnostic logs and optional run exports
	CreateSupportPackage(context.Context, *CreateSupportPackageRequest) (*CreateSupportPackageResponse, error)
	// Fetch data required by the MCP server to generate insights
	GetRunSummaryBundle(context.Context, *RunSummaryBundleRequest) (*RunSummaryBundleResponse, error)
	mustEmbedUnimplementedApapServer()
}

// UnimplementedApapServer must be embedded to have forward compatible implementations.
type UnimplementedApapServer struct {
}

func (UnimplementedApapServer) Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedApapServer) GetVersion(context.Context, *emptypb.Empty) (*ServiceVersion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedApapServer) GetTelemetrySpecification(context.Context, *GetTelemetrySpecificationRequest) (*GetTelemetrySpecificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTelemetrySpecification not implemented")
}
func (UnimplementedApapServer) ListRuns(context.Context, *emptypb.Empty) (*RunListing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedApapServer) GetRunDescription(context.Context, *GetRunDescriptionRequest) (*RunDescription, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunDescription not implemented")
}
func (UnimplementedApapServer) RenameRun(context.Context, *RunRenameRequest) (*RunRenameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameRun not implemented")
}
func (UnimplementedApapServer) InvokeRender(context.Context, *InvokeRenderRequest) (*InvokeRenderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeRender not implemented")
}
func (UnimplementedApapServer) PrepareRender(context.Context, *PrepareRenderRequest) (*PrepareRenderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareRender not implemented")
}
func (UnimplementedApapServer) ListRenders(context.Context, *emptypb.Empty) (*RenderListing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRenders not implemented")
}
func (UnimplementedApapServer) CloseRender(context.Context, *CloseRenderRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseRender not implemented")
}
func (UnimplementedApapServer) Query(*QueryRequest, Apap_QueryServer) error {
	return status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedApapServer) RecipeIssueCommand(*RecipeCommand, Apap_RecipeIssueCommandServer) error {
	return status.Errorf(codes.Unimplemented, "method RecipeIssueCommand not implemented")
}
func (UnimplementedApapServer) RecipeReady(context.Context, *RecipeReadyRequest) (*RecipeReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecipeReady not implemented")
}
func (UnimplementedApapServer) TargetTest(context.Context, *TargetTestRequest) (*TargetTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TargetTest not implemented")
}
func (UnimplementedApapServer) TargetPrepare(context.Context, *TargetPrepareRequest) (*TargetPrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TargetPrepare not implemented")
}
func (UnimplementedApapServer) DeleteRun(context.Context, *RunId) (*DeleteRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRun not implemented")
}
func (UnimplementedApapServer) DeleteRuns(context.Context, *DeleteRunsRequest) (*DeleteRunsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRuns not implemented")
}
func (UnimplementedApapServer) ExportRun(context.Context, *RunExportRequest) (*RunExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportRun not implemented")
}
func (UnimplementedApapServer) TargetInfoCollector(context.Context, *TargetInfoRequest) (*TargetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TargetInfoCollector not implemented")
}
func (UnimplementedApapServer) ListAndroidPackages(context.Context, *ListAndroidPackagesRequest) (*ListAndroidPackagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAndroidPackages not implemented")
}
func (UnimplementedApapServer) ImportRun(context.Context, *RunImportRequest) (*RunImportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportRun not implemented")
}
func (UnimplementedApapServer) ListPrivateSSHKeys(context.Context, *emptypb.Empty) (*PrivateSSHKeyListing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPrivateSSHKeys not implemented")
}
func (UnimplementedApapServer) ParseRecipe(context.Context, *ParseRecipeMessage) (*ParseRecipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseRecipe not implemented")
}
func (UnimplementedApapServer) ListRecipes(context.Context, *emptypb.Empty) (*RecipeNameListing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecipes not implemented")
}
func (UnimplementedApapServer) RecipeValidateParameters(context.Context, *RecipeValidateParametersRequest) (*RecipeValidateParametersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecipeValidateParameters not implemented")
}
func (UnimplementedApapServer) FindSSHKeysForTarget(context.Context, *Target) (*SSHKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSSHKeysForTarget not implemented")
}
func (UnimplementedApapServer) UpdateRuns(context.Context, *UpdateRunsRequest) (*UpdateRunsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRuns not implemented")
}
func (UnimplementedApapServer) LookupMessage(context.Context, *LookupMessageRequest) (*LookupMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupMessage not implemented")
}
func (UnimplementedApapServer) ListDirectories(context.Context, *emptypb.Empty) (*ListDirectoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDirectories not implemented")
}
func (UnimplementedApapServer) CreateSupportPackage(context.Context, *CreateSupportPackageRequest) (*CreateSupportPackageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSupportPackage not implemented")
}
func (UnimplementedApapServer) GetRunSummaryBundle(context.Context, *RunSummaryBundleRequest) (*RunSummaryBundleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunSummaryBundle not implemented")
}
func (UnimplementedApapServer) mustEmbedUnimplementedApapServer() {}

// UnsafeApapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApapServer will
// result in compilation errors.
type UnsafeApapServer interface {
	mustEmbedUnimplementedApapServer()
}

func RegisterApapServer(s grpc.ServiceRegistrar, srv ApapServer) {
	s.RegisterService(&Apap_ServiceDesc, srv)
}

func _Apap_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).Shutdown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).GetVersion(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_GetTelemetrySpecification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTelemetrySpecificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).GetTelemetrySpecification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_GetTelemetrySpecification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).GetTelemetrySpecification(ctx, req.(*GetTelemetrySpecificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).ListRuns(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_GetRunDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).GetRunDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_GetRunDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).GetRunDescription(ctx, req.(*GetRunDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_RenameRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).RenameRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_RenameRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).RenameRun(ctx, req.(*RunRenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_InvokeRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).InvokeRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_InvokeRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).InvokeRender(ctx, req.(*InvokeRenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_PrepareRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).PrepareRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_PrepareRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).PrepareRender(ctx, req.(*PrepareRenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_ListRenders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).ListRenders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_ListRenders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).ListRenders(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_CloseRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).CloseRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_CloseRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).CloseRender(ctx, req.(*CloseRenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApapServer).Query(m, &apapQueryServer{ServerStream: stream})
}

type Apap_QueryServer interface {
	Send(*QueryResponse) error
	grpc.ServerStream
}

type apapQueryServer struct {
	grpc.ServerStream
}

func (x *apapQueryServer) Send(m *QueryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Apap_RecipeIssueCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RecipeCommand)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApapServer).RecipeIssueCommand(m, &apapRecipeIssueCommandServer{ServerStream: stream})
}

type Apap_RecipeIssueCommandServer interface {
	Send(*RecipeResponse) error
	grpc.ServerStream
}

type apapRecipeIssueCommandServer struct {
	grpc.ServerStream
}

func (x *apapRecipeIssueCommandServer) Send(m *RecipeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Apap_RecipeReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecipeReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).RecipeReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_RecipeReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).RecipeReady(ctx, req.(*RecipeReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_TargetTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).TargetTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_TargetTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).TargetTest(ctx, req.(*TargetTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_TargetPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetPrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).TargetPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_TargetPrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).TargetPrepare(ctx, req.(*TargetPrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_DeleteRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).DeleteRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_DeleteRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).DeleteRun(ctx, req.(*RunId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_DeleteRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).DeleteRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_DeleteRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).DeleteRuns(ctx, req.(*DeleteRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_ExportRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).ExportRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_ExportRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).ExportRun(ctx, req.(*RunExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_TargetInfoCollector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).TargetInfoCollector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_TargetInfoCollector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).TargetInfoCollector(ctx, req.(*TargetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_ListAndroidPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAndroidPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).ListAndroidPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_ListAndroidPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).ListAndroidPackages(ctx, req.(*ListAndroidPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_ImportRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).ImportRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_ImportRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).ImportRun(ctx, req.(*RunImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_ListPrivateSSHKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).ListPrivateSSHKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_ListPrivateSSHKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).ListPrivateSSHKeys(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_ParseRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRecipeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).ParseRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_ParseRecipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).ParseRecipe(ctx, req.(*ParseRecipeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_ListRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).ListRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_ListRecipes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).ListRecipes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_RecipeValidateParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecipeValidateParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).RecipeValidateParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_RecipeValidateParameters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).RecipeValidateParameters(ctx, req.(*RecipeValidateParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_FindSSHKeysForTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).FindSSHKeysForTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_FindSSHKeysForTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).FindSSHKeysForTarget(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_UpdateRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).UpdateRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_UpdateRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).UpdateRuns(ctx, req.(*UpdateRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_LookupMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).LookupMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_LookupMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).LookupMessage(ctx, req.(*LookupMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_ListDirectories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).ListDirectories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_ListDirectories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).ListDirectories(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_CreateSupportPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupportPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).CreateSupportPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_CreateSupportPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).CreateSupportPackage(ctx, req.(*CreateSupportPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apap_GetRunSummaryBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSummaryBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApapServer).GetRunSummaryBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Apap_GetRunSummaryBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApapServer).GetRunSummaryBundle(ctx, req.(*RunSummaryBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Apap_ServiceDesc is the grpc.ServiceDesc for Apap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Apap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apap.Apap",
	HandlerType: (*ApapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shutdown",
			Handler:    _Apap_Shutdown_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _Apap_GetVersion_Handler,
		},
		{
			MethodName: "GetTelemetrySpecification",
			Handler:    _Apap_GetTelemetrySpecification_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _Apap_ListRuns_Handler,
		},
		{
			MethodName: "GetRunDescription",
			Handler:    _Apap_GetRunDescription_Handler,
		},
		{
			MethodName: "RenameRun",
			Handler:    _Apap_RenameRun_Handler,
		},
		{
			MethodName: "InvokeRender",
			Handler:    _Apap_InvokeRender_Handler,
		},
		{
			MethodName: "PrepareRender",
			Handler:    _Apap_PrepareRender_Handler,
		},
		{
			MethodName: "ListRenders",
			Handler:    _Apap_ListRenders_Handler,
		},
		{
			MethodName: "CloseRender",
			Handler:    _Apap_CloseRender_Handler,
		},
		{
			MethodName: "RecipeReady",
			Handler:    _Apap_RecipeReady_Handler,
		},
		{
			MethodName: "TargetTest",
			Handler:    _Apap_TargetTest_Handler,
		},
		{
			MethodName: "TargetPrepare",
			Handler:    _Apap_TargetPrepare_Handler,
		},
		{
			MethodName: "DeleteRun",
			Handler:    _Apap_DeleteRun_Handler,
		},
		{
			MethodName: "DeleteRuns",
			Handler:    _Apap_DeleteRuns_Handler,
		},
		{
			MethodName: "ExportRun",
			Handler:    _Apap_ExportRun_Handler,
		},
		{
			MethodName: "TargetInfoCollector",
			Handler:    _Apap_TargetInfoCollector_Handler,
		},
		{
			MethodName: "ListAndroidPackages",
			Handler:    _Apap_ListAndroidPackages_Handler,
		},
		{
			MethodName: "ImportRun",
			Handler:    _Apap_ImportRun_Handler,
		},
		{
			MethodName: "ListPrivateSSHKeys",
			Handler:    _Apap_ListPrivateSSHKeys_Handler,
		},
		{
			MethodName: "ParseRecipe",
			Handler:    _Apap_ParseRecipe_Handler,
		},
		{
			MethodName: "ListRecipes",
			Handler:    _Apap_ListRecipes_Handler,
		},
		{
			MethodName: "RecipeValidateParameters",
			Handler:    _Apap_RecipeValidateParameters_Handler,
		},
		{
			MethodName: "FindSSHKeysForTarget",
			Handler:    _Apap_FindSSHKeysForTarget_Handler,
		},
		{
			MethodName: "UpdateRuns",
			Handler:    _Apap_UpdateRuns_Handler,
		},
		{
			MethodName: "LookupMessage",
			Handler:    _Apap_LookupMessage_Handler,
		},
		{
			MethodName: "ListDirectories",
			Handler:    _Apap_ListDirectories_Handler,
		},
		{
			MethodName: "CreateSupportPackage",
			Handler:    _Apap_CreateSupportPackage_Handler,
		},
		{
			MethodName: "GetRunSummaryBundle",
			Handler:    _Apap_GetRunSummaryBundle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _Apap_Query_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecipeIssueCommand",
			Handler:       _Apap_RecipeIssueCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "apapproto/apap.proto",
}
