// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.23.4
// source: tetherproto/tether.proto

package tetherproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PulseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PulseRequest) Reset() {
	*x = PulseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tetherproto_tether_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PulseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulseRequest) ProtoMessage() {}

func (x *PulseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tetherproto_tether_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulseRequest.ProtoReflect.Descriptor instead.
func (*PulseRequest) Descriptor() ([]byte, []int) {
	return file_tetherproto_tether_proto_rawDescGZIP(), []int{0}
}

type PulseAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PulseAck) Reset() {
	*x = PulseAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tetherproto_tether_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PulseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulseAck) ProtoMessage() {}

func (x *PulseAck) ProtoReflect() protoreflect.Message {
	mi := &file_tetherproto_tether_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulseAck.ProtoReflect.Descriptor instead.
func (*PulseAck) Descriptor() ([]byte, []int) {
	return file_tetherproto_tether_proto_rawDescGZIP(), []int{1}
}

var File_tetherproto_tether_proto protoreflect.FileDescriptor

var file_tetherproto_tether_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x65, 0x74, 0x68, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65,
	0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x65, 0x74, 0x68,
	0x65, 0x72, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x75, 0x6c, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x0a, 0x0a, 0x08, 0x50, 0x75, 0x6c, 0x73, 0x65, 0x41, 0x63, 0x6b, 0x32, 0x3c,
	0x0a, 0x06, 0x54, 0x65, 0x74, 0x68, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x04, 0x48, 0x6f, 0x6c, 0x64,
	0x12, 0x14, 0x2e, 0x74, 0x65, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x6c, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x74, 0x65, 0x74, 0x68, 0x65, 0x72, 0x2e,
	0x50, 0x75, 0x6c, 0x73, 0x65, 0x41, 0x63, 0x6b, 0x28, 0x01, 0x30, 0x01, 0x42, 0x36, 0x5a, 0x34,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x72, 0x6d, 0x2d, 0x44,
	0x65, 0x62, 0x75, 0x67, 0x2f, 0x61, 0x70, 0x61, 0x70, 0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x74, 0x65, 0x74, 0x68, 0x65, 0x72, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tetherproto_tether_proto_rawDescOnce sync.Once
	file_tetherproto_tether_proto_rawDescData = file_tetherproto_tether_proto_rawDesc
)

func file_tetherproto_tether_proto_rawDescGZIP() []byte {
	file_tetherproto_tether_proto_rawDescOnce.Do(func() {
		file_tetherproto_tether_proto_rawDescData = protoimpl.X.CompressGZIP(file_tetherproto_tether_proto_rawDescData)
	})
	return file_tetherproto_tether_proto_rawDescData
}

var file_tetherproto_tether_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tetherproto_tether_proto_goTypes = []any{
	(*PulseRequest)(nil), // 0: tether.PulseRequest
	(*PulseAck)(nil),     // 1: tether.PulseAck
}
var file_tetherproto_tether_proto_depIdxs = []int32{
	0, // 0: tether.Tether.Hold:input_type -> tether.PulseRequest
	1, // 1: tether.Tether.Hold:output_type -> tether.PulseAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tetherproto_tether_proto_init() }
func file_tetherproto_tether_proto_init() {
	if File_tetherproto_tether_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tetherproto_tether_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PulseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tetherproto_tether_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PulseAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tetherproto_tether_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tetherproto_tether_proto_goTypes,
		DependencyIndexes: file_tetherproto_tether_proto_depIdxs,
		MessageInfos:      file_tetherproto_tether_proto_msgTypes,
	}.Build()
	File_tetherproto_tether_proto = out.File
	file_tetherproto_tether_proto_rawDesc = nil
	file_tetherproto_tether_proto_goTypes = nil
	file_tetherproto_tether_proto_depIdxs = nil
}
