// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.23.4
// source: tetherproto/tether.proto

package tetherproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Tether_Hold_FullMethodName = "/tether.Tether/Hold"
)

// TetherClient is the client API for Tether service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TetherClient interface {
	// Hold keeps the connection open, sending periodic pulses. The server
	// will close the connection if no pulse is received within a timeout
	// period.
	Hold(ctx context.Context, opts ...grpc.CallOption) (Tether_HoldClient, error)
}

type tetherClient struct {
	cc grpc.ClientConnInterface
}

func NewTetherClient(cc grpc.ClientConnInterface) TetherClient {
	return &tetherClient{cc}
}

func (c *tetherClient) Hold(ctx context.Context, opts ...grpc.CallOption) (Tether_HoldClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tether_ServiceDesc.Streams[0], Tether_Hold_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &tetherHoldClient{ClientStream: stream}
	return x, nil
}

type Tether_HoldClient interface {
	Send(*PulseRequest) error
	Recv() (*PulseAck, error)
	grpc.ClientStream
}

type tetherHoldClient struct {
	grpc.ClientStream
}

func (x *tetherHoldClient) Send(m *PulseRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tetherHoldClient) Recv() (*PulseAck, error) {
	m := new(PulseAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TetherServer is the server API for Tether service.
// All implementations must embed UnimplementedTetherServer
// for forward compatibility
type TetherServer interface {
	// Hold keeps the connection open, sending periodic pulses. The server
	// will close the connection if no pulse is received within a timeout
	// period.
	Hold(Tether_HoldServer) error
	mustEmbedUnimplementedTetherServer()
}

// UnimplementedTetherServer must be embedded to have forward compatible implementations.
type UnimplementedTetherServer struct {
}

func (UnimplementedTetherServer) Hold(Tether_HoldServer) error {
	return status.Errorf(codes.Unimplemented, "method Hold not implemented")
}
func (UnimplementedTetherServer) mustEmbedUnimplementedTetherServer() {}

// UnsafeTetherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TetherServer will
// result in compilation errors.
type UnsafeTetherServer interface {
	mustEmbedUnimplementedTetherServer()
}

func RegisterTetherServer(s grpc.ServiceRegistrar, srv TetherServer) {
	s.RegisterService(&Tether_ServiceDesc, srv)
}

func _Tether_Hold_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TetherServer).Hold(&tetherHoldServer{ServerStream: stream})
}

type Tether_HoldServer interface {
	Send(*PulseAck) error
	Recv() (*PulseRequest, error)
	grpc.ServerStream
}

type tetherHoldServer struct {
	grpc.ServerStream
}

func (x *tetherHoldServer) Send(m *PulseAck) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tetherHoldServer) Recv() (*PulseRequest, error) {
	m := new(PulseRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Tether_ServiceDesc is the grpc.ServiceDesc for Tether service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tether_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tether.Tether",
	HandlerType: (*TetherServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Hold",
			Handler:       _Tether_Hold_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tetherproto/tether.proto",
}
