// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

//go:build ignore

// This file is used to generate message code constants from the base (English) catalog.
// Message codes are assumed to be identical across all localized versions.
// Therefore only the English catalog is used to generate these constants.

// Usage:
// Either generate all files as part of scripts/generate-all.sh
// Or individually generate with go run gen_codes.go in the message-gen directory.

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/Arm-Debug/apap-cli/apap-engine/licenseheader"
	"github.com/Arm-Debug/apap-cli/apap-engine/message/messageutil"
	"github.com/Arm-Debug/apap-cli/apap-engine/perms"
)

// Relative path to the catalog.json file
const inputPath = "../message/catalog_en-US.json"
const outputPath = "../message/codes.go"

// flatten walks nested maps and collects all fully qualified keys like engine.recipe.run.SOME_ERROR
func flatten(prefix string, m map[string]any, out *[]string) {
	for k, v := range m {
		if messageutil.IsCatalogMetadataKey(k) {
			continue
		}
		key := k
		if prefix != "" {
			key = prefix + "." + k
		}

		switch val := v.(type) {
		case map[string]any:
			// Detect message leaf node by checking if it contains a "Message" key
			if _, isLeaf := val["Message"]; isLeaf {
				*out = append(*out, key)
			} else {
				flatten(key, val, out)
			}
		}
	}
}

// Converts engine.recipe.run.SOME_ERROR to EngineRecipeRunSomeError
func toConstName(s string) string {
	parts := strings.Split(s, ".")
	if len(parts) == 0 {
		return ""
	}

	var buf strings.Builder

	for _, part := range parts {
		// Split each part on underscores
		subParts := strings.Split(part, "_")
		for _, sub := range subParts {
			if sub == "" {
				continue
			}
			buf.WriteString(strings.Title(strings.ToLower(sub)))
		}
	}

	return buf.String()
}

func main() {
	// Read and parse the catalog
	data, err := os.ReadFile(filepath.Clean(inputPath))
	if err != nil {
		panic(fmt.Errorf("failed to read %s: %w", inputPath, err))
	}

	var catalog map[string]any
	if err := json.Unmarshal(data, &catalog); err != nil {
		panic(fmt.Errorf("failed to parse catalog: %w", err))
	}

	var keys []string
	flatten("", catalog, &keys)

	sort.Strings(keys)

	// Open file to write generated constants
	f, err := os.OpenFile(filepath.Clean(outputPath), os.O_CREATE|os.O_TRUNC|os.O_WRONLY, perms.LocalFilePerm)
	if err != nil {
		panic(fmt.Errorf("failed to write output: %w", err))
	}
	defer f.Close()

	if err := licenseheader.WriteGo(f, repoRoot()); err != nil {
		panic(err)
	}
	fmt.Fprintln(f, "// Code generated by gen_codes.go; DO NOT EDIT.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "// Message codes are assumed to be identical across all localized versions of the message catalog.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "package message")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "const (")

	for _, key := range keys {
		fmt.Fprintf(f, "\t%s MessageCode = \"%s\"\n", toConstName(key), key)
	}

	fmt.Fprintln(f, ")")
}

func repoRoot() string {
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		panic("failed to locate generator source file")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(sourceFile), "..", "..", ".."))
}
