// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

//go:build ignore

package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"

	"github.com/Arm-Debug/apap-cli/apap-engine/licenseheader"
	"github.com/Arm-Debug/apap-cli/apap-engine/perms"
)

type cpuCatalog struct {
	CPUs []cpuEntry `json:"cpus"`
}

type cpuEntry struct {
	Name  string `json:"name"`
	CPUID string `json:"cpuid"`
}

func main() {
	inputPath := flag.String("in", "", "path to cpus.json")
	outputPath := flag.String("out", "", "path to generated Go file")
	flag.Parse()

	if *inputPath == "" || *outputPath == "" {
		fmt.Fprintln(os.Stderr, "-in and -out are required")
		os.Exit(2)
	}

	input, err := os.ReadFile(*inputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read %s: %v\n", *inputPath, err)
		os.Exit(1)
	}

	var catalog cpuCatalog
	if err := json.Unmarshal(input, &catalog); err != nil {
		fmt.Fprintf(os.Stderr, "failed to parse %s: %v\n", *inputPath, err)
		os.Exit(1)
	}

	names := map[uint32]string{}
	for _, cpu := range catalog.CPUs {
		if cpu.CPUID == "" {
			continue
		}
		id, err := strconv.ParseUint(strings.TrimPrefix(cpu.CPUID, "0x"), 16, 32)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to parse cpuid %q: %v\n", cpu.CPUID, err)
			os.Exit(1)
		}

		// cpus.json contains the correct brand name e.g. "Neoverse V2" but Gator reports the name
		// with hyphens e.g. "Neoverse-V2", so we need a fixup here for backwards compatibility.
		name := strings.ReplaceAll(cpu.Name, " ", "-")

		if prev, exists := names[uint32(id)]; exists && prev != name {
			fmt.Fprintf(os.Stderr, "conflicting cpu names for %#x: %q vs %q\n", uint32(id), prev, name)
			os.Exit(1)
		}
		names[uint32(id)] = name
	}

	keys := make([]uint32, 0, len(names))
	for id := range names {
		keys = append(keys, id)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })

	var out bytes.Buffer
	if err := licenseheader.WriteGo(&out, repoRoot()); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	out.WriteString("// To download cpus.json and generate cpus.go run scripts/update-arm-cpus.py.\n")
	out.WriteString("// Changes to cpus.json should be made in https://github.com/ARM-software/data\n")
	out.WriteString("\n")
	out.WriteString("package armcpus\n")
	out.WriteString("\n")
	out.WriteString("// CpuidToName maps an Arm cpuid to a display name. The cpuid is the implementor code + part number from the MIDR.\n")
	out.WriteString("var CpuidToName = map[uint32]string{\n")
	for _, id := range keys {
		fmt.Fprintf(&out, "\t0x%x: %s,\n", id, strconv.Quote(names[id]))
	}
	out.WriteString("}\n")

	if err := os.WriteFile(*outputPath, out.Bytes(), perms.LocalFilePerm); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *outputPath, err)
		os.Exit(1)
	}
}

func repoRoot() string {
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		fmt.Fprintln(os.Stderr, "failed to locate generator source file")
		os.Exit(1)
	}
	return filepath.Clean(filepath.Join(filepath.Dir(sourceFile), "..", "..", "..", ".."))
}
