# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0

# Optional gRPC stub regeneration. Replaces core/scripts/protobuf/generate.sh.
#
# Two differences from the shell script are deliberate:
#
#   1. The script ran "go install" for protoc-gen-go, protoc-gen-go-grpc and
#      mockery on every invocation, which fetched and built plugins from the
#      network as a side effect of code generation. Here the plugins are located
#      on PATH, and their versions are checked rather than imposed. Fetching
#      them is a separate, explicit step.
#   2. protoc itself is required rather than installed, so it comes from the
#      platform package manager.

include_guard(GLOBAL)

set(PERFORMIX_PROTOC_MINIMUM_VERSION "23.4" CACHE STRING
    "Minimum accepted protoc version")

set(PERFORMIX_PROTOC_GEN_GO_VERSION "v1.34.2" CACHE STRING
    "protoc-gen-go version expected by the generated stubs")

set(PERFORMIX_PROTOC_GEN_GO_GRPC_VERSION "v1.4.0" CACHE STRING
    "protoc-gen-go-grpc version expected by the generated stubs")

set(PERFORMIX_MOCKERY_VERSION "v2.53.3" CACHE STRING
    "mockery version expected by the generated mocks")

find_program(PERFORMIX_PROTOC NAMES protoc)
if(NOT PERFORMIX_PROTOC)
  message(FATAL_ERROR
    "PERFORMIX_REGENERATE_PROTO is ON but protoc was not found.\n"
    "Install the protobuf compiler provided by your distribution, for example:\n"
    "  zypper install protobuf-devel\n"
    "  apt install protobuf-compiler\n"
    "Or turn the option off; the generated stubs under core/clients/go are\n"
    "checked in and are only stale if the .proto files changed.")
endif()

execute_process(
  COMMAND "${PERFORMIX_PROTOC}" --version
  OUTPUT_VARIABLE _protoc_version_raw
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(_protoc_version_raw MATCHES "([0-9]+\\.[0-9]+(\\.[0-9]+)?)")
  set(PERFORMIX_PROTOC_VERSION "${CMAKE_MATCH_1}")
  if(PERFORMIX_PROTOC_VERSION VERSION_LESS PERFORMIX_PROTOC_MINIMUM_VERSION)
    message(FATAL_ERROR
      "protoc ${PERFORMIX_PROTOC_VERSION} is older than the required "
      "${PERFORMIX_PROTOC_MINIMUM_VERSION}.")
  endif()
endif()

find_program(PERFORMIX_PROTOC_GEN_GO NAMES protoc-gen-go
  HINTS "$ENV{GOBIN}" "$ENV{HOME}/go/bin")
find_program(PERFORMIX_PROTOC_GEN_GO_GRPC NAMES protoc-gen-go-grpc
  HINTS "$ENV{GOBIN}" "$ENV{HOME}/go/bin")

foreach(_plugin PROTOC_GEN_GO PROTOC_GEN_GO_GRPC)
  if(NOT PERFORMIX_${_plugin})
    message(FATAL_ERROR
      "Protobuf plugin not found for ${_plugin}.\n"
      "Install the pinned versions once, into a directory on PATH:\n"
      "  go install google.golang.org/protobuf/cmd/protoc-gen-go@${PERFORMIX_PROTOC_GEN_GO_VERSION}\n"
      "  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@${PERFORMIX_PROTOC_GEN_GO_GRPC_VERSION}")
  endif()
endforeach()

set(PERFORMIX_PROTO_SOURCE_DIR "${PERFORMIX_CORE_DIR}/api")
set(PERFORMIX_PROTO_OUTPUT_DIR "${PERFORMIX_CORE_DIR}/clients/go")

file(GLOB_RECURSE PERFORMIX_PROTO_FILES CONFIGURE_DEPENDS
     "${PERFORMIX_PROTO_SOURCE_DIR}/*.proto")

get_filename_component(_protoc_dir "${PERFORMIX_PROTOC_GEN_GO}" DIRECTORY)

add_custom_target(proto
  COMMAND "${CMAKE_COMMAND}" -E make_directory "${PERFORMIX_PROTO_OUTPUT_DIR}"
  COMMAND "${CMAKE_COMMAND}" -E env
          "PATH=${_protoc_dir}:$ENV{PATH}"
          "${PERFORMIX_PROTOC}"
          "--proto_path=${PERFORMIX_PROTO_SOURCE_DIR}"
          "--go_out=${PERFORMIX_PROTO_OUTPUT_DIR}"
          "--go_opt=paths=source_relative"
          "--go-grpc_out=${PERFORMIX_PROTO_OUTPUT_DIR}"
          "--go-grpc_opt=paths=source_relative"
          ${PERFORMIX_PROTO_FILES}
  COMMENT "Generating gRPC stubs from core/api"
  VERBATIM)

# Mocks are generated by mockery from the interfaces in the freshly generated
# stubs, so they are a separate step chained after proto.
find_program(PERFORMIX_MOCKERY NAMES mockery HINTS "$ENV{GOBIN}" "$ENV{HOME}/go/bin")
if(PERFORMIX_MOCKERY)
  set(_boilerplate "${CMAKE_BINARY_DIR}/mockery-boilerplate.txt")
  file(READ "${PERFORMIX_ROOT_DIR}/copyright-license-header.txt" _header)
  string(REGEX REPLACE "\n" "\n// " _header_commented "// ${_header}")
  file(WRITE "${_boilerplate}" "${_header_commented}\n")

  add_custom_target(proto-mocks
    COMMAND "${CMAKE_COMMAND}" -E chdir "${PERFORMIX_PROTO_OUTPUT_DIR}"
            "${PERFORMIX_MOCKERY}" --boilerplate-file "${_boilerplate}"
    COMMENT "Generating mocks for the gRPC clients"
    VERBATIM)
  add_dependencies(proto-mocks proto)
else()
  message(STATUS
    "mockery not found; the proto-mocks target is unavailable. "
    "Install it with: go install github.com/vektra/mockery/v2@${PERFORMIX_MOCKERY_VERSION}")
endif()
